/*
 * ntp_keyword.h
 * 
 * NOTE: edit this file with caution, it is generated by keyword-gen.c
 *	 Generated 2017-10-03 09:37:20 UTC	  diff_ignore_line
 *
 */
#include "ntp_scanner.h"
#include "ntp_parser.h"

#define LOWEST_KEYWORD_ID 258

const char * const keyword_text[197] = {
	/* 0       258             T_Abbrev */	"abbrev",
	/* 1       259                T_Age */	"age",
	/* 2       260                T_All */	"all",
	/* 3       261              T_Allan */	"allan",
	/* 4       262           T_Allpeers */	"allpeers",
	/* 5       263               T_Auth */	"auth",
	/* 6       264            T_Autokey */	"autokey",
	/* 7       265            T_Automax */	"automax",
	/* 8       266            T_Average */	"average",
	/* 9       267           T_Basedate */	"basedate",
	/* 10      268            T_Bclient */	"bclient",
	/* 11      269        T_Bcpollbstep */	"bcpollbstep",
	/* 12      270             T_Beacon */	"beacon",
	/* 13      271          T_Broadcast */	"broadcast",
	/* 14      272    T_Broadcastclient */	"broadcastclient",
	/* 15      273     T_Broadcastdelay */	"broadcastdelay",
	/* 16      274              T_Burst */	"burst",
	/* 17      275          T_Calibrate */	"calibrate",
	/* 18      276            T_Ceiling */	"ceiling",
	/* 19      277         T_Clockstats */	"clockstats",
	/* 20      278             T_Cohort */	"cohort",
	/* 21      279         T_ControlKey */	"controlkey",
	/* 22      280             T_Crypto */	"crypto",
	/* 23      281        T_Cryptostats */	"cryptostats",
	/* 24      282                T_Ctl */	"ctl",
	/* 25      283                T_Day */	"day",
	/* 26      284            T_Default */	"default",
	/* 27      285             T_Digest */	"digest",
	/* 28      286            T_Disable */	"disable",
	/* 29      287            T_Discard */	"discard",
	/* 30      288         T_Dispersion */	"dispersion",
	/* 31      289             T_Double */	NULL,
	/* 32      290          T_Driftfile */	"driftfile",
	/* 33      291               T_Drop */	"drop",
	/* 34      292               T_Dscp */	"dscp",
	/* 35      293           T_Ellipsis */	"...",
	/* 36      294             T_Enable */	"enable",
	/* 37      295                T_End */	"end",
	/* 38      296              T_False */	NULL,
	/* 39      297               T_File */	"file",
	/* 40      298            T_Filegen */	"filegen",
	/* 41      299            T_Filenum */	"filenum",
	/* 42      300              T_Flag1 */	"flag1",
	/* 43      301              T_Flag2 */	"flag2",
	/* 44      302              T_Flag3 */	"flag3",
	/* 45      303              T_Flag4 */	"flag4",
	/* 46      304              T_Flake */	"flake",
	/* 47      305              T_Floor */	"floor",
	/* 48      306               T_Freq */	"freq",
	/* 49      307              T_Fudge */	"fudge",
	/* 50      308               T_Host */	"host",
	/* 51      309           T_Huffpuff */	"huffpuff",
	/* 52      310             T_Iburst */	"iburst",
	/* 53      311              T_Ident */	"ident",
	/* 54      312             T_Ignore */	"ignore",
	/* 55      313           T_Incalloc */	"incalloc",
	/* 56      314             T_Incmem */	"incmem",
	/* 57      315          T_Initalloc */	"initalloc",
	/* 58      316            T_Initmem */	"initmem",
	/* 59      317        T_Includefile */	"includefile",
	/* 60      318            T_Integer */	NULL,
	/* 61      319          T_Interface */	"interface",
	/* 62      320           T_Intrange */	NULL,
	/* 63      321                 T_Io */	"io",
	/* 64      322               T_Ipv4 */	"ipv4",
	/* 65      323          T_Ipv4_flag */	"-4",
	/* 66      324               T_Ipv6 */	"ipv6",
	/* 67      325          T_Ipv6_flag */	"-6",
	/* 68      326             T_Kernel */	"kernel",
	/* 69      327                T_Key */	"key",
	/* 70      328               T_Keys */	"keys",
	/* 71      329            T_Keysdir */	"keysdir",
	/* 72      330                T_Kod */	"kod",
	/* 73      331             T_Mssntp */	"mssntp",
	/* 74      332           T_Leapfile */	"leapfile",
	/* 75      333  T_Leapsmearinterval */	"leapsmearinterval",
	/* 76      334            T_Limited */	"limited",
	/* 77      335               T_Link */	"link",
	/* 78      336             T_Listen */	"listen",
	/* 79      337          T_Logconfig */	"logconfig",
	/* 80      338            T_Logfile */	"logfile",
	/* 81      339          T_Loopstats */	"loopstats",
	/* 82      340        T_Lowpriotrap */	"lowpriotrap",
	/* 83      341     T_Manycastclient */	"manycastclient",
	/* 84      342     T_Manycastserver */	"manycastserver",
	/* 85      343               T_Mask */	"mask",
	/* 86      344             T_Maxage */	"maxage",
	/* 87      345           T_Maxclock */	"maxclock",
	/* 88      346           T_Maxdepth */	"maxdepth",
	/* 89      347            T_Maxdist */	"maxdist",
	/* 90      348             T_Maxmem */	"maxmem",
	/* 91      349            T_Maxpoll */	"maxpoll",
	/* 92      350          T_Mdnstries */	"mdnstries",
	/* 93      351                T_Mem */	"mem",
	/* 94      352            T_Memlock */	"memlock",
	/* 95      353           T_Minclock */	"minclock",
	/* 96      354           T_Mindepth */	"mindepth",
	/* 97      355            T_Mindist */	"mindist",
	/* 98      356            T_Minimum */	"minimum",
	/* 99      357            T_Minpoll */	"minpoll",
	/* 100     358            T_Minsane */	"minsane",
	/* 101     359               T_Mode */	"mode",
	/* 102     360              T_Mode7 */	"mode7",
	/* 103     361            T_Monitor */	"monitor",
	/* 104     362              T_Month */	"month",
	/* 105     363                T_Mru */	"mru",
	/* 106     364    T_Multicastclient */	"multicastclient",
	/* 107     365                T_Nic */	"nic",
	/* 108     366             T_Nolink */	"nolink",
	/* 109     367           T_Nomodify */	"nomodify",
	/* 110     368          T_Nomrulist */	"nomrulist",
	/* 111     369               T_None */	"none",
	/* 112     370        T_Nonvolatile */	"nonvolatile",
	/* 113     371             T_Nopeer */	"nopeer",
	/* 114     372            T_Noquery */	"noquery",
	/* 115     373           T_Noselect */	"noselect",
	/* 116     374            T_Noserve */	"noserve",
	/* 117     375             T_Notrap */	"notrap",
	/* 118     376            T_Notrust */	"notrust",
	/* 119     377                T_Ntp */	"ntp",
	/* 120     378            T_Ntpport */	"ntpport",
	/* 121     379     T_NtpSignDsocket */	"ntpsigndsocket",
	/* 122     380             T_Orphan */	"orphan",
	/* 123     381         T_Orphanwait */	"orphanwait",
	/* 124     382          T_PCEdigest */	"peer_clear_digest_early",
	/* 125     383              T_Panic */	"panic",
	/* 126     384               T_Peer */	"peer",
	/* 127     385          T_Peerstats */	"peerstats",
	/* 128     386              T_Phone */	"phone",
	/* 129     387                T_Pid */	"pid",
	/* 130     388            T_Pidfile */	"pidfile",
	/* 131     389               T_Pool */	"pool",
	/* 132     390               T_Port */	"port",
	/* 133     391            T_Preempt */	"preempt",
	/* 134     392             T_Prefer */	"prefer",
	/* 135     393         T_Protostats */	"protostats",
	/* 136     394                 T_Pw */	"pw",
	/* 137     395           T_Randfile */	"randfile",
	/* 138     396           T_Rawstats */	"rawstats",
	/* 139     397              T_Refid */	"refid",
	/* 140     398         T_Requestkey */	"requestkey",
	/* 141     399              T_Reset */	"reset",
	/* 142     400           T_Restrict */	"restrict",
	/* 143     401             T_Revoke */	"revoke",
	/* 144     402             T_Rlimit */	"rlimit",
	/* 145     403      T_Saveconfigdir */	"saveconfigdir",
	/* 146     404             T_Server */	"server",
	/* 147     405             T_Setvar */	"setvar",
	/* 148     406             T_Source */	"source",
	/* 149     407          T_Stacksize */	"stacksize",
	/* 150     408         T_Statistics */	"statistics",
	/* 151     409              T_Stats */	"stats",
	/* 152     410           T_Statsdir */	"statsdir",
	/* 153     411               T_Step */	"step",
	/* 154     412           T_Stepback */	"stepback",
	/* 155     413            T_Stepfwd */	"stepfwd",
	/* 156     414            T_Stepout */	"stepout",
	/* 157     415            T_Stratum */	"stratum",
	/* 158     416             T_String */	NULL,
	/* 159     417                T_Sys */	"sys",
	/* 160     418           T_Sysstats */	"sysstats",
	/* 161     419               T_Tick */	"tick",
	/* 162     420              T_Time1 */	"time1",
	/* 163     421              T_Time2 */	"time2",
	/* 164     422              T_Timer */	"timer",
	/* 165     423        T_Timingstats */	"timingstats",
	/* 166     424             T_Tinker */	"tinker",
	/* 167     425                T_Tos */	"tos",
	/* 168     426               T_Trap */	"trap",
	/* 169     427               T_True */	"true",
	/* 170     428         T_Trustedkey */	"trustedkey",
	/* 171     429                T_Ttl */	"ttl",
	/* 172     430               T_Type */	"type",
	/* 173     431              T_U_int */	NULL,
	/* 174     432           T_UEcrypto */	"unpeer_crypto_early",
	/* 175     433        T_UEcryptonak */	"unpeer_crypto_nak_early",
	/* 176     434           T_UEdigest */	"unpeer_digest_early",
	/* 177     435           T_Unconfig */	"unconfig",
	/* 178     436             T_Unpeer */	"unpeer",
	/* 179     437            T_Version */	"version",
	/* 180     438    T_WanderThreshold */	NULL,
	/* 181     439               T_Week */	"week",
	/* 182     440           T_Wildcard */	"wildcard",
	/* 183     441             T_Xleave */	"xleave",
	/* 184     442               T_Year */	"year",
	/* 185     443               T_Flag */	NULL,
	/* 186     444                T_EOC */	NULL,
	/* 187     445           T_Simulate */	"simulate",
	/* 188     446         T_Beep_Delay */	"beep_delay",
	/* 189     447       T_Sim_Duration */	"simulation_duration",
	/* 190     448      T_Server_Offset */	"server_offset",
	/* 191     449           T_Duration */	"duration",
	/* 192     450        T_Freq_Offset */	"freq_offset",
	/* 193     451             T_Wander */	"wander",
	/* 194     452             T_Jitter */	"jitter",
	/* 195     453         T_Prop_Delay */	"prop_delay",
	/* 196     454         T_Proc_Delay */	"proc_delay"
};

#define SCANNER_INIT_S 922

const scan_state sst[925] = {
/*SS_T( ch,	f-by, match, other ),				 */
  0,				      /*     0                   */
  S_ST( '-',	3,      325,     0 ), /*     1                   */
  S_ST( '.',	3,        3,     1 ), /*     2                   */
  S_ST( '.',	3,      293,     0 ), /*     3 .                 */
  S_ST( 'a',	3,       23,     2 ), /*     4                   */
  S_ST( 'b',	3,        6,     0 ), /*     5 a                 */
  S_ST( 'b',	3,        7,     0 ), /*     6 ab                */
  S_ST( 'r',	3,        8,     0 ), /*     7 abb               */
  S_ST( 'e',	3,      258,     0 ), /*     8 abbr              */
  S_ST( 'g',	3,      259,     5 ), /*     9 a                 */
  S_ST( 'l',	3,      260,     9 ), /*    10 a                 */
  S_ST( 'a',	3,      261,     0 ), /*    11 all               */
  S_ST( 'p',	3,       13,    11 ), /*    12 all               */
  S_ST( 'e',	3,       14,     0 ), /*    13 allp              */
  S_ST( 'e',	3,       15,     0 ), /*    14 allpe             */
  S_ST( 'r',	3,      262,     0 ), /*    15 allpee            */
  S_ST( 'u',	3,       17,    10 ), /*    16 a                 */
  S_ST( 't',	3,       18,     0 ), /*    17 au                */
  S_ST( 'o',	3,       21,   263 ), /*    18 aut               */
  S_ST( 'k',	3,       20,     0 ), /*    19 auto              */
  S_ST( 'e',	3,      264,     0 ), /*    20 autok             */
  S_ST( 'm',	3,       22,    19 ), /*    21 auto              */
  S_ST( 'a',	3,      265,     0 ), /*    22 autom             */
  S_ST( 'v',	3,       24,    16 ), /*    23 a                 */
  S_ST( 'e',	3,       25,     0 ), /*    24 av                */
  S_ST( 'r',	3,       26,     0 ), /*    25 ave               */
  S_ST( 'a',	3,       27,     0 ), /*    26 aver              */
  S_ST( 'g',	3,      266,     0 ), /*    27 avera             */
  S_ST( 'b',	3,       75,     4 ), /*    28                   */
  S_ST( 'a',	3,       30,     0 ), /*    29 b                 */
  S_ST( 's',	3,       31,     0 ), /*    30 ba                */
  S_ST( 'e',	3,       32,     0 ), /*    31 bas               */
  S_ST( 'd',	3,       33,     0 ), /*    32 base              */
  S_ST( 'a',	3,       34,     0 ), /*    33 based             */
  S_ST( 't',	3,      267,     0 ), /*    34 baseda            */
  S_ST( 'c',	3,       40,    29 ), /*    35 b                 */
  S_ST( 'l',	3,       37,     0 ), /*    36 bc                */
  S_ST( 'i',	3,       38,     0 ), /*    37 bcl               */
  S_ST( 'e',	3,       39,     0 ), /*    38 bcli              */
  S_ST( 'n',	3,      268,     0 ), /*    39 bclie             */
  S_ST( 'p',	3,       41,    36 ), /*    40 bc                */
  S_ST( 'o',	3,       42,     0 ), /*    41 bcp               */
  S_ST( 'l',	3,       43,     0 ), /*    42 bcpo              */
  S_ST( 'l',	3,       44,     0 ), /*    43 bcpol             */
  S_ST( 'b',	3,       45,     0 ), /*    44 bcpoll            */
  S_ST( 's',	3,       46,     0 ), /*    45 bcpollb           */
  S_ST( 't',	3,       47,     0 ), /*    46 bcpollbs          */
  S_ST( 'e',	3,      269,     0 ), /*    47 bcpollbst         */
  S_ST( 'e',	3,       52,    35 ), /*    48 b                 */
  S_ST( 'a',	3,       50,     0 ), /*    49 be                */
  S_ST( 'c',	3,       51,     0 ), /*    50 bea               */
  S_ST( 'o',	3,      270,     0 ), /*    51 beac              */
  S_ST( 'e',	3,       53,    49 ), /*    52 be                */
  S_ST( 'p',	3,       54,     0 ), /*    53 bee               */
  S_ST( '_',	3,       55,     0 ), /*    54 beep              */
  S_ST( 'd',	3,       56,     0 ), /*    55 beep_             */
  S_ST( 'e',	3,       57,     0 ), /*    56 beep_d            */
  S_ST( 'l',	3,       58,     0 ), /*    57 beep_de           */
  S_ST( 'a',	3,      446,     0 ), /*    58 beep_del          */
  S_ST( 'r',	3,       60,    48 ), /*    59 b                 */
  S_ST( 'o',	3,       61,     0 ), /*    60 br                */
  S_ST( 'a',	3,       62,     0 ), /*    61 bro               */
  S_ST( 'd',	3,       63,     0 ), /*    62 broa              */
  S_ST( 'c',	3,       64,     0 ), /*    63 broad             */
  S_ST( 'a',	3,       65,     0 ), /*    64 broadc            */
  S_ST( 's',	3,      271,     0 ), /*    65 broadca           */
  S_ST( 'c',	3,       67,     0 ), /*    66 broadcast         */
  S_ST( 'l',	3,       68,     0 ), /*    67 broadcastc        */
  S_ST( 'i',	3,       69,     0 ), /*    68 broadcastcl       */
  S_ST( 'e',	3,       70,     0 ), /*    69 broadcastcli      */
  S_ST( 'n',	3,      272,     0 ), /*    70 broadcastclie     */
  S_ST( 'd',	3,       72,    66 ), /*    71 broadcast         */
  S_ST( 'e',	3,       73,     0 ), /*    72 broadcastd        */
  S_ST( 'l',	3,       74,     0 ), /*    73 broadcastde       */
  S_ST( 'a',	3,      273,     0 ), /*    74 broadcastdel      */
  S_ST( 'u',	3,       76,    59 ), /*    75 b                 */
  S_ST( 'r',	3,       77,     0 ), /*    76 bu                */
  S_ST( 's',	3,      274,     0 ), /*    77 bur               */
  S_ST( 'c',	3,      118,    28 ), /*    78                   */
  S_ST( 'a',	3,       80,     0 ), /*    79 c                 */
  S_ST( 'l',	3,       81,     0 ), /*    80 ca                */
  S_ST( 'i',	3,       82,     0 ), /*    81 cal               */
  S_ST( 'b',	3,       83,     0 ), /*    82 cali              */
  S_ST( 'r',	3,       84,     0 ), /*    83 calib             */
  S_ST( 'a',	3,       85,     0 ), /*    84 calibr            */
  S_ST( 't',	3,      275,     0 ), /*    85 calibra           */
  S_ST( 'e',	3,       87,    79 ), /*    86 c                 */
  S_ST( 'i',	3,       88,     0 ), /*    87 ce                */
  S_ST( 'l',	3,       89,     0 ), /*    88 cei               */
  S_ST( 'i',	3,       90,     0 ), /*    89 ceil              */
  S_ST( 'n',	3,      276,     0 ), /*    90 ceili             */
  S_ST( 'l',	3,       92,    86 ), /*    91 c                 */
  S_ST( 'o',	3,       93,     0 ), /*    92 cl                */
  S_ST( 'c',	3,       94,     0 ), /*    93 clo               */
  S_ST( 'k',	3,       95,     0 ), /*    94 cloc              */
  S_ST( 's',	3,       96,     0 ), /*    95 clock             */
  S_ST( 't',	3,       97,     0 ), /*    96 clocks            */
  S_ST( 'a',	3,       98,     0 ), /*    97 clockst           */
  S_ST( 't',	3,      277,     0 ), /*    98 clocksta          */
  S_ST( 'o',	3,      103,    91 ), /*    99 c                 */
  S_ST( 'h',	3,      101,     0 ), /*   100 co                */
  S_ST( 'o',	3,      102,     0 ), /*   101 coh               */
  S_ST( 'r',	3,      278,     0 ), /*   102 coho              */
  S_ST( 'n',	3,      104,   100 ), /*   103 co                */
  S_ST( 't',	3,      105,     0 ), /*   104 con               */
  S_ST( 'r',	3,      106,     0 ), /*   105 cont              */
  S_ST( 'o',	3,      107,     0 ), /*   106 contr             */
  S_ST( 'l',	3,      108,     0 ), /*   107 contro            */
  S_ST( 'k',	3,      109,     0 ), /*   108 control           */
  S_ST( 'e',	3,      279,     0 ), /*   109 controlk          */
  S_ST( 'r',	3,      111,    99 ), /*   110 c                 */
  S_ST( 'y',	3,      112,     0 ), /*   111 cr                */
  S_ST( 'p',	3,      113,     0 ), /*   112 cry               */
  S_ST( 't',	3,      280,     0 ), /*   113 cryp              */
  S_ST( 's',	3,      115,     0 ), /*   114 crypto            */
  S_ST( 't',	3,      116,     0 ), /*   115 cryptos           */
  S_ST( 'a',	3,      117,     0 ), /*   116 cryptost          */
  S_ST( 't',	3,      281,     0 ), /*   117 cryptosta         */
  S_ST( 't',	3,      282,   110 ), /*   118 c                 */
  S_ST( 'd',	3,      153,    78 ), /*   119                   */
  S_ST( 'a',	3,      283,     0 ), /*   120 d                 */
  S_ST( 'e',	3,      122,   120 ), /*   121 d                 */
  S_ST( 'f',	3,      123,     0 ), /*   122 de                */
  S_ST( 'a',	3,      124,     0 ), /*   123 def               */
  S_ST( 'u',	3,      125,     0 ), /*   124 defa              */
  S_ST( 'l',	3,      284,     0 ), /*   125 defau             */
  S_ST( 'i',	3,      130,   121 ), /*   126 d                 */
  S_ST( 'g',	3,      128,     0 ), /*   127 di                */
  S_ST( 'e',	3,      129,     0 ), /*   128 dig               */
  S_ST( 's',	3,      285,     0 ), /*   129 dige              */
  S_ST( 's',	3,      137,   127 ), /*   130 di                */
  S_ST( 'a',	3,      132,     0 ), /*   131 dis               */
  S_ST( 'b',	3,      133,     0 ), /*   132 disa              */
  S_ST( 'l',	3,      286,     0 ), /*   133 disab             */
  S_ST( 'c',	3,      135,   131 ), /*   134 dis               */
  S_ST( 'a',	3,      136,     0 ), /*   135 disc              */
  S_ST( 'r',	3,      287,     0 ), /*   136 disca             */
  S_ST( 'p',	3,      138,   134 ), /*   137 dis               */
  S_ST( 'e',	3,      139,     0 ), /*   138 disp              */
  S_ST( 'r',	3,      140,     0 ), /*   139 dispe             */
  S_ST( 's',	3,      141,     0 ), /*   140 disper            */
  S_ST( 'i',	3,      142,     0 ), /*   141 dispers           */
  S_ST( 'o',	3,      288,     0 ), /*   142 dispersi          */
  S_ST( 'r',	3,      150,   126 ), /*   143 d                 */
  S_ST( 'i',	3,      145,     0 ), /*   144 dr                */
  S_ST( 'f',	3,      146,     0 ), /*   145 dri               */
  S_ST( 't',	3,      147,     0 ), /*   146 drif              */
  S_ST( 'f',	3,      148,     0 ), /*   147 drift             */
  S_ST( 'i',	3,      149,     0 ), /*   148 driftf            */
  S_ST( 'l',	3,      290,     0 ), /*   149 driftfi           */
  S_ST( 'o',	3,      291,   144 ), /*   150 dr                */
  S_ST( 's',	3,      152,   143 ), /*   151 d                 */
  S_ST( 'c',	3,      292,     0 ), /*   152 ds                */
  S_ST( 'u',	3,      154,   151 ), /*   153 d                 */
  S_ST( 'r',	3,      155,     0 ), /*   154 du                */
  S_ST( 'a',	3,      156,     0 ), /*   155 dur               */
  S_ST( 't',	3,      157,     0 ), /*   156 dura              */
  S_ST( 'i',	3,      158,     0 ), /*   157 durat             */
  S_ST( 'o',	3,      449,     0 ), /*   158 durati            */
  S_ST( 'e',	3,      160,   119 ), /*   159                   */
  S_ST( 'n',	3,      295,     0 ), /*   160 e                 */
  S_ST( 'a',	3,      162,     0 ), /*   161 en                */
  S_ST( 'b',	3,      163,     0 ), /*   162 ena               */
  S_ST( 'l',	3,      294,     0 ), /*   163 enab              */
  S_ST( 'f',	3,      185,   159 ), /*   164                   */
  S_ST( 'i',	3,      166,     0 ), /*   165 f                 */
  S_ST( 'l',	3,      297,     0 ), /*   166 fi                */
  S_ST( 'g',	3,      168,     0 ), /*   167 file              */
  S_ST( 'e',	3,      298,     0 ), /*   168 fileg             */
  S_ST( 'n',	3,      170,   167 ), /*   169 file              */
  S_ST( 'u',	3,      299,     0 ), /*   170 filen             */
  S_ST( 'l',	3,      175,   165 ), /*   171 f                 */
  S_ST( 'a',	3,      174,     0 ), /*   172 fl                */
  S_ST( 'g',	3,      303,     0 ), /*   173 fla               */
  S_ST( 'k',	3,      304,   173 ), /*   174 fla               */
  S_ST( 'o',	3,      176,   172 ), /*   175 fl                */
  S_ST( 'o',	3,      305,     0 ), /*   176 flo               */
  S_ST( 'r',	3,      178,   171 ), /*   177 f                 */
  S_ST( 'e',	3,      306,     0 ), /*   178 fr                */
  S_ST( '_',	3,      180,     0 ), /*   179 freq              */
  S_ST( 'o',	3,      181,     0 ), /*   180 freq_             */
  S_ST( 'f',	3,      182,     0 ), /*   181 freq_o            */
  S_ST( 'f',	3,      183,     0 ), /*   182 freq_of           */
  S_ST( 's',	3,      184,     0 ), /*   183 freq_off          */
  S_ST( 'e',	3,      450,     0 ), /*   184 freq_offs         */
  S_ST( 'u',	3,      186,   177 ), /*   185 f                 */
  S_ST( 'd',	3,      187,     0 ), /*   186 fu                */
  S_ST( 'g',	3,      307,     0 ), /*   187 fud               */
  S_ST( 'h',	3,      191,   164 ), /*   188                   */
  S_ST( 'o',	3,      190,     0 ), /*   189 h                 */
  S_ST( 's',	3,      308,     0 ), /*   190 ho                */
  S_ST( 'u',	3,      192,   189 ), /*   191 h                 */
  S_ST( 'f',	3,      193,     0 ), /*   192 hu                */
  S_ST( 'f',	3,      194,     0 ), /*   193 huf               */
  S_ST( 'p',	3,      195,     0 ), /*   194 huff              */
  S_ST( 'u',	3,      196,     0 ), /*   195 huffp             */
  S_ST( 'f',	3,      309,     0 ), /*   196 huffpu            */
  S_ST( 'i',	3,      238,   188 ), /*   197                   */
  S_ST( 'b',	3,      199,     0 ), /*   198 i                 */
  S_ST( 'u',	3,      200,     0 ), /*   199 ib                */
  S_ST( 'r',	3,      201,     0 ), /*   200 ibu               */
  S_ST( 's',	3,      310,     0 ), /*   201 ibur              */
  S_ST( 'd',	3,      203,   198 ), /*   202 i                 */
  S_ST( 'e',	3,      204,     0 ), /*   203 id                */
  S_ST( 'n',	3,      311,     0 ), /*   204 ide               */
  S_ST( 'g',	3,      206,   202 ), /*   205 i                 */
  S_ST( 'n',	3,      207,     0 ), /*   206 ig                */
  S_ST( 'o',	3,      208,     0 ), /*   207 ign               */
  S_ST( 'r',	3,      312,     0 ), /*   208 igno              */
  S_ST( 'n',	3,      232,   205 ), /*   209 i                 */
  S_ST( 'c',	3,      222,     0 ), /*   210 in                */
  S_ST( 'a',	3,      212,     0 ), /*   211 inc               */
  S_ST( 'l',	3,      213,     0 ), /*   212 inca              */
  S_ST( 'l',	3,      214,     0 ), /*   213 incal             */
  S_ST( 'o',	3,      313,     0 ), /*   214 incall            */
  S_ST( 'l',	3,      216,   211 ), /*   215 inc               */
  S_ST( 'u',	3,      217,     0 ), /*   216 incl              */
  S_ST( 'd',	3,      218,     0 ), /*   217 inclu             */
  S_ST( 'e',	3,      219,     0 ), /*   218 includ            */
  S_ST( 'f',	3,      220,     0 ), /*   219 include           */
  S_ST( 'i',	3,      221,     0 ), /*   220 includef          */
  S_ST( 'l',	3,      317,     0 ), /*   221 includefi         */
  S_ST( 'm',	3,      223,   215 ), /*   222 inc               */
  S_ST( 'e',	3,      314,     0 ), /*   223 incm              */
  S_ST( 'i',	3,      225,   210 ), /*   224 in                */
  S_ST( 't',	3,      230,     0 ), /*   225 ini               */
  S_ST( 'a',	3,      227,     0 ), /*   226 init              */
  S_ST( 'l',	3,      228,     0 ), /*   227 inita             */
  S_ST( 'l',	3,      229,     0 ), /*   228 inital            */
  S_ST( 'o',	3,      315,     0 ), /*   229 initall           */
  S_ST( 'm',	3,      231,   226 ), /*   230 init              */
  S_ST( 'e',	3,      316,     0 ), /*   231 initm             */
  S_ST( 't',	3,      233,   224 ), /*   232 in                */
  S_ST( 'e',	3,      234,     0 ), /*   233 int               */
  S_ST( 'r',	3,      235,     0 ), /*   234 inte              */
  S_ST( 'f',	3,      236,     0 ), /*   235 inter             */
  S_ST( 'a',	3,      237,     0 ), /*   236 interf            */
  S_ST( 'c',	3,      319,     0 ), /*   237 interfa           */
  S_ST( 'p',	3,      239,   321 ), /*   238 i                 */
  S_ST( 'v',	3,      324,     0 ), /*   239 ip                */
  S_ST( 'j',	3,      241,   197 ), /*   240                   */
  S_ST( 'i',	3,      242,     0 ), /*   241 j                 */
  S_ST( 't',	3,      243,     0 ), /*   242 ji                */
  S_ST( 't',	3,      244,     0 ), /*   243 jit               */
  S_ST( 'e',	3,      452,     0 ), /*   244 jitt              */
  S_ST( 'k',	3,      252,   240 ), /*   245                   */
  S_ST( 'e',	3,      327,     0 ), /*   246 k                 */
  S_ST( 'r',	3,      248,     0 ), /*   247 ke                */
  S_ST( 'n',	3,      249,     0 ), /*   248 ker               */
  S_ST( 'e',	3,      326,     0 ), /*   249 kern              */
  S_ST( 'd',	3,      251,     0 ), /*   250 keys              */
  S_ST( 'i',	3,      329,     0 ), /*   251 keysd             */
  S_ST( 'o',	3,      330,   246 ), /*   252 k                 */
  S_ST( 'l',	3,      469,   245 ), /*   253                   */
  S_ST( 'e',	3,      255,     0 ), /*   254 l                 */
  S_ST( 'a',	3,      256,     0 ), /*   255 le                */
  S_ST( 'p',	3,      318,     0 ), /*   256 lea               */
  S_ST( 'f',	3,      289,     0 ), /*   257 leap              */
  S_ST( 'v',	1,        0,     0 ), /*   258 T_Abbrev          */
  S_ST( 'e',	0,        0,     0 ), /*   259 T_Age             */
  S_ST( 'l',	0,       12,     0 ), /*   260 T_All             */
  S_ST( 'n',	0,        0,     0 ), /*   261 T_Allan           */
  S_ST( 's',	0,        0,     0 ), /*   262 T_Allpeers        */
  S_ST( 'h',	0,        0,     0 ), /*   263 T_Auth            */
  S_ST( 'y',	0,        0,     0 ), /*   264 T_Autokey         */
  S_ST( 'x',	0,        0,     0 ), /*   265 T_Automax         */
  S_ST( 'e',	0,        0,     0 ), /*   266 T_Average         */
  S_ST( 'e',	1,        0,     0 ), /*   267 T_Basedate        */
  S_ST( 't',	0,        0,     0 ), /*   268 T_Bclient         */
  S_ST( 'p',	0,        0,     0 ), /*   269 T_Bcpollbstep     */
  S_ST( 'n',	0,        0,     0 ), /*   270 T_Beacon          */
  S_ST( 't',	1,       71,     0 ), /*   271 T_Broadcast       */
  S_ST( 't',	0,        0,     0 ), /*   272 T_Broadcastclient */
  S_ST( 'y',	0,        0,     0 ), /*   273 T_Broadcastdelay  */
  S_ST( 't',	0,        0,     0 ), /*   274 T_Burst           */
  S_ST( 'e',	0,        0,     0 ), /*   275 T_Calibrate       */
  S_ST( 'g',	0,        0,     0 ), /*   276 T_Ceiling         */
  S_ST( 's',	0,        0,     0 ), /*   277 T_Clockstats      */
  S_ST( 't',	0,        0,     0 ), /*   278 T_Cohort          */
  S_ST( 'y',	0,        0,     0 ), /*   279 T_ControlKey      */
  S_ST( 'o',	0,      114,     0 ), /*   280 T_Crypto          */
  S_ST( 's',	0,        0,     0 ), /*   281 T_Cryptostats     */
  S_ST( 'l',	0,        0,     0 ), /*   282 T_Ctl             */
  S_ST( 'y',	0,        0,     0 ), /*   283 T_Day             */
  S_ST( 't',	0,        0,     0 ), /*   284 T_Default         */
  S_ST( 't',	1,        0,     0 ), /*   285 T_Digest          */
  S_ST( 'e',	0,        0,     0 ), /*   286 T_Disable         */
  S_ST( 'd',	0,        0,     0 ), /*   287 T_Discard         */
  S_ST( 'n',	0,        0,     0 ), /*   288 T_Dispersion      */
  S_ST( 'i',	3,      296,     0 ), /*   289 leapf             */
  S_ST( 'e',	1,        0,     0 ), /*   290 T_Driftfile       */
  S_ST( 'p',	0,        0,     0 ), /*   291 T_Drop            */
  S_ST( 'p',	0,        0,     0 ), /*   292 T_Dscp            */
  S_ST( '.',	0,        0,     0 ), /*   293 T_Ellipsis        */
  S_ST( 'e',	0,        0,     0 ), /*   294 T_Enable          */
  S_ST( 'd',	0,        0,   161 ), /*   295 T_End             */
  S_ST( 'l',	3,      332,     0 ), /*   296 leapfi            */
  S_ST( 'e',	1,      169,     0 ), /*   297 T_File            */
  S_ST( 'n',	0,        0,     0 ), /*   298 T_Filegen         */
  S_ST( 'm',	0,        0,     0 ), /*   299 T_Filenum         */
  S_ST( '1',	0,        0,     0 ), /*   300 T_Flag1           */
  S_ST( '2',	0,        0,   300 ), /*   301 T_Flag2           */
  S_ST( '3',	0,        0,   301 ), /*   302 T_Flag3           */
  S_ST( '4',	0,        0,   302 ), /*   303 T_Flag4           */
  S_ST( 'e',	0,        0,     0 ), /*   304 T_Flake           */
  S_ST( 'r',	0,        0,     0 ), /*   305 T_Floor           */
  S_ST( 'q',	0,      179,     0 ), /*   306 T_Freq            */
  S_ST( 'e',	1,        0,     0 ), /*   307 T_Fudge           */
  S_ST( 't',	1,        0,     0 ), /*   308 T_Host            */
  S_ST( 'f',	0,        0,     0 ), /*   309 T_Huffpuff        */
  S_ST( 't',	0,        0,     0 ), /*   310 T_Iburst          */
  S_ST( 't',	1,        0,     0 ), /*   311 T_Ident           */
  S_ST( 'e',	0,        0,     0 ), /*   312 T_Ignore          */
  S_ST( 'c',	0,        0,     0 ), /*   313 T_Incalloc        */
  S_ST( 'm',	0,        0,     0 ), /*   314 T_Incmem          */
  S_ST( 'c',	0,        0,     0 ), /*   315 T_Initalloc       */
  S_ST( 'm',	0,        0,     0 ), /*   316 T_Initmem         */
  S_ST( 'e',	1,        0,     0 ), /*   317 T_Includefile     */
  S_ST( 's',	3,      320,   257 ), /*   318 leap              */
  S_ST( 'e',	0,        0,     0 ), /*   319 T_Interface       */
  S_ST( 'm',	3,      416,     0 ), /*   320 leaps             */
  S_ST( 'o',	0,        0,   209 ), /*   321 T_Io              */
  S_ST( '4',	0,        0,     0 ), /*   322 T_Ipv4            */
  S_ST( '4',	0,        0,     0 ), /*   323 T_Ipv4_flag       */
  S_ST( '6',	0,        0,   322 ), /*   324 T_Ipv6            */
  S_ST( '6',	0,        0,   323 ), /*   325 T_Ipv6_flag       */
  S_ST( 'l',	0,        0,     0 ), /*   326 T_Kernel          */
  S_ST( 'y',	0,      328,   247 ), /*   327 T_Key             */
  S_ST( 's',	1,      250,     0 ), /*   328 T_Keys            */
  S_ST( 'r',	1,        0,     0 ), /*   329 T_Keysdir         */
  S_ST( 'd',	0,        0,     0 ), /*   330 T_Kod             */
  S_ST( 'p',	0,        0,     0 ), /*   331 T_Mssntp          */
  S_ST( 'e',	1,        0,     0 ), /*   332 T_Leapfile        */
  S_ST( 'l',	0,        0,     0 ), /*   333 T_Leapsmearinterval */
  S_ST( 'd',	0,        0,     0 ), /*   334 T_Limited         */
  S_ST( 'k',	0,        0,     0 ), /*   335 T_Link            */
  S_ST( 'n',	0,        0,     0 ), /*   336 T_Listen          */
  S_ST( 'g',	2,        0,     0 ), /*   337 T_Logconfig       */
  S_ST( 'e',	1,        0,     0 ), /*   338 T_Logfile         */
  S_ST( 's',	0,        0,     0 ), /*   339 T_Loopstats       */
  S_ST( 'p',	0,        0,     0 ), /*   340 T_Lowpriotrap     */
  S_ST( 't',	1,        0,     0 ), /*   341 T_Manycastclient  */
  S_ST( 'r',	2,        0,     0 ), /*   342 T_Manycastserver  */
  S_ST( 'k',	0,        0,     0 ), /*   343 T_Mask            */
  S_ST( 'e',	0,        0,     0 ), /*   344 T_Maxage          */
  S_ST( 'k',	0,        0,     0 ), /*   345 T_Maxclock        */
  S_ST( 'h',	0,        0,     0 ), /*   346 T_Maxdepth        */
  S_ST( 't',	0,        0,     0 ), /*   347 T_Maxdist         */
  S_ST( 'm',	0,        0,     0 ), /*   348 T_Maxmem          */
  S_ST( 'l',	0,        0,     0 ), /*   349 T_Maxpoll         */
  S_ST( 's',	0,        0,     0 ), /*   350 T_Mdnstries       */
  S_ST( 'm',	0,      538,     0 ), /*   351 T_Mem             */
  S_ST( 'k',	0,        0,     0 ), /*   352 T_Memlock         */
  S_ST( 'k',	0,        0,     0 ), /*   353 T_Minclock        */
  S_ST( 'h',	0,        0,     0 ), /*   354 T_Mindepth        */
  S_ST( 't',	0,        0,     0 ), /*   355 T_Mindist         */
  S_ST( 'm',	0,        0,     0 ), /*   356 T_Minimum         */
  S_ST( 'l',	0,        0,     0 ), /*   357 T_Minpoll         */
  S_ST( 'e',	0,        0,     0 ), /*   358 T_Minsane         */
  S_ST( 'e',	0,      360,     0 ), /*   359 T_Mode            */
  S_ST( '7',	0,        0,     0 ), /*   360 T_Mode7           */
  S_ST( 'r',	0,        0,     0 ), /*   361 T_Monitor         */
  S_ST( 'h',	0,        0,     0 ), /*   362 T_Month           */
  S_ST( 'u',	0,        0,     0 ), /*   363 T_Mru             */
  S_ST( 't',	2,        0,     0 ), /*   364 T_Multicastclient */
  S_ST( 'c',	0,        0,     0 ), /*   365 T_Nic             */
  S_ST( 'k',	0,        0,     0 ), /*   366 T_Nolink          */
  S_ST( 'y',	0,        0,     0 ), /*   367 T_Nomodify        */
  S_ST( 't',	0,        0,     0 ), /*   368 T_Nomrulist       */
  S_ST( 'e',	0,        0,     0 ), /*   369 T_None            */
  S_ST( 'e',	0,        0,     0 ), /*   370 T_Nonvolatile     */
  S_ST( 'r',	0,        0,     0 ), /*   371 T_Nopeer          */
  S_ST( 'y',	0,        0,     0 ), /*   372 T_Noquery         */
  S_ST( 't',	0,        0,     0 ), /*   373 T_Noselect        */
  S_ST( 'e',	0,        0,     0 ), /*   374 T_Noserve         */
  S_ST( 'p',	0,        0,     0 ), /*   375 T_Notrap          */
  S_ST( 't',	0,        0,     0 ), /*   376 T_Notrust         */
  S_ST( 'p',	0,      634,     0 ), /*   377 T_Ntp             */
  S_ST( 't',	0,        0,     0 ), /*   378 T_Ntpport         */
  S_ST( 't',	1,        0,     0 ), /*   379 T_NtpSignDsocket  */
  S_ST( 'n',	0,      649,     0 ), /*   380 T_Orphan          */
  S_ST( 't',	0,        0,     0 ), /*   381 T_Orphanwait      */
  S_ST( 'y',	0,        0,     0 ), /*   382 T_PCEdigest       */
  S_ST( 'c',	0,        0,     0 ), /*   383 T_Panic           */
  S_ST( 'r',	1,      676,     0 ), /*   384 T_Peer            */
  S_ST( 's',	0,        0,     0 ), /*   385 T_Peerstats       */
  S_ST( 'e',	2,        0,     0 ), /*   386 T_Phone           */
  S_ST( 'd',	0,      684,     0 ), /*   387 T_Pid             */
  S_ST( 'e',	1,        0,     0 ), /*   388 T_Pidfile         */
  S_ST( 'l',	1,        0,     0 ), /*   389 T_Pool            */
  S_ST( 't',	0,        0,     0 ), /*   390 T_Port            */
  S_ST( 't',	0,        0,     0 ), /*   391 T_Preempt         */
  S_ST( 'r',	0,        0,     0 ), /*   392 T_Prefer          */
  S_ST( 's',	0,        0,     0 ), /*   393 T_Protostats      */
  S_ST( 'w',	1,        0,   690 ), /*   394 T_Pw              */
  S_ST( 'e',	1,        0,     0 ), /*   395 T_Randfile        */
  S_ST( 's',	0,        0,     0 ), /*   396 T_Rawstats        */
  S_ST( 'd',	1,        0,     0 ), /*   397 T_Refid           */
  S_ST( 'y',	0,        0,     0 ), /*   398 T_Requestkey      */
  S_ST( 't',	0,        0,     0 ), /*   399 T_Reset           */
  S_ST( 't',	0,        0,     0 ), /*   400 T_Restrict        */
  S_ST( 'e',	0,        0,     0 ), /*   401 T_Revoke          */
  S_ST( 't',	0,        0,     0 ), /*   402 T_Rlimit          */
  S_ST( 'r',	1,        0,     0 ), /*   403 T_Saveconfigdir   */
  S_ST( 'r',	1,      767,     0 ), /*   404 T_Server          */
  S_ST( 'r',	1,        0,     0 ), /*   405 T_Setvar          */
  S_ST( 'e',	0,        0,     0 ), /*   406 T_Source          */
  S_ST( 'e',	0,        0,     0 ), /*   407 T_Stacksize       */
  S_ST( 's',	0,        0,     0 ), /*   408 T_Statistics      */
  S_ST( 's',	0,      810,   805 ), /*   409 T_Stats           */
  S_ST( 'r',	1,        0,     0 ), /*   410 T_Statsdir        */
  S_ST( 'p',	0,      818,     0 ), /*   411 T_Step            */
  S_ST( 'k',	0,        0,     0 ), /*   412 T_Stepback        */
  S_ST( 'd',	0,        0,     0 ), /*   413 T_Stepfwd         */
  S_ST( 't',	0,        0,     0 ), /*   414 T_Stepout         */
  S_ST( 'm',	0,        0,     0 ), /*   415 T_Stratum         */
  S_ST( 'e',	3,      431,     0 ), /*   416 leapsm            */
  S_ST( 's',	0,      825,     0 ), /*   417 T_Sys             */
  S_ST( 's',	0,        0,     0 ), /*   418 T_Sysstats        */
  S_ST( 'k',	0,        0,     0 ), /*   419 T_Tick            */
  S_ST( '1',	0,        0,     0 ), /*   420 T_Time1           */
  S_ST( '2',	0,        0,   420 ), /*   421 T_Time2           */
  S_ST( 'r',	0,        0,   421 ), /*   422 T_Timer           */
  S_ST( 's',	0,        0,     0 ), /*   423 T_Timingstats     */
  S_ST( 'r',	0,        0,     0 ), /*   424 T_Tinker          */
  S_ST( 's',	0,        0,     0 ), /*   425 T_Tos             */
  S_ST( 'p',	1,        0,     0 ), /*   426 T_Trap            */
  S_ST( 'e',	0,        0,     0 ), /*   427 T_True            */
  S_ST( 'y',	0,        0,     0 ), /*   428 T_Trustedkey      */
  S_ST( 'l',	0,        0,     0 ), /*   429 T_Ttl             */
  S_ST( 'e',	0,        0,     0 ), /*   430 T_Type            */
  S_ST( 'a',	3,      438,     0 ), /*   431 leapsme           */
  S_ST( 'y',	0,        0,     0 ), /*   432 T_UEcrypto        */
  S_ST( 'y',	0,        0,     0 ), /*   433 T_UEcryptonak     */
  S_ST( 'y',	0,        0,     0 ), /*   434 T_UEdigest        */
  S_ST( 'g',	1,        0,     0 ), /*   435 T_Unconfig        */
  S_ST( 'r',	1,      867,     0 ), /*   436 T_Unpeer          */
  S_ST( 'n',	0,        0,     0 ), /*   437 T_Version         */
  S_ST( 'r',	3,      443,     0 ), /*   438 leapsmea          */
  S_ST( 'k',	0,        0,     0 ), /*   439 T_Week            */
  S_ST( 'd',	0,        0,     0 ), /*   440 T_Wildcard        */
  S_ST( 'e',	0,        0,     0 ), /*   441 T_Xleave          */
  S_ST( 'r',	0,        0,     0 ), /*   442 T_Year            */
  S_ST( 'i',	3,      444,     0 ), /*   443 leapsmear         */
  S_ST( 'n',	3,      455,     0 ), /*   444 leapsmeari        */
  S_ST( 'e',	0,        0,     0 ), /*   445 T_Simulate        */
  S_ST( 'y',	0,        0,     0 ), /*   446 T_Beep_Delay      */
  S_ST( 'n',	0,        0,     0 ), /*   447 T_Sim_Duration    */
  S_ST( 't',	0,        0,     0 ), /*   448 T_Server_Offset   */
  S_ST( 'n',	0,        0,     0 ), /*   449 T_Duration        */
  S_ST( 't',	0,        0,     0 ), /*   450 T_Freq_Offset     */
  S_ST( 'r',	0,        0,     0 ), /*   451 T_Wander          */
  S_ST( 'r',	0,        0,     0 ), /*   452 T_Jitter          */
  S_ST( 'y',	0,        0,     0 ), /*   453 T_Prop_Delay      */
  S_ST( 'y',	0,        0,     0 ), /*   454 T_Proc_Delay      */
  S_ST( 't',	3,      456,     0 ), /*   455 leapsmearin       */
  S_ST( 'e',	3,      457,     0 ), /*   456 leapsmearint      */
  S_ST( 'r',	3,      458,     0 ), /*   457 leapsmearinte     */
  S_ST( 'v',	3,      459,     0 ), /*   458 leapsmearinter    */
  S_ST( 'a',	3,      333,     0 ), /*   459 leapsmearinterv   */
  S_ST( 'i',	3,      466,   254 ), /*   460 l                 */
  S_ST( 'm',	3,      462,     0 ), /*   461 li                */
  S_ST( 'i',	3,      463,     0 ), /*   462 lim               */
  S_ST( 't',	3,      464,     0 ), /*   463 limi              */
  S_ST( 'e',	3,      334,     0 ), /*   464 limit             */
  S_ST( 'n',	3,      335,   461 ), /*   465 li                */
  S_ST( 's',	3,      467,   465 ), /*   466 li                */
  S_ST( 't',	3,      468,     0 ), /*   467 lis               */
  S_ST( 'e',	3,      336,     0 ), /*   468 list              */
  S_ST( 'o',	3,      485,   460 ), /*   469 l                 */
  S_ST( 'g',	3,      476,     0 ), /*   470 lo                */
  S_ST( 'c',	3,      472,     0 ), /*   471 log               */
  S_ST( 'o',	3,      473,     0 ), /*   472 logc              */
  S_ST( 'n',	3,      474,     0 ), /*   473 logco             */
  S_ST( 'f',	3,      475,     0 ), /*   474 logcon            */
  S_ST( 'i',	3,      337,     0 ), /*   475 logconf           */
  S_ST( 'f',	3,      477,   471 ), /*   476 log               */
  S_ST( 'i',	3,      478,     0 ), /*   477 logf              */
  S_ST( 'l',	3,      338,     0 ), /*   478 logfi             */
  S_ST( 'o',	3,      480,   470 ), /*   479 lo                */
  S_ST( 'p',	3,      481,     0 ), /*   480 loo               */
  S_ST( 's',	3,      482,     0 ), /*   481 loop              */
  S_ST( 't',	3,      483,     0 ), /*   482 loops             */
  S_ST( 'a',	3,      484,     0 ), /*   483 loopst            */
  S_ST( 't',	3,      339,     0 ), /*   484 loopsta           */
  S_ST( 'w',	3,      486,   479 ), /*   485 lo                */
  S_ST( 'p',	3,      487,     0 ), /*   486 low               */
  S_ST( 'r',	3,      488,     0 ), /*   487 lowp              */
  S_ST( 'i',	3,      489,     0 ), /*   488 lowpr             */
  S_ST( 'o',	3,      490,     0 ), /*   489 lowpri            */
  S_ST( 't',	3,      491,     0 ), /*   490 lowprio           */
  S_ST( 'r',	3,      492,     0 ), /*   491 lowpriot          */
  S_ST( 'a',	3,      340,     0 ), /*   492 lowpriotr         */
  S_ST( 'm',	3,      574,   253 ), /*   493                   */
  S_ST( 'a',	3,      512,     0 ), /*   494 m                 */
  S_ST( 'n',	3,      496,     0 ), /*   495 ma                */
  S_ST( 'y',	3,      497,     0 ), /*   496 man               */
  S_ST( 'c',	3,      498,     0 ), /*   497 many              */
  S_ST( 'a',	3,      499,     0 ), /*   498 manyc             */
  S_ST( 's',	3,      500,     0 ), /*   499 manyca            */
  S_ST( 't',	3,      506,     0 ), /*   500 manycas           */
  S_ST( 'c',	3,      502,     0 ), /*   501 manycast          */
  S_ST( 'l',	3,      503,     0 ), /*   502 manycastc         */
  S_ST( 'i',	3,      504,     0 ), /*   503 manycastcl        */
  S_ST( 'e',	3,      505,     0 ), /*   504 manycastcli       */
  S_ST( 'n',	3,      341,     0 ), /*   505 manycastclie      */
  S_ST( 's',	3,      507,   501 ), /*   506 manycast          */
  S_ST( 'e',	3,      508,     0 ), /*   507 manycasts         */
  S_ST( 'r',	3,      509,     0 ), /*   508 manycastse        */
  S_ST( 'v',	3,      510,     0 ), /*   509 manycastser       */
  S_ST( 'e',	3,      342,     0 ), /*   510 manycastserv      */
  S_ST( 's',	3,      343,   495 ), /*   511 ma                */
  S_ST( 'x',	3,      527,   511 ), /*   512 ma                */
  S_ST( 'a',	3,      514,     0 ), /*   513 max               */
  S_ST( 'g',	3,      344,     0 ), /*   514 maxa              */
  S_ST( 'c',	3,      516,   513 ), /*   515 max               */
  S_ST( 'l',	3,      517,     0 ), /*   516 maxc              */
  S_ST( 'o',	3,      518,     0 ), /*   517 maxcl             */
  S_ST( 'c',	3,      345,     0 ), /*   518 maxclo            */
  S_ST( 'd',	3,      523,   515 ), /*   519 max               */
  S_ST( 'e',	3,      521,     0 ), /*   520 maxd              */
  S_ST( 'p',	3,      522,     0 ), /*   521 maxde             */
  S_ST( 't',	3,      346,     0 ), /*   522 maxdep            */
  S_ST( 'i',	3,      524,   520 ), /*   523 maxd              */
  S_ST( 's',	3,      347,     0 ), /*   524 maxdi             */
  S_ST( 'm',	3,      526,   519 ), /*   525 max               */
  S_ST( 'e',	3,      348,     0 ), /*   526 maxm              */
  S_ST( 'p',	3,      528,   525 ), /*   527 max               */
  S_ST( 'o',	3,      529,     0 ), /*   528 maxp              */
  S_ST( 'l',	3,      349,     0 ), /*   529 maxpo             */
  S_ST( 'd',	3,      531,   494 ), /*   530 m                 */
  S_ST( 'n',	3,      532,     0 ), /*   531 md                */
  S_ST( 's',	3,      533,     0 ), /*   532 mdn               */
  S_ST( 't',	3,      534,     0 ), /*   533 mdns              */
  S_ST( 'r',	3,      535,     0 ), /*   534 mdnst             */
  S_ST( 'i',	3,      536,     0 ), /*   535 mdnstr            */
  S_ST( 'e',	3,      350,     0 ), /*   536 mdnstri           */
  S_ST( 'e',	3,      351,   530 ), /*   537 m                 */
  S_ST( 'l',	3,      539,     0 ), /*   538 mem               */
  S_ST( 'o',	3,      540,     0 ), /*   539 meml              */
  S_ST( 'c',	3,      352,     0 ), /*   540 memlo             */
  S_ST( 'i',	3,      542,   537 ), /*   541 m                 */
  S_ST( 'n',	3,      559,     0 ), /*   542 mi                */
  S_ST( 'c',	3,      544,     0 ), /*   543 min               */
  S_ST( 'l',	3,      545,     0 ), /*   544 minc              */
  S_ST( 'o',	3,      546,     0 ), /*   545 mincl             */
  S_ST( 'c',	3,      353,     0 ), /*   546 minclo            */
  S_ST( 'd',	3,      551,   543 ), /*   547 min               */
  S_ST( 'e',	3,      549,     0 ), /*   548 mind              */
  S_ST( 'p',	3,      550,     0 ), /*   549 minde             */
  S_ST( 't',	3,      354,     0 ), /*   550 mindep            */
  S_ST( 'i',	3,      552,   548 ), /*   551 mind              */
  S_ST( 's',	3,      355,     0 ), /*   552 mindi             */
  S_ST( 'i',	3,      554,   547 ), /*   553 min               */
  S_ST( 'm',	3,      555,     0 ), /*   554 mini              */
  S_ST( 'u',	3,      356,     0 ), /*   555 minim             */
  S_ST( 'p',	3,      557,   553 ), /*   556 min               */
  S_ST( 'o',	3,      558,     0 ), /*   557 minp              */
  S_ST( 'l',	3,      357,     0 ), /*   558 minpo             */
  S_ST( 's',	3,      560,   556 ), /*   559 min               */
  S_ST( 'a',	3,      561,     0 ), /*   560 mins              */
  S_ST( 'n',	3,      358,     0 ), /*   561 minsa             */
  S_ST( 'o',	3,      564,   541 ), /*   562 m                 */
  S_ST( 'd',	3,      359,     0 ), /*   563 mo                */
  S_ST( 'n',	3,      568,   563 ), /*   564 mo                */
  S_ST( 'i',	3,      566,     0 ), /*   565 mon               */
  S_ST( 't',	3,      567,     0 ), /*   566 moni              */
  S_ST( 'o',	3,      361,     0 ), /*   567 monit             */
  S_ST( 't',	3,      362,   565 ), /*   568 mon               */
  S_ST( 'r',	3,      363,   562 ), /*   569 m                 */
  S_ST( 's',	3,      571,   569 ), /*   570 m                 */
  S_ST( 's',	3,      572,     0 ), /*   571 ms                */
  S_ST( 'n',	3,      573,     0 ), /*   572 mss               */
  S_ST( 't',	3,      331,     0 ), /*   573 mssn              */
  S_ST( 'u',	3,      575,   570 ), /*   574 m                 */
  S_ST( 'l',	3,      576,     0 ), /*   575 mu                */
  S_ST( 't',	3,      577,     0 ), /*   576 mul               */
  S_ST( 'i',	3,      578,     0 ), /*   577 mult              */
  S_ST( 'c',	3,      579,     0 ), /*   578 multi             */
  S_ST( 'a',	3,      580,     0 ), /*   579 multic            */
  S_ST( 's',	3,      581,     0 ), /*   580 multica           */
  S_ST( 't',	3,      582,     0 ), /*   581 multicas          */
  S_ST( 'c',	3,      583,     0 ), /*   582 multicast         */
  S_ST( 'l',	3,      584,     0 ), /*   583 multicastc        */
  S_ST( 'i',	3,      585,     0 ), /*   584 multicastcl       */
  S_ST( 'e',	3,      586,     0 ), /*   585 multicastcli      */
  S_ST( 'n',	3,      364,     0 ), /*   586 multicastclie     */
  S_ST( 'n',	3,      630,   493 ), /*   587                   */
  S_ST( 'i',	3,      365,     0 ), /*   588 n                 */
  S_ST( 'o',	3,      625,   588 ), /*   589 n                 */
  S_ST( 'l',	3,      591,     0 ), /*   590 no                */
  S_ST( 'i',	3,      592,     0 ), /*   591 nol               */
  S_ST( 'n',	3,      366,     0 ), /*   592 noli              */
  S_ST( 'm',	3,      598,   590 ), /*   593 no                */
  S_ST( 'o',	3,      595,     0 ), /*   594 nom               */
  S_ST( 'd',	3,      596,     0 ), /*   595 nomo              */
  S_ST( 'i',	3,      597,     0 ), /*   596 nomod             */
  S_ST( 'f',	3,      367,     0 ), /*   597 nomodi            */
  S_ST( 'r',	3,      599,   594 ), /*   598 nom               */
  S_ST( 'u',	3,      600,     0 ), /*   599 nomr              */
  S_ST( 'l',	3,      601,     0 ), /*   600 nomru             */
  S_ST( 'i',	3,      602,     0 ), /*   601 nomrul            */
  S_ST( 's',	3,      368,     0 ), /*   602 nomruli           */
  S_ST( 'n',	3,      604,   593 ), /*   603 no                */
  S_ST( 'v',	3,      605,   369 ), /*   604 non               */
  S_ST( 'o',	3,      606,     0 ), /*   605 nonv              */
  S_ST( 'l',	3,      607,     0 ), /*   606 nonvo             */
  S_ST( 'a',	3,      608,     0 ), /*   607 nonvol            */
  S_ST( 't',	3,      609,     0 ), /*   608 nonvola           */
  S_ST( 'i',	3,      610,     0 ), /*   609 nonvolat          */
  S_ST( 'l',	3,      370,     0 ), /*   610 nonvolati         */
  S_ST( 'p',	3,      612,   603 ), /*   611 no                */
  S_ST( 'e',	3,      613,     0 ), /*   612 nop               */
  S_ST( 'e',	3,      371,     0 ), /*   613 nope              */
  S_ST( 'q',	3,      615,   611 ), /*   614 no                */
  S_ST( 'u',	3,      616,     0 ), /*   615 noq               */
  S_ST( 'e',	3,      617,     0 ), /*   616 noqu              */
  S_ST( 'r',	3,      372,     0 ), /*   617 noque             */
  S_ST( 's',	3,      619,   614 ), /*   618 no                */
  S_ST( 'e',	3,      623,     0 ), /*   619 nos               */
  S_ST( 'l',	3,      621,     0 ), /*   620 nose              */
  S_ST( 'e',	3,      622,     0 ), /*   621 nosel             */
  S_ST( 'c',	3,      373,     0 ), /*   622 nosele            */
  S_ST( 'r',	3,      624,   620 ), /*   623 nose              */
  S_ST( 'v',	3,      374,     0 ), /*   624 noser             */
  S_ST( 't',	3,      626,   618 ), /*   625 no                */
  S_ST( 'r',	3,      628,     0 ), /*   626 not               */
  S_ST( 'a',	3,      375,     0 ), /*   627 notr              */
  S_ST( 'u',	3,      629,   627 ), /*   628 notr              */
  S_ST( 's',	3,      376,     0 ), /*   629 notru             */
  S_ST( 't',	3,      377,   589 ), /*   630 n                 */
  S_ST( 'p',	3,      632,     0 ), /*   631 ntp               */
  S_ST( 'o',	3,      633,     0 ), /*   632 ntpp              */
  S_ST( 'r',	3,      378,     0 ), /*   633 ntppo             */
  S_ST( 's',	3,      635,   631 ), /*   634 ntp               */
  S_ST( 'i',	3,      636,     0 ), /*   635 ntps              */
  S_ST( 'g',	3,      637,     0 ), /*   636 ntpsi             */
  S_ST( 'n',	3,      638,     0 ), /*   637 ntpsig            */
  S_ST( 'd',	3,      639,     0 ), /*   638 ntpsign           */
  S_ST( 's',	3,      640,     0 ), /*   639 ntpsignd          */
  S_ST( 'o',	3,      641,     0 ), /*   640 ntpsignds         */
  S_ST( 'c',	3,      642,     0 ), /*   641 ntpsigndso        */
  S_ST( 'k',	3,      643,     0 ), /*   642 ntpsigndsoc       */
  S_ST( 'e',	3,      379,     0 ), /*   643 ntpsigndsock      */
  S_ST( 'o',	3,      645,   587 ), /*   644                   */
  S_ST( 'r',	3,      646,     0 ), /*   645 o                 */
  S_ST( 'p',	3,      647,     0 ), /*   646 or                */
  S_ST( 'h',	3,      648,     0 ), /*   647 orp               */
  S_ST( 'a',	3,      380,     0 ), /*   648 orph              */
  S_ST( 'w',	3,      650,     0 ), /*   649 orphan            */
  S_ST( 'a',	3,      651,     0 ), /*   650 orphanw           */
  S_ST( 'i',	3,      381,     0 ), /*   651 orphanwa          */
  S_ST( 'p',	3,      394,   644 ), /*   652                   */
  S_ST( 'a',	3,      654,     0 ), /*   653 p                 */
  S_ST( 'n',	3,      655,     0 ), /*   654 pa                */
  S_ST( 'i',	3,      383,     0 ), /*   655 pan               */
  S_ST( 'e',	3,      657,   653 ), /*   656 p                 */
  S_ST( 'e',	3,      384,     0 ), /*   657 pe                */
  S_ST( '_',	3,      659,     0 ), /*   658 peer              */
  S_ST( 'c',	3,      660,     0 ), /*   659 peer_             */
  S_ST( 'l',	3,      661,     0 ), /*   660 peer_c            */
  S_ST( 'e',	3,      662,     0 ), /*   661 peer_cl           */
  S_ST( 'a',	3,      663,     0 ), /*   662 peer_cle          */
  S_ST( 'r',	3,      664,     0 ), /*   663 peer_clea         */
  S_ST( '_',	3,      665,     0 ), /*   664 peer_clear        */
  S_ST( 'd',	3,      666,     0 ), /*   665 peer_clear_       */
  S_ST( 'i',	3,      667,     0 ), /*   666 peer_clear_d      */
  S_ST( 'g',	3,      668,     0 ), /*   667 peer_clear_di     */
  S_ST( 'e',	3,      669,     0 ), /*   668 peer_clear_dig    */
  S_ST( 's',	3,      670,     0 ), /*   669 peer_clear_dige   */
  S_ST( 't',	3,      671,     0 ), /*   670 peer_clear_diges  */
  S_ST( '_',	3,      672,     0 ), /*   671 peer_clear_digest */
  S_ST( 'e',	3,      673,     0 ), /*   672 peer_clear_digest_ */
  S_ST( 'a',	3,      674,     0 ), /*   673 peer_clear_digest_e */
  S_ST( 'r',	3,      675,     0 ), /*   674 peer_clear_digest_ea */
  S_ST( 'l',	3,      382,     0 ), /*   675 peer_clear_digest_ear */
  S_ST( 's',	3,      677,   658 ), /*   676 peer              */
  S_ST( 't',	3,      678,     0 ), /*   677 peers             */
  S_ST( 'a',	3,      679,     0 ), /*   678 peerst            */
  S_ST( 't',	3,      385,     0 ), /*   679 peersta           */
  S_ST( 'h',	3,      681,   656 ), /*   680 p                 */
  S_ST( 'o',	3,      682,     0 ), /*   681 ph                */
  S_ST( 'n',	3,      386,     0 ), /*   682 pho               */
  S_ST( 'i',	3,      387,   680 ), /*   683 p                 */
  S_ST( 'f',	3,      685,     0 ), /*   684 pid               */
  S_ST( 'i',	3,      686,     0 ), /*   685 pidf              */
  S_ST( 'l',	3,      388,     0 ), /*   686 pidfi             */
  S_ST( 'o',	3,      689,   683 ), /*   687 p                 */
  S_ST( 'o',	3,      389,     0 ), /*   688 po                */
  S_ST( 'r',	3,      390,   688 ), /*   689 po                */
  S_ST( 'r',	3,      697,   687 ), /*   690 p                 */
  S_ST( 'e',	3,      695,     0 ), /*   691 pr                */
  S_ST( 'e',	3,      693,     0 ), /*   692 pre               */
  S_ST( 'm',	3,      694,     0 ), /*   693 pree              */
  S_ST( 'p',	3,      391,     0 ), /*   694 preem             */
  S_ST( 'f',	3,      696,   692 ), /*   695 pre               */
  S_ST( 'e',	3,      392,     0 ), /*   696 pref              */
  S_ST( 'o',	3,      710,   691 ), /*   697 pr                */
  S_ST( 'c',	3,      699,     0 ), /*   698 pro               */
  S_ST( '_',	3,      700,     0 ), /*   699 proc              */
  S_ST( 'd',	3,      701,     0 ), /*   700 proc_             */
  S_ST( 'e',	3,      702,     0 ), /*   701 proc_d            */
  S_ST( 'l',	3,      703,     0 ), /*   702 proc_de           */
  S_ST( 'a',	3,      454,     0 ), /*   703 proc_del          */
  S_ST( 'p',	3,      705,   698 ), /*   704 pro               */
  S_ST( '_',	3,      706,     0 ), /*   705 prop              */
  S_ST( 'd',	3,      707,     0 ), /*   706 prop_             */
  S_ST( 'e',	3,      708,     0 ), /*   707 prop_d            */
  S_ST( 'l',	3,      709,     0 ), /*   708 prop_de           */
  S_ST( 'a',	3,      453,     0 ), /*   709 prop_del          */
  S_ST( 't',	3,      711,   704 ), /*   710 pro               */
  S_ST( 'o',	3,      712,     0 ), /*   711 prot              */
  S_ST( 's',	3,      713,     0 ), /*   712 proto             */
  S_ST( 't',	3,      714,     0 ), /*   713 protos            */
  S_ST( 'a',	3,      715,     0 ), /*   714 protost           */
  S_ST( 't',	3,      393,     0 ), /*   715 protosta          */
  S_ST( 'r',	3,      747,   652 ), /*   716                   */
  S_ST( 'a',	3,      723,     0 ), /*   717 r                 */
  S_ST( 'n',	3,      719,     0 ), /*   718 ra                */
  S_ST( 'd',	3,      720,     0 ), /*   719 ran               */
  S_ST( 'f',	3,      721,     0 ), /*   720 rand              */
  S_ST( 'i',	3,      722,     0 ), /*   721 randf             */
  S_ST( 'l',	3,      395,     0 ), /*   722 randfi            */
  S_ST( 'w',	3,      724,   718 ), /*   723 ra                */
  S_ST( 's',	3,      725,     0 ), /*   724 raw               */
  S_ST( 't',	3,      726,     0 ), /*   725 raws              */
  S_ST( 'a',	3,      727,     0 ), /*   726 rawst             */
  S_ST( 't',	3,      396,     0 ), /*   727 rawsta            */
  S_ST( 'e',	3,      744,   717 ), /*   728 r                 */
  S_ST( 'f',	3,      730,     0 ), /*   729 re                */
  S_ST( 'i',	3,      397,     0 ), /*   730 ref               */
  S_ST( 'q',	3,      732,   729 ), /*   731 re                */
  S_ST( 'u',	3,      733,     0 ), /*   732 req               */
  S_ST( 'e',	3,      734,     0 ), /*   733 requ              */
  S_ST( 's',	3,      735,     0 ), /*   734 reque             */
  S_ST( 't',	3,      736,     0 ), /*   735 reques            */
  S_ST( 'k',	3,      737,     0 ), /*   736 request           */
  S_ST( 'e',	3,      398,     0 ), /*   737 requestk          */
  S_ST( 's',	3,      740,   731 ), /*   738 re                */
  S_ST( 'e',	3,      399,     0 ), /*   739 res               */
  S_ST( 't',	3,      741,   739 ), /*   740 res               */
  S_ST( 'r',	3,      742,     0 ), /*   741 rest              */
  S_ST( 'i',	3,      743,     0 ), /*   742 restr             */
  S_ST( 'c',	3,      400,     0 ), /*   743 restri            */
  S_ST( 'v',	3,      745,   738 ), /*   744 re                */
  S_ST( 'o',	3,      746,     0 ), /*   745 rev               */
  S_ST( 'k',	3,      401,     0 ), /*   746 revo              */
  S_ST( 'l',	3,      748,   728 ), /*   747 r                 */
  S_ST( 'i',	3,      749,     0 ), /*   748 rl                */
  S_ST( 'm',	3,      750,     0 ), /*   749 rli               */
  S_ST( 'i',	3,      402,     0 ), /*   750 rlim              */
  S_ST( 's',	3,      824,   716 ), /*   751                   */
  S_ST( 'a',	3,      753,     0 ), /*   752 s                 */
  S_ST( 'v',	3,      754,     0 ), /*   753 sa                */
  S_ST( 'e',	3,      755,     0 ), /*   754 sav               */
  S_ST( 'c',	3,      756,     0 ), /*   755 save              */
  S_ST( 'o',	3,      757,     0 ), /*   756 savec             */
  S_ST( 'n',	3,      758,     0 ), /*   757 saveco            */
  S_ST( 'f',	3,      759,     0 ), /*   758 savecon           */
  S_ST( 'i',	3,      760,     0 ), /*   759 saveconf          */
  S_ST( 'g',	3,      761,     0 ), /*   760 saveconfi         */
  S_ST( 'd',	3,      762,     0 ), /*   761 saveconfig        */
  S_ST( 'i',	3,      403,     0 ), /*   762 saveconfigd       */
  S_ST( 'e',	3,      773,   752 ), /*   763 s                 */
  S_ST( 'r',	3,      765,     0 ), /*   764 se                */
  S_ST( 'v',	3,      766,     0 ), /*   765 ser               */
  S_ST( 'e',	3,      404,     0 ), /*   766 serv              */
  S_ST( '_',	3,      768,     0 ), /*   767 server            */
  S_ST( 'o',	3,      769,     0 ), /*   768 server_           */
  S_ST( 'f',	3,      770,     0 ), /*   769 server_o          */
  S_ST( 'f',	3,      771,     0 ), /*   770 server_of         */
  S_ST( 's',	3,      772,     0 ), /*   771 server_off        */
  S_ST( 'e',	3,      448,     0 ), /*   772 server_offs       */
  S_ST( 't',	3,      774,   764 ), /*   773 se                */
  S_ST( 'v',	3,      775,     0 ), /*   774 set               */
  S_ST( 'a',	3,      405,     0 ), /*   775 setv              */
  S_ST( 'i',	3,      777,   763 ), /*   776 s                 */
  S_ST( 'm',	3,      778,     0 ), /*   777 si                */
  S_ST( 'u',	3,      779,     0 ), /*   778 sim               */
  S_ST( 'l',	3,      780,     0 ), /*   779 simu              */
  S_ST( 'a',	3,      781,     0 ), /*   780 simul             */
  S_ST( 't',	3,      782,     0 ), /*   781 simula            */
  S_ST( 'i',	3,      783,   445 ), /*   782 simulat           */
  S_ST( 'o',	3,      784,     0 ), /*   783 simulati          */
  S_ST( 'n',	3,      785,     0 ), /*   784 simulatio         */
  S_ST( '_',	3,      786,     0 ), /*   785 simulation        */
  S_ST( 'd',	3,      787,     0 ), /*   786 simulation_       */
  S_ST( 'u',	3,      788,     0 ), /*   787 simulation_d      */
  S_ST( 'r',	3,      789,     0 ), /*   788 simulation_du     */
  S_ST( 'a',	3,      790,     0 ), /*   789 simulation_dur    */
  S_ST( 't',	3,      791,     0 ), /*   790 simulation_dura   */
  S_ST( 'i',	3,      792,     0 ), /*   791 simulation_durat  */
  S_ST( 'o',	3,      447,     0 ), /*   792 simulation_durati */
  S_ST( 'o',	3,      794,   776 ), /*   793 s                 */
  S_ST( 'u',	3,      795,     0 ), /*   794 so                */
  S_ST( 'r',	3,      796,     0 ), /*   795 sou               */
  S_ST( 'c',	3,      406,     0 ), /*   796 sour              */
  S_ST( 't',	3,      820,   793 ), /*   797 s                 */
  S_ST( 'a',	3,      804,     0 ), /*   798 st                */
  S_ST( 'c',	3,      800,     0 ), /*   799 sta               */
  S_ST( 'k',	3,      801,     0 ), /*   800 stac              */
  S_ST( 's',	3,      802,     0 ), /*   801 stack             */
  S_ST( 'i',	3,      803,     0 ), /*   802 stacks            */
  S_ST( 'z',	3,      407,     0 ), /*   803 stacksi           */
  S_ST( 't',	3,      409,   799 ), /*   804 sta               */
  S_ST( 'i',	3,      806,     0 ), /*   805 stat              */
  S_ST( 's',	3,      807,     0 ), /*   806 stati             */
  S_ST( 't',	3,      808,     0 ), /*   807 statis            */
  S_ST( 'i',	3,      809,     0 ), /*   808 statist           */
  S_ST( 'c',	3,      408,     0 ), /*   809 statisti          */
  S_ST( 'd',	3,      811,     0 ), /*   810 stats             */
  S_ST( 'i',	3,      410,     0 ), /*   811 statsd            */
  S_ST( 'e',	3,      411,   798 ), /*   812 st                */
  S_ST( 'b',	3,      814,     0 ), /*   813 step              */
  S_ST( 'a',	3,      815,     0 ), /*   814 stepb             */
  S_ST( 'c',	3,      412,     0 ), /*   815 stepba            */
  S_ST( 'f',	3,      817,   813 ), /*   816 step              */
  S_ST( 'w',	3,      413,     0 ), /*   817 stepf             */
  S_ST( 'o',	3,      819,   816 ), /*   818 step              */
  S_ST( 'u',	3,      414,     0 ), /*   819 stepo             */
  S_ST( 'r',	3,      821,   812 ), /*   820 st                */
  S_ST( 'a',	3,      822,     0 ), /*   821 str               */
  S_ST( 't',	3,      823,     0 ), /*   822 stra              */
  S_ST( 'u',	3,      415,     0 ), /*   823 strat             */
  S_ST( 'y',	3,      417,   797 ), /*   824 s                 */
  S_ST( 's',	3,      826,     0 ), /*   825 sys               */
  S_ST( 't',	3,      827,     0 ), /*   826 syss              */
  S_ST( 'a',	3,      828,     0 ), /*   827 sysst             */
  S_ST( 't',	3,      418,     0 ), /*   828 syssta            */
  S_ST( 't',	3,      855,   751 ), /*   829                   */
  S_ST( 'i',	3,      841,     0 ), /*   830 t                 */
  S_ST( 'c',	3,      419,     0 ), /*   831 ti                */
  S_ST( 'm',	3,      834,   831 ), /*   832 ti                */
  S_ST( 'e',	3,      422,     0 ), /*   833 tim               */
  S_ST( 'i',	3,      835,   833 ), /*   834 tim               */
  S_ST( 'n',	3,      836,     0 ), /*   835 timi              */
  S_ST( 'g',	3,      837,     0 ), /*   836 timin             */
  S_ST( 's',	3,      838,     0 ), /*   837 timing            */
  S_ST( 't',	3,      839,     0 ), /*   838 timings           */
  S_ST( 'a',	3,      840,     0 ), /*   839 timingst          */
  S_ST( 't',	3,      423,     0 ), /*   840 timingsta         */
  S_ST( 'n',	3,      842,   832 ), /*   841 ti                */
  S_ST( 'k',	3,      843,     0 ), /*   842 tin               */
  S_ST( 'e',	3,      424,     0 ), /*   843 tink              */
  S_ST( 'o',	3,      425,   830 ), /*   844 t                 */
  S_ST( 'r',	3,      847,   844 ), /*   845 t                 */
  S_ST( 'a',	3,      426,     0 ), /*   846 tr                */
  S_ST( 'u',	3,      848,   846 ), /*   847 tr                */
  S_ST( 's',	3,      849,   427 ), /*   848 tru               */
  S_ST( 't',	3,      850,     0 ), /*   849 trus              */
  S_ST( 'e',	3,      851,     0 ), /*   850 trust             */
  S_ST( 'd',	3,      852,     0 ), /*   851 truste            */
  S_ST( 'k',	3,      853,     0 ), /*   852 trusted           */
  S_ST( 'e',	3,      428,     0 ), /*   853 trustedk          */
  S_ST( 't',	3,      429,   845 ), /*   854 t                 */
  S_ST( 'y',	3,      856,   854 ), /*   855 t                 */
  S_ST( 'p',	3,      430,     0 ), /*   856 ty                */
  S_ST( 'u',	3,      858,   829 ), /*   857                   */
  S_ST( 'n',	3,      864,     0 ), /*   858 u                 */
  S_ST( 'c',	3,      860,     0 ), /*   859 un                */
  S_ST( 'o',	3,      861,     0 ), /*   860 unc               */
  S_ST( 'n',	3,      862,     0 ), /*   861 unco              */
  S_ST( 'f',	3,      863,     0 ), /*   862 uncon             */
  S_ST( 'i',	3,      435,     0 ), /*   863 unconf            */
  S_ST( 'p',	3,      865,   859 ), /*   864 un                */
  S_ST( 'e',	3,      866,     0 ), /*   865 unp               */
  S_ST( 'e',	3,      436,     0 ), /*   866 unpe              */
  S_ST( '_',	3,      887,     0 ), /*   867 unpeer            */
  S_ST( 'c',	3,      869,     0 ), /*   868 unpeer_           */
  S_ST( 'r',	3,      870,     0 ), /*   869 unpeer_c          */
  S_ST( 'y',	3,      871,     0 ), /*   870 unpeer_cr         */
  S_ST( 'p',	3,      872,     0 ), /*   871 unpeer_cry        */
  S_ST( 't',	3,      873,     0 ), /*   872 unpeer_cryp       */
  S_ST( 'o',	3,      874,     0 ), /*   873 unpeer_crypt      */
  S_ST( '_',	3,      879,     0 ), /*   874 unpeer_crypto     */
  S_ST( 'e',	3,      876,     0 ), /*   875 unpeer_crypto_    */
  S_ST( 'a',	3,      877,     0 ), /*   876 unpeer_crypto_e   */
  S_ST( 'r',	3,      878,     0 ), /*   877 unpeer_crypto_ea  */
  S_ST( 'l',	3,      432,     0 ), /*   878 unpeer_crypto_ear */
  S_ST( 'n',	3,      880,   875 ), /*   879 unpeer_crypto_    */
  S_ST( 'a',	3,      881,     0 ), /*   880 unpeer_crypto_n   */
  S_ST( 'k',	3,      882,     0 ), /*   881 unpeer_crypto_na  */
  S_ST( '_',	3,      883,     0 ), /*   882 unpeer_crypto_nak */
  S_ST( 'e',	3,      884,     0 ), /*   883 unpeer_crypto_nak_ */
  S_ST( 'a',	3,      885,     0 ), /*   884 unpeer_crypto_nak_e */
  S_ST( 'r',	3,      886,     0 ), /*   885 unpeer_crypto_nak_ea */
  S_ST( 'l',	3,      433,     0 ), /*   886 unpeer_crypto_nak_ear */
  S_ST( 'd',	3,      888,   868 ), /*   887 unpeer_           */
  S_ST( 'i',	3,      889,     0 ), /*   888 unpeer_d          */
  S_ST( 'g',	3,      890,     0 ), /*   889 unpeer_di         */
  S_ST( 'e',	3,      891,     0 ), /*   890 unpeer_dig        */
  S_ST( 's',	3,      892,     0 ), /*   891 unpeer_dige       */
  S_ST( 't',	3,      893,     0 ), /*   892 unpeer_diges      */
  S_ST( '_',	3,      894,     0 ), /*   893 unpeer_digest     */
  S_ST( 'e',	3,      895,     0 ), /*   894 unpeer_digest_    */
  S_ST( 'a',	3,      896,     0 ), /*   895 unpeer_digest_e   */
  S_ST( 'r',	3,      897,     0 ), /*   896 unpeer_digest_ea  */
  S_ST( 'l',	3,      434,     0 ), /*   897 unpeer_digest_ear */
  S_ST( 'v',	3,      899,   857 ), /*   898                   */
  S_ST( 'e',	3,      900,     0 ), /*   899 v                 */
  S_ST( 'r',	3,      901,     0 ), /*   900 ve                */
  S_ST( 's',	3,      902,     0 ), /*   901 ver               */
  S_ST( 'i',	3,      903,     0 ), /*   902 vers              */
  S_ST( 'o',	3,      437,     0 ), /*   903 versi             */
  S_ST( 'w',	3,      911,   898 ), /*   904                   */
  S_ST( 'a',	3,      906,     0 ), /*   905 w                 */
  S_ST( 'n',	3,      907,     0 ), /*   906 wa                */
  S_ST( 'd',	3,      908,     0 ), /*   907 wan               */
  S_ST( 'e',	3,      451,     0 ), /*   908 wand              */
  S_ST( 'e',	3,      910,   905 ), /*   909 w                 */
  S_ST( 'e',	3,      439,     0 ), /*   910 we                */
  S_ST( 'i',	3,      912,   909 ), /*   911 w                 */
  S_ST( 'l',	3,      913,     0 ), /*   912 wi                */
  S_ST( 'd',	3,      914,     0 ), /*   913 wil               */
  S_ST( 'c',	3,      915,     0 ), /*   914 wild              */
  S_ST( 'a',	3,      916,     0 ), /*   915 wildc             */
  S_ST( 'r',	3,      440,     0 ), /*   916 wildca            */
  S_ST( 'x',	3,      918,   904 ), /*   917                   */
  S_ST( 'l',	3,      919,     0 ), /*   918 x                 */
  S_ST( 'e',	3,      920,     0 ), /*   919 xl                */
  S_ST( 'a',	3,      921,     0 ), /*   920 xle               */
  S_ST( 'v',	3,      441,     0 ), /*   921 xlea              */
  S_ST( 'y',	3,      923,   917 ), /*   922 [initial state]   */
  S_ST( 'e',	3,      924,     0 ), /*   923 y                 */
  S_ST( 'a',	3,      442,     0 )  /*   924 ye                */
};

