/*
 * ntp_keyword.h
 * 
 * NOTE: edit this file with caution, it is generated by keyword-gen.c
 *	 Generated 2018-01-05 08:53:56 UTC	  diff_ignore_line
 *
 */
#include "ntp_scanner.h"
#include "ntp_parser.h"

#define LOWEST_KEYWORD_ID 258

const char * const keyword_text[199] = {
	/* 0       258             T_Abbrev */	"abbrev",
	/* 1       259                T_Age */	"age",
	/* 2       260                T_All */	"all",
	/* 3       261              T_Allan */	"allan",
	/* 4       262           T_Allpeers */	"allpeers",
	/* 5       263               T_Auth */	"auth",
	/* 6       264            T_Autokey */	"autokey",
	/* 7       265            T_Automax */	"automax",
	/* 8       266            T_Average */	"average",
	/* 9       267           T_Basedate */	"basedate",
	/* 10      268            T_Bclient */	"bclient",
	/* 11      269        T_Bcpollbstep */	"bcpollbstep",
	/* 12      270             T_Beacon */	"beacon",
	/* 13      271          T_Broadcast */	"broadcast",
	/* 14      272    T_Broadcastclient */	"broadcastclient",
	/* 15      273     T_Broadcastdelay */	"broadcastdelay",
	/* 16      274              T_Burst */	"burst",
	/* 17      275          T_Calibrate */	"calibrate",
	/* 18      276            T_Ceiling */	"ceiling",
	/* 19      277         T_Clockstats */	"clockstats",
	/* 20      278             T_Cohort */	"cohort",
	/* 21      279         T_ControlKey */	"controlkey",
	/* 22      280             T_Crypto */	"crypto",
	/* 23      281        T_Cryptostats */	"cryptostats",
	/* 24      282                T_Ctl */	"ctl",
	/* 25      283                T_Day */	"day",
	/* 26      284            T_Default */	"default",
	/* 27      285             T_Digest */	"digest",
	/* 28      286            T_Disable */	"disable",
	/* 29      287            T_Discard */	"discard",
	/* 30      288         T_Dispersion */	"dispersion",
	/* 31      289             T_Double */	NULL,
	/* 32      290          T_Driftfile */	"driftfile",
	/* 33      291               T_Drop */	"drop",
	/* 34      292               T_Dscp */	"dscp",
	/* 35      293           T_Ellipsis */	"...",
	/* 36      294             T_Enable */	"enable",
	/* 37      295                T_End */	"end",
	/* 38      296              T_Epeer */	"epeer",
	/* 39      297              T_False */	NULL,
	/* 40      298               T_File */	"file",
	/* 41      299            T_Filegen */	"filegen",
	/* 42      300            T_Filenum */	"filenum",
	/* 43      301              T_Flag1 */	"flag1",
	/* 44      302              T_Flag2 */	"flag2",
	/* 45      303              T_Flag3 */	"flag3",
	/* 46      304              T_Flag4 */	"flag4",
	/* 47      305              T_Flake */	"flake",
	/* 48      306              T_Floor */	"floor",
	/* 49      307               T_Freq */	"freq",
	/* 50      308              T_Fudge */	"fudge",
	/* 51      309               T_Host */	"host",
	/* 52      310           T_Huffpuff */	"huffpuff",
	/* 53      311             T_Iburst */	"iburst",
	/* 54      312              T_Ident */	"ident",
	/* 55      313             T_Ignore */	"ignore",
	/* 56      314           T_Incalloc */	"incalloc",
	/* 57      315             T_Incmem */	"incmem",
	/* 58      316          T_Initalloc */	"initalloc",
	/* 59      317            T_Initmem */	"initmem",
	/* 60      318        T_Includefile */	"includefile",
	/* 61      319            T_Integer */	NULL,
	/* 62      320          T_Interface */	"interface",
	/* 63      321           T_Intrange */	NULL,
	/* 64      322                 T_Io */	"io",
	/* 65      323               T_Ipv4 */	"ipv4",
	/* 66      324          T_Ipv4_flag */	"-4",
	/* 67      325               T_Ipv6 */	"ipv6",
	/* 68      326          T_Ipv6_flag */	"-6",
	/* 69      327             T_Kernel */	"kernel",
	/* 70      328                T_Key */	"key",
	/* 71      329               T_Keys */	"keys",
	/* 72      330            T_Keysdir */	"keysdir",
	/* 73      331                T_Kod */	"kod",
	/* 74      332             T_Mssntp */	"mssntp",
	/* 75      333           T_Leapfile */	"leapfile",
	/* 76      334  T_Leapsmearinterval */	"leapsmearinterval",
	/* 77      335            T_Limited */	"limited",
	/* 78      336               T_Link */	"link",
	/* 79      337             T_Listen */	"listen",
	/* 80      338          T_Logconfig */	"logconfig",
	/* 81      339            T_Logfile */	"logfile",
	/* 82      340          T_Loopstats */	"loopstats",
	/* 83      341        T_Lowpriotrap */	"lowpriotrap",
	/* 84      342     T_Manycastclient */	"manycastclient",
	/* 85      343     T_Manycastserver */	"manycastserver",
	/* 86      344               T_Mask */	"mask",
	/* 87      345             T_Maxage */	"maxage",
	/* 88      346           T_Maxclock */	"maxclock",
	/* 89      347           T_Maxdepth */	"maxdepth",
	/* 90      348            T_Maxdist */	"maxdist",
	/* 91      349             T_Maxmem */	"maxmem",
	/* 92      350            T_Maxpoll */	"maxpoll",
	/* 93      351          T_Mdnstries */	"mdnstries",
	/* 94      352                T_Mem */	"mem",
	/* 95      353            T_Memlock */	"memlock",
	/* 96      354           T_Minclock */	"minclock",
	/* 97      355           T_Mindepth */	"mindepth",
	/* 98      356            T_Mindist */	"mindist",
	/* 99      357            T_Minimum */	"minimum",
	/* 100     358            T_Minpoll */	"minpoll",
	/* 101     359            T_Minsane */	"minsane",
	/* 102     360               T_Mode */	"mode",
	/* 103     361              T_Mode7 */	"mode7",
	/* 104     362            T_Monitor */	"monitor",
	/* 105     363              T_Month */	"month",
	/* 106     364                T_Mru */	"mru",
	/* 107     365    T_Multicastclient */	"multicastclient",
	/* 108     366                T_Nic */	"nic",
	/* 109     367             T_Nolink */	"nolink",
	/* 110     368           T_Nomodify */	"nomodify",
	/* 111     369          T_Nomrulist */	"nomrulist",
	/* 112     370               T_None */	"none",
	/* 113     371        T_Nonvolatile */	"nonvolatile",
	/* 114     372            T_Noepeer */	"noepeer",
	/* 115     373             T_Nopeer */	"nopeer",
	/* 116     374            T_Noquery */	"noquery",
	/* 117     375           T_Noselect */	"noselect",
	/* 118     376            T_Noserve */	"noserve",
	/* 119     377             T_Notrap */	"notrap",
	/* 120     378            T_Notrust */	"notrust",
	/* 121     379                T_Ntp */	"ntp",
	/* 122     380            T_Ntpport */	"ntpport",
	/* 123     381     T_NtpSignDsocket */	"ntpsigndsocket",
	/* 124     382             T_Orphan */	"orphan",
	/* 125     383         T_Orphanwait */	"orphanwait",
	/* 126     384          T_PCEdigest */	"peer_clear_digest_early",
	/* 127     385              T_Panic */	"panic",
	/* 128     386               T_Peer */	"peer",
	/* 129     387          T_Peerstats */	"peerstats",
	/* 130     388              T_Phone */	"phone",
	/* 131     389                T_Pid */	"pid",
	/* 132     390            T_Pidfile */	"pidfile",
	/* 133     391               T_Pool */	"pool",
	/* 134     392               T_Port */	"port",
	/* 135     393            T_Preempt */	"preempt",
	/* 136     394             T_Prefer */	"prefer",
	/* 137     395         T_Protostats */	"protostats",
	/* 138     396                 T_Pw */	"pw",
	/* 139     397           T_Randfile */	"randfile",
	/* 140     398           T_Rawstats */	"rawstats",
	/* 141     399              T_Refid */	"refid",
	/* 142     400         T_Requestkey */	"requestkey",
	/* 143     401              T_Reset */	"reset",
	/* 144     402           T_Restrict */	"restrict",
	/* 145     403             T_Revoke */	"revoke",
	/* 146     404             T_Rlimit */	"rlimit",
	/* 147     405      T_Saveconfigdir */	"saveconfigdir",
	/* 148     406             T_Server */	"server",
	/* 149     407             T_Setvar */	"setvar",
	/* 150     408             T_Source */	"source",
	/* 151     409          T_Stacksize */	"stacksize",
	/* 152     410         T_Statistics */	"statistics",
	/* 153     411              T_Stats */	"stats",
	/* 154     412           T_Statsdir */	"statsdir",
	/* 155     413               T_Step */	"step",
	/* 156     414           T_Stepback */	"stepback",
	/* 157     415            T_Stepfwd */	"stepfwd",
	/* 158     416            T_Stepout */	"stepout",
	/* 159     417            T_Stratum */	"stratum",
	/* 160     418             T_String */	NULL,
	/* 161     419                T_Sys */	"sys",
	/* 162     420           T_Sysstats */	"sysstats",
	/* 163     421               T_Tick */	"tick",
	/* 164     422              T_Time1 */	"time1",
	/* 165     423              T_Time2 */	"time2",
	/* 166     424              T_Timer */	"timer",
	/* 167     425        T_Timingstats */	"timingstats",
	/* 168     426             T_Tinker */	"tinker",
	/* 169     427                T_Tos */	"tos",
	/* 170     428               T_Trap */	"trap",
	/* 171     429               T_True */	"true",
	/* 172     430         T_Trustedkey */	"trustedkey",
	/* 173     431                T_Ttl */	"ttl",
	/* 174     432               T_Type */	"type",
	/* 175     433              T_U_int */	NULL,
	/* 176     434           T_UEcrypto */	"unpeer_crypto_early",
	/* 177     435        T_UEcryptonak */	"unpeer_crypto_nak_early",
	/* 178     436           T_UEdigest */	"unpeer_digest_early",
	/* 179     437           T_Unconfig */	"unconfig",
	/* 180     438             T_Unpeer */	"unpeer",
	/* 181     439            T_Version */	"version",
	/* 182     440    T_WanderThreshold */	NULL,
	/* 183     441               T_Week */	"week",
	/* 184     442           T_Wildcard */	"wildcard",
	/* 185     443             T_Xleave */	"xleave",
	/* 186     444               T_Year */	"year",
	/* 187     445               T_Flag */	NULL,
	/* 188     446                T_EOC */	NULL,
	/* 189     447           T_Simulate */	"simulate",
	/* 190     448         T_Beep_Delay */	"beep_delay",
	/* 191     449       T_Sim_Duration */	"simulation_duration",
	/* 192     450      T_Server_Offset */	"server_offset",
	/* 193     451           T_Duration */	"duration",
	/* 194     452        T_Freq_Offset */	"freq_offset",
	/* 195     453             T_Wander */	"wander",
	/* 196     454             T_Jitter */	"jitter",
	/* 197     455         T_Prop_Delay */	"prop_delay",
	/* 198     456         T_Proc_Delay */	"proc_delay"
};

#define SCANNER_INIT_S 931

const scan_state sst[934] = {
/*SS_T( ch,	f-by, match, other ),				 */
  0,				      /*     0                   */
  S_ST( '-',	3,      326,     0 ), /*     1                   */
  S_ST( '.',	3,        3,     1 ), /*     2                   */
  S_ST( '.',	3,      293,     0 ), /*     3 .                 */
  S_ST( 'a',	3,       23,     2 ), /*     4                   */
  S_ST( 'b',	3,        6,     0 ), /*     5 a                 */
  S_ST( 'b',	3,        7,     0 ), /*     6 ab                */
  S_ST( 'r',	3,        8,     0 ), /*     7 abb               */
  S_ST( 'e',	3,      258,     0 ), /*     8 abbr              */
  S_ST( 'g',	3,      259,     5 ), /*     9 a                 */
  S_ST( 'l',	3,      260,     9 ), /*    10 a                 */
  S_ST( 'a',	3,      261,     0 ), /*    11 all               */
  S_ST( 'p',	3,       13,    11 ), /*    12 all               */
  S_ST( 'e',	3,       14,     0 ), /*    13 allp              */
  S_ST( 'e',	3,       15,     0 ), /*    14 allpe             */
  S_ST( 'r',	3,      262,     0 ), /*    15 allpee            */
  S_ST( 'u',	3,       17,    10 ), /*    16 a                 */
  S_ST( 't',	3,       18,     0 ), /*    17 au                */
  S_ST( 'o',	3,       21,   263 ), /*    18 aut               */
  S_ST( 'k',	3,       20,     0 ), /*    19 auto              */
  S_ST( 'e',	3,      264,     0 ), /*    20 autok             */
  S_ST( 'm',	3,       22,    19 ), /*    21 auto              */
  S_ST( 'a',	3,      265,     0 ), /*    22 autom             */
  S_ST( 'v',	3,       24,    16 ), /*    23 a                 */
  S_ST( 'e',	3,       25,     0 ), /*    24 av                */
  S_ST( 'r',	3,       26,     0 ), /*    25 ave               */
  S_ST( 'a',	3,       27,     0 ), /*    26 aver              */
  S_ST( 'g',	3,      266,     0 ), /*    27 avera             */
  S_ST( 'b',	3,       75,     4 ), /*    28                   */
  S_ST( 'a',	3,       30,     0 ), /*    29 b                 */
  S_ST( 's',	3,       31,     0 ), /*    30 ba                */
  S_ST( 'e',	3,       32,     0 ), /*    31 bas               */
  S_ST( 'd',	3,       33,     0 ), /*    32 base              */
  S_ST( 'a',	3,       34,     0 ), /*    33 based             */
  S_ST( 't',	3,      267,     0 ), /*    34 baseda            */
  S_ST( 'c',	3,       40,    29 ), /*    35 b                 */
  S_ST( 'l',	3,       37,     0 ), /*    36 bc                */
  S_ST( 'i',	3,       38,     0 ), /*    37 bcl               */
  S_ST( 'e',	3,       39,     0 ), /*    38 bcli              */
  S_ST( 'n',	3,      268,     0 ), /*    39 bclie             */
  S_ST( 'p',	3,       41,    36 ), /*    40 bc                */
  S_ST( 'o',	3,       42,     0 ), /*    41 bcp               */
  S_ST( 'l',	3,       43,     0 ), /*    42 bcpo              */
  S_ST( 'l',	3,       44,     0 ), /*    43 bcpol             */
  S_ST( 'b',	3,       45,     0 ), /*    44 bcpoll            */
  S_ST( 's',	3,       46,     0 ), /*    45 bcpollb           */
  S_ST( 't',	3,       47,     0 ), /*    46 bcpollbs          */
  S_ST( 'e',	3,      269,     0 ), /*    47 bcpollbst         */
  S_ST( 'e',	3,       52,    35 ), /*    48 b                 */
  S_ST( 'a',	3,       50,     0 ), /*    49 be                */
  S_ST( 'c',	3,       51,     0 ), /*    50 bea               */
  S_ST( 'o',	3,      270,     0 ), /*    51 beac              */
  S_ST( 'e',	3,       53,    49 ), /*    52 be                */
  S_ST( 'p',	3,       54,     0 ), /*    53 bee               */
  S_ST( '_',	3,       55,     0 ), /*    54 beep              */
  S_ST( 'd',	3,       56,     0 ), /*    55 beep_             */
  S_ST( 'e',	3,       57,     0 ), /*    56 beep_d            */
  S_ST( 'l',	3,       58,     0 ), /*    57 beep_de           */
  S_ST( 'a',	3,      448,     0 ), /*    58 beep_del          */
  S_ST( 'r',	3,       60,    48 ), /*    59 b                 */
  S_ST( 'o',	3,       61,     0 ), /*    60 br                */
  S_ST( 'a',	3,       62,     0 ), /*    61 bro               */
  S_ST( 'd',	3,       63,     0 ), /*    62 broa              */
  S_ST( 'c',	3,       64,     0 ), /*    63 broad             */
  S_ST( 'a',	3,       65,     0 ), /*    64 broadc            */
  S_ST( 's',	3,      271,     0 ), /*    65 broadca           */
  S_ST( 'c',	3,       67,     0 ), /*    66 broadcast         */
  S_ST( 'l',	3,       68,     0 ), /*    67 broadcastc        */
  S_ST( 'i',	3,       69,     0 ), /*    68 broadcastcl       */
  S_ST( 'e',	3,       70,     0 ), /*    69 broadcastcli      */
  S_ST( 'n',	3,      272,     0 ), /*    70 broadcastclie     */
  S_ST( 'd',	3,       72,    66 ), /*    71 broadcast         */
  S_ST( 'e',	3,       73,     0 ), /*    72 broadcastd        */
  S_ST( 'l',	3,       74,     0 ), /*    73 broadcastde       */
  S_ST( 'a',	3,      273,     0 ), /*    74 broadcastdel      */
  S_ST( 'u',	3,       76,    59 ), /*    75 b                 */
  S_ST( 'r',	3,       77,     0 ), /*    76 bu                */
  S_ST( 's',	3,      274,     0 ), /*    77 bur               */
  S_ST( 'c',	3,      118,    28 ), /*    78                   */
  S_ST( 'a',	3,       80,     0 ), /*    79 c                 */
  S_ST( 'l',	3,       81,     0 ), /*    80 ca                */
  S_ST( 'i',	3,       82,     0 ), /*    81 cal               */
  S_ST( 'b',	3,       83,     0 ), /*    82 cali              */
  S_ST( 'r',	3,       84,     0 ), /*    83 calib             */
  S_ST( 'a',	3,       85,     0 ), /*    84 calibr            */
  S_ST( 't',	3,      275,     0 ), /*    85 calibra           */
  S_ST( 'e',	3,       87,    79 ), /*    86 c                 */
  S_ST( 'i',	3,       88,     0 ), /*    87 ce                */
  S_ST( 'l',	3,       89,     0 ), /*    88 cei               */
  S_ST( 'i',	3,       90,     0 ), /*    89 ceil              */
  S_ST( 'n',	3,      276,     0 ), /*    90 ceili             */
  S_ST( 'l',	3,       92,    86 ), /*    91 c                 */
  S_ST( 'o',	3,       93,     0 ), /*    92 cl                */
  S_ST( 'c',	3,       94,     0 ), /*    93 clo               */
  S_ST( 'k',	3,       95,     0 ), /*    94 cloc              */
  S_ST( 's',	3,       96,     0 ), /*    95 clock             */
  S_ST( 't',	3,       97,     0 ), /*    96 clocks            */
  S_ST( 'a',	3,       98,     0 ), /*    97 clockst           */
  S_ST( 't',	3,      277,     0 ), /*    98 clocksta          */
  S_ST( 'o',	3,      103,    91 ), /*    99 c                 */
  S_ST( 'h',	3,      101,     0 ), /*   100 co                */
  S_ST( 'o',	3,      102,     0 ), /*   101 coh               */
  S_ST( 'r',	3,      278,     0 ), /*   102 coho              */
  S_ST( 'n',	3,      104,   100 ), /*   103 co                */
  S_ST( 't',	3,      105,     0 ), /*   104 con               */
  S_ST( 'r',	3,      106,     0 ), /*   105 cont              */
  S_ST( 'o',	3,      107,     0 ), /*   106 contr             */
  S_ST( 'l',	3,      108,     0 ), /*   107 contro            */
  S_ST( 'k',	3,      109,     0 ), /*   108 control           */
  S_ST( 'e',	3,      279,     0 ), /*   109 controlk          */
  S_ST( 'r',	3,      111,    99 ), /*   110 c                 */
  S_ST( 'y',	3,      112,     0 ), /*   111 cr                */
  S_ST( 'p',	3,      113,     0 ), /*   112 cry               */
  S_ST( 't',	3,      280,     0 ), /*   113 cryp              */
  S_ST( 's',	3,      115,     0 ), /*   114 crypto            */
  S_ST( 't',	3,      116,     0 ), /*   115 cryptos           */
  S_ST( 'a',	3,      117,     0 ), /*   116 cryptost          */
  S_ST( 't',	3,      281,     0 ), /*   117 cryptosta         */
  S_ST( 't',	3,      282,   110 ), /*   118 c                 */
  S_ST( 'd',	3,      153,    78 ), /*   119                   */
  S_ST( 'a',	3,      283,     0 ), /*   120 d                 */
  S_ST( 'e',	3,      122,   120 ), /*   121 d                 */
  S_ST( 'f',	3,      123,     0 ), /*   122 de                */
  S_ST( 'a',	3,      124,     0 ), /*   123 def               */
  S_ST( 'u',	3,      125,     0 ), /*   124 defa              */
  S_ST( 'l',	3,      284,     0 ), /*   125 defau             */
  S_ST( 'i',	3,      130,   121 ), /*   126 d                 */
  S_ST( 'g',	3,      128,     0 ), /*   127 di                */
  S_ST( 'e',	3,      129,     0 ), /*   128 dig               */
  S_ST( 's',	3,      285,     0 ), /*   129 dige              */
  S_ST( 's',	3,      137,   127 ), /*   130 di                */
  S_ST( 'a',	3,      132,     0 ), /*   131 dis               */
  S_ST( 'b',	3,      133,     0 ), /*   132 disa              */
  S_ST( 'l',	3,      286,     0 ), /*   133 disab             */
  S_ST( 'c',	3,      135,   131 ), /*   134 dis               */
  S_ST( 'a',	3,      136,     0 ), /*   135 disc              */
  S_ST( 'r',	3,      287,     0 ), /*   136 disca             */
  S_ST( 'p',	3,      138,   134 ), /*   137 dis               */
  S_ST( 'e',	3,      139,     0 ), /*   138 disp              */
  S_ST( 'r',	3,      140,     0 ), /*   139 dispe             */
  S_ST( 's',	3,      141,     0 ), /*   140 disper            */
  S_ST( 'i',	3,      142,     0 ), /*   141 dispers           */
  S_ST( 'o',	3,      288,     0 ), /*   142 dispersi          */
  S_ST( 'r',	3,      150,   126 ), /*   143 d                 */
  S_ST( 'i',	3,      145,     0 ), /*   144 dr                */
  S_ST( 'f',	3,      146,     0 ), /*   145 dri               */
  S_ST( 't',	3,      147,     0 ), /*   146 drif              */
  S_ST( 'f',	3,      148,     0 ), /*   147 drift             */
  S_ST( 'i',	3,      149,     0 ), /*   148 driftf            */
  S_ST( 'l',	3,      290,     0 ), /*   149 driftfi           */
  S_ST( 'o',	3,      291,   144 ), /*   150 dr                */
  S_ST( 's',	3,      152,   143 ), /*   151 d                 */
  S_ST( 'c',	3,      292,     0 ), /*   152 ds                */
  S_ST( 'u',	3,      154,   151 ), /*   153 d                 */
  S_ST( 'r',	3,      155,     0 ), /*   154 du                */
  S_ST( 'a',	3,      156,     0 ), /*   155 dur               */
  S_ST( 't',	3,      157,     0 ), /*   156 dura              */
  S_ST( 'i',	3,      158,     0 ), /*   157 durat             */
  S_ST( 'o',	3,      451,     0 ), /*   158 durati            */
  S_ST( 'e',	3,      164,   119 ), /*   159                   */
  S_ST( 'n',	3,      295,     0 ), /*   160 e                 */
  S_ST( 'a',	3,      162,     0 ), /*   161 en                */
  S_ST( 'b',	3,      163,     0 ), /*   162 ena               */
  S_ST( 'l',	3,      294,     0 ), /*   163 enab              */
  S_ST( 'p',	3,      165,   160 ), /*   164 e                 */
  S_ST( 'e',	3,      166,     0 ), /*   165 ep                */
  S_ST( 'e',	3,      296,     0 ), /*   166 epe               */
  S_ST( 'f',	3,      188,   159 ), /*   167                   */
  S_ST( 'i',	3,      169,     0 ), /*   168 f                 */
  S_ST( 'l',	3,      298,     0 ), /*   169 fi                */
  S_ST( 'g',	3,      171,     0 ), /*   170 file              */
  S_ST( 'e',	3,      299,     0 ), /*   171 fileg             */
  S_ST( 'n',	3,      173,   170 ), /*   172 file              */
  S_ST( 'u',	3,      300,     0 ), /*   173 filen             */
  S_ST( 'l',	3,      178,   168 ), /*   174 f                 */
  S_ST( 'a',	3,      177,     0 ), /*   175 fl                */
  S_ST( 'g',	3,      304,     0 ), /*   176 fla               */
  S_ST( 'k',	3,      305,   176 ), /*   177 fla               */
  S_ST( 'o',	3,      179,   175 ), /*   178 fl                */
  S_ST( 'o',	3,      306,     0 ), /*   179 flo               */
  S_ST( 'r',	3,      181,   174 ), /*   180 f                 */
  S_ST( 'e',	3,      307,     0 ), /*   181 fr                */
  S_ST( '_',	3,      183,     0 ), /*   182 freq              */
  S_ST( 'o',	3,      184,     0 ), /*   183 freq_             */
  S_ST( 'f',	3,      185,     0 ), /*   184 freq_o            */
  S_ST( 'f',	3,      186,     0 ), /*   185 freq_of           */
  S_ST( 's',	3,      187,     0 ), /*   186 freq_off          */
  S_ST( 'e',	3,      452,     0 ), /*   187 freq_offs         */
  S_ST( 'u',	3,      189,   180 ), /*   188 f                 */
  S_ST( 'd',	3,      190,     0 ), /*   189 fu                */
  S_ST( 'g',	3,      308,     0 ), /*   190 fud               */
  S_ST( 'h',	3,      194,   167 ), /*   191                   */
  S_ST( 'o',	3,      193,     0 ), /*   192 h                 */
  S_ST( 's',	3,      309,     0 ), /*   193 ho                */
  S_ST( 'u',	3,      195,   192 ), /*   194 h                 */
  S_ST( 'f',	3,      196,     0 ), /*   195 hu                */
  S_ST( 'f',	3,      197,     0 ), /*   196 huf               */
  S_ST( 'p',	3,      198,     0 ), /*   197 huff              */
  S_ST( 'u',	3,      199,     0 ), /*   198 huffp             */
  S_ST( 'f',	3,      310,     0 ), /*   199 huffpu            */
  S_ST( 'i',	3,      241,   191 ), /*   200                   */
  S_ST( 'b',	3,      202,     0 ), /*   201 i                 */
  S_ST( 'u',	3,      203,     0 ), /*   202 ib                */
  S_ST( 'r',	3,      204,     0 ), /*   203 ibu               */
  S_ST( 's',	3,      311,     0 ), /*   204 ibur              */
  S_ST( 'd',	3,      206,   201 ), /*   205 i                 */
  S_ST( 'e',	3,      207,     0 ), /*   206 id                */
  S_ST( 'n',	3,      312,     0 ), /*   207 ide               */
  S_ST( 'g',	3,      209,   205 ), /*   208 i                 */
  S_ST( 'n',	3,      210,     0 ), /*   209 ig                */
  S_ST( 'o',	3,      211,     0 ), /*   210 ign               */
  S_ST( 'r',	3,      313,     0 ), /*   211 igno              */
  S_ST( 'n',	3,      235,   208 ), /*   212 i                 */
  S_ST( 'c',	3,      225,     0 ), /*   213 in                */
  S_ST( 'a',	3,      215,     0 ), /*   214 inc               */
  S_ST( 'l',	3,      216,     0 ), /*   215 inca              */
  S_ST( 'l',	3,      217,     0 ), /*   216 incal             */
  S_ST( 'o',	3,      314,     0 ), /*   217 incall            */
  S_ST( 'l',	3,      219,   214 ), /*   218 inc               */
  S_ST( 'u',	3,      220,     0 ), /*   219 incl              */
  S_ST( 'd',	3,      221,     0 ), /*   220 inclu             */
  S_ST( 'e',	3,      222,     0 ), /*   221 includ            */
  S_ST( 'f',	3,      223,     0 ), /*   222 include           */
  S_ST( 'i',	3,      224,     0 ), /*   223 includef          */
  S_ST( 'l',	3,      318,     0 ), /*   224 includefi         */
  S_ST( 'm',	3,      226,   218 ), /*   225 inc               */
  S_ST( 'e',	3,      315,     0 ), /*   226 incm              */
  S_ST( 'i',	3,      228,   213 ), /*   227 in                */
  S_ST( 't',	3,      233,     0 ), /*   228 ini               */
  S_ST( 'a',	3,      230,     0 ), /*   229 init              */
  S_ST( 'l',	3,      231,     0 ), /*   230 inita             */
  S_ST( 'l',	3,      232,     0 ), /*   231 inital            */
  S_ST( 'o',	3,      316,     0 ), /*   232 initall           */
  S_ST( 'm',	3,      234,   229 ), /*   233 init              */
  S_ST( 'e',	3,      317,     0 ), /*   234 initm             */
  S_ST( 't',	3,      236,   227 ), /*   235 in                */
  S_ST( 'e',	3,      237,     0 ), /*   236 int               */
  S_ST( 'r',	3,      238,     0 ), /*   237 inte              */
  S_ST( 'f',	3,      239,     0 ), /*   238 inter             */
  S_ST( 'a',	3,      240,     0 ), /*   239 interf            */
  S_ST( 'c',	3,      320,     0 ), /*   240 interfa           */
  S_ST( 'p',	3,      242,   322 ), /*   241 i                 */
  S_ST( 'v',	3,      325,     0 ), /*   242 ip                */
  S_ST( 'j',	3,      244,   200 ), /*   243                   */
  S_ST( 'i',	3,      245,     0 ), /*   244 j                 */
  S_ST( 't',	3,      246,     0 ), /*   245 ji                */
  S_ST( 't',	3,      247,     0 ), /*   246 jit               */
  S_ST( 'e',	3,      454,     0 ), /*   247 jitt              */
  S_ST( 'k',	3,      255,   243 ), /*   248                   */
  S_ST( 'e',	3,      328,     0 ), /*   249 k                 */
  S_ST( 'r',	3,      251,     0 ), /*   250 ke                */
  S_ST( 'n',	3,      252,     0 ), /*   251 ker               */
  S_ST( 'e',	3,      327,     0 ), /*   252 kern              */
  S_ST( 'd',	3,      254,     0 ), /*   253 keys              */
  S_ST( 'i',	3,      330,     0 ), /*   254 keysd             */
  S_ST( 'o',	3,      331,   249 ), /*   255 k                 */
  S_ST( 'l',	3,      474,   248 ), /*   256                   */
  S_ST( 'e',	3,      289,     0 ), /*   257 l                 */
  S_ST( 'v',	1,        0,     0 ), /*   258 T_Abbrev          */
  S_ST( 'e',	0,        0,     0 ), /*   259 T_Age             */
  S_ST( 'l',	0,       12,     0 ), /*   260 T_All             */
  S_ST( 'n',	0,        0,     0 ), /*   261 T_Allan           */
  S_ST( 's',	0,        0,     0 ), /*   262 T_Allpeers        */
  S_ST( 'h',	0,        0,     0 ), /*   263 T_Auth            */
  S_ST( 'y',	0,        0,     0 ), /*   264 T_Autokey         */
  S_ST( 'x',	0,        0,     0 ), /*   265 T_Automax         */
  S_ST( 'e',	0,        0,     0 ), /*   266 T_Average         */
  S_ST( 'e',	1,        0,     0 ), /*   267 T_Basedate        */
  S_ST( 't',	0,        0,     0 ), /*   268 T_Bclient         */
  S_ST( 'p',	0,        0,     0 ), /*   269 T_Bcpollbstep     */
  S_ST( 'n',	0,        0,     0 ), /*   270 T_Beacon          */
  S_ST( 't',	1,       71,     0 ), /*   271 T_Broadcast       */
  S_ST( 't',	0,        0,     0 ), /*   272 T_Broadcastclient */
  S_ST( 'y',	0,        0,     0 ), /*   273 T_Broadcastdelay  */
  S_ST( 't',	0,        0,     0 ), /*   274 T_Burst           */
  S_ST( 'e',	0,        0,     0 ), /*   275 T_Calibrate       */
  S_ST( 'g',	0,        0,     0 ), /*   276 T_Ceiling         */
  S_ST( 's',	0,        0,     0 ), /*   277 T_Clockstats      */
  S_ST( 't',	0,        0,     0 ), /*   278 T_Cohort          */
  S_ST( 'y',	0,        0,     0 ), /*   279 T_ControlKey      */
  S_ST( 'o',	0,      114,     0 ), /*   280 T_Crypto          */
  S_ST( 's',	0,        0,     0 ), /*   281 T_Cryptostats     */
  S_ST( 'l',	0,        0,     0 ), /*   282 T_Ctl             */
  S_ST( 'y',	0,        0,     0 ), /*   283 T_Day             */
  S_ST( 't',	0,        0,     0 ), /*   284 T_Default         */
  S_ST( 't',	1,        0,     0 ), /*   285 T_Digest          */
  S_ST( 'e',	0,        0,     0 ), /*   286 T_Disable         */
  S_ST( 'd',	0,        0,     0 ), /*   287 T_Discard         */
  S_ST( 'n',	0,        0,     0 ), /*   288 T_Dispersion      */
  S_ST( 'a',	3,      297,     0 ), /*   289 le                */
  S_ST( 'e',	1,        0,     0 ), /*   290 T_Driftfile       */
  S_ST( 'p',	0,        0,     0 ), /*   291 T_Drop            */
  S_ST( 'p',	0,        0,     0 ), /*   292 T_Dscp            */
  S_ST( '.',	0,        0,     0 ), /*   293 T_Ellipsis        */
  S_ST( 'e',	0,        0,     0 ), /*   294 T_Enable          */
  S_ST( 'd',	0,        0,   161 ), /*   295 T_End             */
  S_ST( 'r',	0,        0,     0 ), /*   296 T_Epeer           */
  S_ST( 'p',	3,      433,     0 ), /*   297 lea               */
  S_ST( 'e',	1,      172,     0 ), /*   298 T_File            */
  S_ST( 'n',	0,        0,     0 ), /*   299 T_Filegen         */
  S_ST( 'm',	0,        0,     0 ), /*   300 T_Filenum         */
  S_ST( '1',	0,        0,     0 ), /*   301 T_Flag1           */
  S_ST( '2',	0,        0,   301 ), /*   302 T_Flag2           */
  S_ST( '3',	0,        0,   302 ), /*   303 T_Flag3           */
  S_ST( '4',	0,        0,   303 ), /*   304 T_Flag4           */
  S_ST( 'e',	0,        0,     0 ), /*   305 T_Flake           */
  S_ST( 'r',	0,        0,     0 ), /*   306 T_Floor           */
  S_ST( 'q',	0,      182,     0 ), /*   307 T_Freq            */
  S_ST( 'e',	1,        0,     0 ), /*   308 T_Fudge           */
  S_ST( 't',	1,        0,     0 ), /*   309 T_Host            */
  S_ST( 'f',	0,        0,     0 ), /*   310 T_Huffpuff        */
  S_ST( 't',	0,        0,     0 ), /*   311 T_Iburst          */
  S_ST( 't',	1,        0,     0 ), /*   312 T_Ident           */
  S_ST( 'e',	0,        0,     0 ), /*   313 T_Ignore          */
  S_ST( 'c',	0,        0,     0 ), /*   314 T_Incalloc        */
  S_ST( 'm',	0,        0,     0 ), /*   315 T_Incmem          */
  S_ST( 'c',	0,        0,     0 ), /*   316 T_Initalloc       */
  S_ST( 'm',	0,        0,     0 ), /*   317 T_Initmem         */
  S_ST( 'e',	1,        0,     0 ), /*   318 T_Includefile     */
  S_ST( 'f',	3,      321,     0 ), /*   319 leap              */
  S_ST( 'e',	0,        0,     0 ), /*   320 T_Interface       */
  S_ST( 'i',	3,      418,     0 ), /*   321 leapf             */
  S_ST( 'o',	0,        0,   212 ), /*   322 T_Io              */
  S_ST( '4',	0,        0,     0 ), /*   323 T_Ipv4            */
  S_ST( '4',	0,        0,     0 ), /*   324 T_Ipv4_flag       */
  S_ST( '6',	0,        0,   323 ), /*   325 T_Ipv6            */
  S_ST( '6',	0,        0,   324 ), /*   326 T_Ipv6_flag       */
  S_ST( 'l',	0,        0,     0 ), /*   327 T_Kernel          */
  S_ST( 'y',	0,      329,   250 ), /*   328 T_Key             */
  S_ST( 's',	1,      253,     0 ), /*   329 T_Keys            */
  S_ST( 'r',	1,        0,     0 ), /*   330 T_Keysdir         */
  S_ST( 'd',	0,        0,     0 ), /*   331 T_Kod             */
  S_ST( 'p',	0,        0,     0 ), /*   332 T_Mssntp          */
  S_ST( 'e',	1,        0,     0 ), /*   333 T_Leapfile        */
  S_ST( 'l',	0,        0,     0 ), /*   334 T_Leapsmearinterval */
  S_ST( 'd',	0,        0,     0 ), /*   335 T_Limited         */
  S_ST( 'k',	0,        0,     0 ), /*   336 T_Link            */
  S_ST( 'n',	0,        0,     0 ), /*   337 T_Listen          */
  S_ST( 'g',	2,        0,     0 ), /*   338 T_Logconfig       */
  S_ST( 'e',	1,        0,     0 ), /*   339 T_Logfile         */
  S_ST( 's',	0,        0,     0 ), /*   340 T_Loopstats       */
  S_ST( 'p',	0,        0,     0 ), /*   341 T_Lowpriotrap     */
  S_ST( 't',	1,        0,     0 ), /*   342 T_Manycastclient  */
  S_ST( 'r',	2,        0,     0 ), /*   343 T_Manycastserver  */
  S_ST( 'k',	0,        0,     0 ), /*   344 T_Mask            */
  S_ST( 'e',	0,        0,     0 ), /*   345 T_Maxage          */
  S_ST( 'k',	0,        0,     0 ), /*   346 T_Maxclock        */
  S_ST( 'h',	0,        0,     0 ), /*   347 T_Maxdepth        */
  S_ST( 't',	0,        0,     0 ), /*   348 T_Maxdist         */
  S_ST( 'm',	0,        0,     0 ), /*   349 T_Maxmem          */
  S_ST( 'l',	0,        0,     0 ), /*   350 T_Maxpoll         */
  S_ST( 's',	0,        0,     0 ), /*   351 T_Mdnstries       */
  S_ST( 'm',	0,      543,     0 ), /*   352 T_Mem             */
  S_ST( 'k',	0,        0,     0 ), /*   353 T_Memlock         */
  S_ST( 'k',	0,        0,     0 ), /*   354 T_Minclock        */
  S_ST( 'h',	0,        0,     0 ), /*   355 T_Mindepth        */
  S_ST( 't',	0,        0,     0 ), /*   356 T_Mindist         */
  S_ST( 'm',	0,        0,     0 ), /*   357 T_Minimum         */
  S_ST( 'l',	0,        0,     0 ), /*   358 T_Minpoll         */
  S_ST( 'e',	0,        0,     0 ), /*   359 T_Minsane         */
  S_ST( 'e',	0,      361,     0 ), /*   360 T_Mode            */
  S_ST( '7',	0,        0,     0 ), /*   361 T_Mode7           */
  S_ST( 'r',	0,        0,     0 ), /*   362 T_Monitor         */
  S_ST( 'h',	0,        0,     0 ), /*   363 T_Month           */
  S_ST( 'u',	0,        0,     0 ), /*   364 T_Mru             */
  S_ST( 't',	2,        0,     0 ), /*   365 T_Multicastclient */
  S_ST( 'c',	0,        0,     0 ), /*   366 T_Nic             */
  S_ST( 'k',	0,        0,     0 ), /*   367 T_Nolink          */
  S_ST( 'y',	0,        0,     0 ), /*   368 T_Nomodify        */
  S_ST( 't',	0,        0,     0 ), /*   369 T_Nomrulist       */
  S_ST( 'e',	0,        0,     0 ), /*   370 T_None            */
  S_ST( 'e',	0,        0,     0 ), /*   371 T_Nonvolatile     */
  S_ST( 'r',	0,        0,     0 ), /*   372 T_Noepeer         */
  S_ST( 'r',	0,        0,     0 ), /*   373 T_Nopeer          */
  S_ST( 'y',	0,        0,     0 ), /*   374 T_Noquery         */
  S_ST( 't',	0,        0,     0 ), /*   375 T_Noselect        */
  S_ST( 'e',	0,        0,     0 ), /*   376 T_Noserve         */
  S_ST( 'p',	0,        0,     0 ), /*   377 T_Notrap          */
  S_ST( 't',	0,        0,     0 ), /*   378 T_Notrust         */
  S_ST( 'p',	0,      643,     0 ), /*   379 T_Ntp             */
  S_ST( 't',	0,        0,     0 ), /*   380 T_Ntpport         */
  S_ST( 't',	1,        0,     0 ), /*   381 T_NtpSignDsocket  */
  S_ST( 'n',	0,      658,     0 ), /*   382 T_Orphan          */
  S_ST( 't',	0,        0,     0 ), /*   383 T_Orphanwait      */
  S_ST( 'y',	0,        0,     0 ), /*   384 T_PCEdigest       */
  S_ST( 'c',	0,        0,     0 ), /*   385 T_Panic           */
  S_ST( 'r',	1,      685,     0 ), /*   386 T_Peer            */
  S_ST( 's',	0,        0,     0 ), /*   387 T_Peerstats       */
  S_ST( 'e',	2,        0,     0 ), /*   388 T_Phone           */
  S_ST( 'd',	0,      693,     0 ), /*   389 T_Pid             */
  S_ST( 'e',	1,        0,     0 ), /*   390 T_Pidfile         */
  S_ST( 'l',	1,        0,     0 ), /*   391 T_Pool            */
  S_ST( 't',	0,        0,     0 ), /*   392 T_Port            */
  S_ST( 't',	0,        0,     0 ), /*   393 T_Preempt         */
  S_ST( 'r',	0,        0,     0 ), /*   394 T_Prefer          */
  S_ST( 's',	0,        0,     0 ), /*   395 T_Protostats      */
  S_ST( 'w',	1,        0,   699 ), /*   396 T_Pw              */
  S_ST( 'e',	1,        0,     0 ), /*   397 T_Randfile        */
  S_ST( 's',	0,        0,     0 ), /*   398 T_Rawstats        */
  S_ST( 'd',	1,        0,     0 ), /*   399 T_Refid           */
  S_ST( 'y',	0,        0,     0 ), /*   400 T_Requestkey      */
  S_ST( 't',	0,        0,     0 ), /*   401 T_Reset           */
  S_ST( 't',	0,        0,     0 ), /*   402 T_Restrict        */
  S_ST( 'e',	0,        0,     0 ), /*   403 T_Revoke          */
  S_ST( 't',	0,        0,     0 ), /*   404 T_Rlimit          */
  S_ST( 'r',	1,        0,     0 ), /*   405 T_Saveconfigdir   */
  S_ST( 'r',	1,      776,     0 ), /*   406 T_Server          */
  S_ST( 'r',	1,        0,     0 ), /*   407 T_Setvar          */
  S_ST( 'e',	0,        0,     0 ), /*   408 T_Source          */
  S_ST( 'e',	0,        0,     0 ), /*   409 T_Stacksize       */
  S_ST( 's',	0,        0,     0 ), /*   410 T_Statistics      */
  S_ST( 's',	0,      819,   814 ), /*   411 T_Stats           */
  S_ST( 'r',	1,        0,     0 ), /*   412 T_Statsdir        */
  S_ST( 'p',	0,      827,     0 ), /*   413 T_Step            */
  S_ST( 'k',	0,        0,     0 ), /*   414 T_Stepback        */
  S_ST( 'd',	0,        0,     0 ), /*   415 T_Stepfwd         */
  S_ST( 't',	0,        0,     0 ), /*   416 T_Stepout         */
  S_ST( 'm',	0,        0,     0 ), /*   417 T_Stratum         */
  S_ST( 'l',	3,      333,     0 ), /*   418 leapfi            */
  S_ST( 's',	0,      834,     0 ), /*   419 T_Sys             */
  S_ST( 's',	0,        0,     0 ), /*   420 T_Sysstats        */
  S_ST( 'k',	0,        0,     0 ), /*   421 T_Tick            */
  S_ST( '1',	0,        0,     0 ), /*   422 T_Time1           */
  S_ST( '2',	0,        0,   422 ), /*   423 T_Time2           */
  S_ST( 'r',	0,        0,   423 ), /*   424 T_Timer           */
  S_ST( 's',	0,        0,     0 ), /*   425 T_Timingstats     */
  S_ST( 'r',	0,        0,     0 ), /*   426 T_Tinker          */
  S_ST( 's',	0,        0,     0 ), /*   427 T_Tos             */
  S_ST( 'p',	1,        0,     0 ), /*   428 T_Trap            */
  S_ST( 'e',	0,        0,     0 ), /*   429 T_True            */
  S_ST( 'y',	0,        0,     0 ), /*   430 T_Trustedkey      */
  S_ST( 'l',	0,        0,     0 ), /*   431 T_Ttl             */
  S_ST( 'e',	0,        0,     0 ), /*   432 T_Type            */
  S_ST( 's',	3,      440,   319 ), /*   433 leap              */
  S_ST( 'y',	0,        0,     0 ), /*   434 T_UEcrypto        */
  S_ST( 'y',	0,        0,     0 ), /*   435 T_UEcryptonak     */
  S_ST( 'y',	0,        0,     0 ), /*   436 T_UEdigest        */
  S_ST( 'g',	1,        0,     0 ), /*   437 T_Unconfig        */
  S_ST( 'r',	1,      876,     0 ), /*   438 T_Unpeer          */
  S_ST( 'n',	0,        0,     0 ), /*   439 T_Version         */
  S_ST( 'm',	3,      445,     0 ), /*   440 leaps             */
  S_ST( 'k',	0,        0,     0 ), /*   441 T_Week            */
  S_ST( 'd',	0,        0,     0 ), /*   442 T_Wildcard        */
  S_ST( 'e',	0,        0,     0 ), /*   443 T_Xleave          */
  S_ST( 'r',	0,        0,     0 ), /*   444 T_Year            */
  S_ST( 'e',	3,      446,     0 ), /*   445 leapsm            */
  S_ST( 'a',	3,      457,     0 ), /*   446 leapsme           */
  S_ST( 'e',	0,        0,     0 ), /*   447 T_Simulate        */
  S_ST( 'y',	0,        0,     0 ), /*   448 T_Beep_Delay      */
  S_ST( 'n',	0,        0,     0 ), /*   449 T_Sim_Duration    */
  S_ST( 't',	0,        0,     0 ), /*   450 T_Server_Offset   */
  S_ST( 'n',	0,        0,     0 ), /*   451 T_Duration        */
  S_ST( 't',	0,        0,     0 ), /*   452 T_Freq_Offset     */
  S_ST( 'r',	0,        0,     0 ), /*   453 T_Wander          */
  S_ST( 'r',	0,        0,     0 ), /*   454 T_Jitter          */
  S_ST( 'y',	0,        0,     0 ), /*   455 T_Prop_Delay      */
  S_ST( 'y',	0,        0,     0 ), /*   456 T_Proc_Delay      */
  S_ST( 'r',	3,      458,     0 ), /*   457 leapsmea          */
  S_ST( 'i',	3,      459,     0 ), /*   458 leapsmear         */
  S_ST( 'n',	3,      460,     0 ), /*   459 leapsmeari        */
  S_ST( 't',	3,      461,     0 ), /*   460 leapsmearin       */
  S_ST( 'e',	3,      462,     0 ), /*   461 leapsmearint      */
  S_ST( 'r',	3,      463,     0 ), /*   462 leapsmearinte     */
  S_ST( 'v',	3,      464,     0 ), /*   463 leapsmearinter    */
  S_ST( 'a',	3,      334,     0 ), /*   464 leapsmearinterv   */
  S_ST( 'i',	3,      471,   257 ), /*   465 l                 */
  S_ST( 'm',	3,      467,     0 ), /*   466 li                */
  S_ST( 'i',	3,      468,     0 ), /*   467 lim               */
  S_ST( 't',	3,      469,     0 ), /*   468 limi              */
  S_ST( 'e',	3,      335,     0 ), /*   469 limit             */
  S_ST( 'n',	3,      336,   466 ), /*   470 li                */
  S_ST( 's',	3,      472,   470 ), /*   471 li                */
  S_ST( 't',	3,      473,     0 ), /*   472 lis               */
  S_ST( 'e',	3,      337,     0 ), /*   473 list              */
  S_ST( 'o',	3,      490,   465 ), /*   474 l                 */
  S_ST( 'g',	3,      481,     0 ), /*   475 lo                */
  S_ST( 'c',	3,      477,     0 ), /*   476 log               */
  S_ST( 'o',	3,      478,     0 ), /*   477 logc              */
  S_ST( 'n',	3,      479,     0 ), /*   478 logco             */
  S_ST( 'f',	3,      480,     0 ), /*   479 logcon            */
  S_ST( 'i',	3,      338,     0 ), /*   480 logconf           */
  S_ST( 'f',	3,      482,   476 ), /*   481 log               */
  S_ST( 'i',	3,      483,     0 ), /*   482 logf              */
  S_ST( 'l',	3,      339,     0 ), /*   483 logfi             */
  S_ST( 'o',	3,      485,   475 ), /*   484 lo                */
  S_ST( 'p',	3,      486,     0 ), /*   485 loo               */
  S_ST( 's',	3,      487,     0 ), /*   486 loop              */
  S_ST( 't',	3,      488,     0 ), /*   487 loops             */
  S_ST( 'a',	3,      489,     0 ), /*   488 loopst            */
  S_ST( 't',	3,      340,     0 ), /*   489 loopsta           */
  S_ST( 'w',	3,      491,   484 ), /*   490 lo                */
  S_ST( 'p',	3,      492,     0 ), /*   491 low               */
  S_ST( 'r',	3,      493,     0 ), /*   492 lowp              */
  S_ST( 'i',	3,      494,     0 ), /*   493 lowpr             */
  S_ST( 'o',	3,      495,     0 ), /*   494 lowpri            */
  S_ST( 't',	3,      496,     0 ), /*   495 lowprio           */
  S_ST( 'r',	3,      497,     0 ), /*   496 lowpriot          */
  S_ST( 'a',	3,      341,     0 ), /*   497 lowpriotr         */
  S_ST( 'm',	3,      579,   256 ), /*   498                   */
  S_ST( 'a',	3,      517,     0 ), /*   499 m                 */
  S_ST( 'n',	3,      501,     0 ), /*   500 ma                */
  S_ST( 'y',	3,      502,     0 ), /*   501 man               */
  S_ST( 'c',	3,      503,     0 ), /*   502 many              */
  S_ST( 'a',	3,      504,     0 ), /*   503 manyc             */
  S_ST( 's',	3,      505,     0 ), /*   504 manyca            */
  S_ST( 't',	3,      511,     0 ), /*   505 manycas           */
  S_ST( 'c',	3,      507,     0 ), /*   506 manycast          */
  S_ST( 'l',	3,      508,     0 ), /*   507 manycastc         */
  S_ST( 'i',	3,      509,     0 ), /*   508 manycastcl        */
  S_ST( 'e',	3,      510,     0 ), /*   509 manycastcli       */
  S_ST( 'n',	3,      342,     0 ), /*   510 manycastclie      */
  S_ST( 's',	3,      512,   506 ), /*   511 manycast          */
  S_ST( 'e',	3,      513,     0 ), /*   512 manycasts         */
  S_ST( 'r',	3,      514,     0 ), /*   513 manycastse        */
  S_ST( 'v',	3,      515,     0 ), /*   514 manycastser       */
  S_ST( 'e',	3,      343,     0 ), /*   515 manycastserv      */
  S_ST( 's',	3,      344,   500 ), /*   516 ma                */
  S_ST( 'x',	3,      532,   516 ), /*   517 ma                */
  S_ST( 'a',	3,      519,     0 ), /*   518 max               */
  S_ST( 'g',	3,      345,     0 ), /*   519 maxa              */
  S_ST( 'c',	3,      521,   518 ), /*   520 max               */
  S_ST( 'l',	3,      522,     0 ), /*   521 maxc              */
  S_ST( 'o',	3,      523,     0 ), /*   522 maxcl             */
  S_ST( 'c',	3,      346,     0 ), /*   523 maxclo            */
  S_ST( 'd',	3,      528,   520 ), /*   524 max               */
  S_ST( 'e',	3,      526,     0 ), /*   525 maxd              */
  S_ST( 'p',	3,      527,     0 ), /*   526 maxde             */
  S_ST( 't',	3,      347,     0 ), /*   527 maxdep            */
  S_ST( 'i',	3,      529,   525 ), /*   528 maxd              */
  S_ST( 's',	3,      348,     0 ), /*   529 maxdi             */
  S_ST( 'm',	3,      531,   524 ), /*   530 max               */
  S_ST( 'e',	3,      349,     0 ), /*   531 maxm              */
  S_ST( 'p',	3,      533,   530 ), /*   532 max               */
  S_ST( 'o',	3,      534,     0 ), /*   533 maxp              */
  S_ST( 'l',	3,      350,     0 ), /*   534 maxpo             */
  S_ST( 'd',	3,      536,   499 ), /*   535 m                 */
  S_ST( 'n',	3,      537,     0 ), /*   536 md                */
  S_ST( 's',	3,      538,     0 ), /*   537 mdn               */
  S_ST( 't',	3,      539,     0 ), /*   538 mdns              */
  S_ST( 'r',	3,      540,     0 ), /*   539 mdnst             */
  S_ST( 'i',	3,      541,     0 ), /*   540 mdnstr            */
  S_ST( 'e',	3,      351,     0 ), /*   541 mdnstri           */
  S_ST( 'e',	3,      352,   535 ), /*   542 m                 */
  S_ST( 'l',	3,      544,     0 ), /*   543 mem               */
  S_ST( 'o',	3,      545,     0 ), /*   544 meml              */
  S_ST( 'c',	3,      353,     0 ), /*   545 memlo             */
  S_ST( 'i',	3,      547,   542 ), /*   546 m                 */
  S_ST( 'n',	3,      564,     0 ), /*   547 mi                */
  S_ST( 'c',	3,      549,     0 ), /*   548 min               */
  S_ST( 'l',	3,      550,     0 ), /*   549 minc              */
  S_ST( 'o',	3,      551,     0 ), /*   550 mincl             */
  S_ST( 'c',	3,      354,     0 ), /*   551 minclo            */
  S_ST( 'd',	3,      556,   548 ), /*   552 min               */
  S_ST( 'e',	3,      554,     0 ), /*   553 mind              */
  S_ST( 'p',	3,      555,     0 ), /*   554 minde             */
  S_ST( 't',	3,      355,     0 ), /*   555 mindep            */
  S_ST( 'i',	3,      557,   553 ), /*   556 mind              */
  S_ST( 's',	3,      356,     0 ), /*   557 mindi             */
  S_ST( 'i',	3,      559,   552 ), /*   558 min               */
  S_ST( 'm',	3,      560,     0 ), /*   559 mini              */
  S_ST( 'u',	3,      357,     0 ), /*   560 minim             */
  S_ST( 'p',	3,      562,   558 ), /*   561 min               */
  S_ST( 'o',	3,      563,     0 ), /*   562 minp              */
  S_ST( 'l',	3,      358,     0 ), /*   563 minpo             */
  S_ST( 's',	3,      565,   561 ), /*   564 min               */
  S_ST( 'a',	3,      566,     0 ), /*   565 mins              */
  S_ST( 'n',	3,      359,     0 ), /*   566 minsa             */
  S_ST( 'o',	3,      569,   546 ), /*   567 m                 */
  S_ST( 'd',	3,      360,     0 ), /*   568 mo                */
  S_ST( 'n',	3,      573,   568 ), /*   569 mo                */
  S_ST( 'i',	3,      571,     0 ), /*   570 mon               */
  S_ST( 't',	3,      572,     0 ), /*   571 moni              */
  S_ST( 'o',	3,      362,     0 ), /*   572 monit             */
  S_ST( 't',	3,      363,   570 ), /*   573 mon               */
  S_ST( 'r',	3,      364,   567 ), /*   574 m                 */
  S_ST( 's',	3,      576,   574 ), /*   575 m                 */
  S_ST( 's',	3,      577,     0 ), /*   576 ms                */
  S_ST( 'n',	3,      578,     0 ), /*   577 mss               */
  S_ST( 't',	3,      332,     0 ), /*   578 mssn              */
  S_ST( 'u',	3,      580,   575 ), /*   579 m                 */
  S_ST( 'l',	3,      581,     0 ), /*   580 mu                */
  S_ST( 't',	3,      582,     0 ), /*   581 mul               */
  S_ST( 'i',	3,      583,     0 ), /*   582 mult              */
  S_ST( 'c',	3,      584,     0 ), /*   583 multi             */
  S_ST( 'a',	3,      585,     0 ), /*   584 multic            */
  S_ST( 's',	3,      586,     0 ), /*   585 multica           */
  S_ST( 't',	3,      587,     0 ), /*   586 multicas          */
  S_ST( 'c',	3,      588,     0 ), /*   587 multicast         */
  S_ST( 'l',	3,      589,     0 ), /*   588 multicastc        */
  S_ST( 'i',	3,      590,     0 ), /*   589 multicastcl       */
  S_ST( 'e',	3,      591,     0 ), /*   590 multicastcli      */
  S_ST( 'n',	3,      365,     0 ), /*   591 multicastclie     */
  S_ST( 'n',	3,      639,   498 ), /*   592                   */
  S_ST( 'i',	3,      366,     0 ), /*   593 n                 */
  S_ST( 'o',	3,      634,   593 ), /*   594 n                 */
  S_ST( 'e',	3,      596,     0 ), /*   595 no                */
  S_ST( 'p',	3,      597,     0 ), /*   596 noe               */
  S_ST( 'e',	3,      598,     0 ), /*   597 noep              */
  S_ST( 'e',	3,      372,     0 ), /*   598 noepe             */
  S_ST( 'l',	3,      600,   595 ), /*   599 no                */
  S_ST( 'i',	3,      601,     0 ), /*   600 nol               */
  S_ST( 'n',	3,      367,     0 ), /*   601 noli              */
  S_ST( 'm',	3,      607,   599 ), /*   602 no                */
  S_ST( 'o',	3,      604,     0 ), /*   603 nom               */
  S_ST( 'd',	3,      605,     0 ), /*   604 nomo              */
  S_ST( 'i',	3,      606,     0 ), /*   605 nomod             */
  S_ST( 'f',	3,      368,     0 ), /*   606 nomodi            */
  S_ST( 'r',	3,      608,   603 ), /*   607 nom               */
  S_ST( 'u',	3,      609,     0 ), /*   608 nomr              */
  S_ST( 'l',	3,      610,     0 ), /*   609 nomru             */
  S_ST( 'i',	3,      611,     0 ), /*   610 nomrul            */
  S_ST( 's',	3,      369,     0 ), /*   611 nomruli           */
  S_ST( 'n',	3,      613,   602 ), /*   612 no                */
  S_ST( 'v',	3,      614,   370 ), /*   613 non               */
  S_ST( 'o',	3,      615,     0 ), /*   614 nonv              */
  S_ST( 'l',	3,      616,     0 ), /*   615 nonvo             */
  S_ST( 'a',	3,      617,     0 ), /*   616 nonvol            */
  S_ST( 't',	3,      618,     0 ), /*   617 nonvola           */
  S_ST( 'i',	3,      619,     0 ), /*   618 nonvolat          */
  S_ST( 'l',	3,      371,     0 ), /*   619 nonvolati         */
  S_ST( 'p',	3,      621,   612 ), /*   620 no                */
  S_ST( 'e',	3,      622,     0 ), /*   621 nop               */
  S_ST( 'e',	3,      373,     0 ), /*   622 nope              */
  S_ST( 'q',	3,      624,   620 ), /*   623 no                */
  S_ST( 'u',	3,      625,     0 ), /*   624 noq               */
  S_ST( 'e',	3,      626,     0 ), /*   625 noqu              */
  S_ST( 'r',	3,      374,     0 ), /*   626 noque             */
  S_ST( 's',	3,      628,   623 ), /*   627 no                */
  S_ST( 'e',	3,      632,     0 ), /*   628 nos               */
  S_ST( 'l',	3,      630,     0 ), /*   629 nose              */
  S_ST( 'e',	3,      631,     0 ), /*   630 nosel             */
  S_ST( 'c',	3,      375,     0 ), /*   631 nosele            */
  S_ST( 'r',	3,      633,   629 ), /*   632 nose              */
  S_ST( 'v',	3,      376,     0 ), /*   633 noser             */
  S_ST( 't',	3,      635,   627 ), /*   634 no                */
  S_ST( 'r',	3,      637,     0 ), /*   635 not               */
  S_ST( 'a',	3,      377,     0 ), /*   636 notr              */
  S_ST( 'u',	3,      638,   636 ), /*   637 notr              */
  S_ST( 's',	3,      378,     0 ), /*   638 notru             */
  S_ST( 't',	3,      379,   594 ), /*   639 n                 */
  S_ST( 'p',	3,      641,     0 ), /*   640 ntp               */
  S_ST( 'o',	3,      642,     0 ), /*   641 ntpp              */
  S_ST( 'r',	3,      380,     0 ), /*   642 ntppo             */
  S_ST( 's',	3,      644,   640 ), /*   643 ntp               */
  S_ST( 'i',	3,      645,     0 ), /*   644 ntps              */
  S_ST( 'g',	3,      646,     0 ), /*   645 ntpsi             */
  S_ST( 'n',	3,      647,     0 ), /*   646 ntpsig            */
  S_ST( 'd',	3,      648,     0 ), /*   647 ntpsign           */
  S_ST( 's',	3,      649,     0 ), /*   648 ntpsignd          */
  S_ST( 'o',	3,      650,     0 ), /*   649 ntpsignds         */
  S_ST( 'c',	3,      651,     0 ), /*   650 ntpsigndso        */
  S_ST( 'k',	3,      652,     0 ), /*   651 ntpsigndsoc       */
  S_ST( 'e',	3,      381,     0 ), /*   652 ntpsigndsock      */
  S_ST( 'o',	3,      654,   592 ), /*   653                   */
  S_ST( 'r',	3,      655,     0 ), /*   654 o                 */
  S_ST( 'p',	3,      656,     0 ), /*   655 or                */
  S_ST( 'h',	3,      657,     0 ), /*   656 orp               */
  S_ST( 'a',	3,      382,     0 ), /*   657 orph              */
  S_ST( 'w',	3,      659,     0 ), /*   658 orphan            */
  S_ST( 'a',	3,      660,     0 ), /*   659 orphanw           */
  S_ST( 'i',	3,      383,     0 ), /*   660 orphanwa          */
  S_ST( 'p',	3,      396,   653 ), /*   661                   */
  S_ST( 'a',	3,      663,     0 ), /*   662 p                 */
  S_ST( 'n',	3,      664,     0 ), /*   663 pa                */
  S_ST( 'i',	3,      385,     0 ), /*   664 pan               */
  S_ST( 'e',	3,      666,   662 ), /*   665 p                 */
  S_ST( 'e',	3,      386,     0 ), /*   666 pe                */
  S_ST( '_',	3,      668,     0 ), /*   667 peer              */
  S_ST( 'c',	3,      669,     0 ), /*   668 peer_             */
  S_ST( 'l',	3,      670,     0 ), /*   669 peer_c            */
  S_ST( 'e',	3,      671,     0 ), /*   670 peer_cl           */
  S_ST( 'a',	3,      672,     0 ), /*   671 peer_cle          */
  S_ST( 'r',	3,      673,     0 ), /*   672 peer_clea         */
  S_ST( '_',	3,      674,     0 ), /*   673 peer_clear        */
  S_ST( 'd',	3,      675,     0 ), /*   674 peer_clear_       */
  S_ST( 'i',	3,      676,     0 ), /*   675 peer_clear_d      */
  S_ST( 'g',	3,      677,     0 ), /*   676 peer_clear_di     */
  S_ST( 'e',	3,      678,     0 ), /*   677 peer_clear_dig    */
  S_ST( 's',	3,      679,     0 ), /*   678 peer_clear_dige   */
  S_ST( 't',	3,      680,     0 ), /*   679 peer_clear_diges  */
  S_ST( '_',	3,      681,     0 ), /*   680 peer_clear_digest */
  S_ST( 'e',	3,      682,     0 ), /*   681 peer_clear_digest_ */
  S_ST( 'a',	3,      683,     0 ), /*   682 peer_clear_digest_e */
  S_ST( 'r',	3,      684,     0 ), /*   683 peer_clear_digest_ea */
  S_ST( 'l',	3,      384,     0 ), /*   684 peer_clear_digest_ear */
  S_ST( 's',	3,      686,   667 ), /*   685 peer              */
  S_ST( 't',	3,      687,     0 ), /*   686 peers             */
  S_ST( 'a',	3,      688,     0 ), /*   687 peerst            */
  S_ST( 't',	3,      387,     0 ), /*   688 peersta           */
  S_ST( 'h',	3,      690,   665 ), /*   689 p                 */
  S_ST( 'o',	3,      691,     0 ), /*   690 ph                */
  S_ST( 'n',	3,      388,     0 ), /*   691 pho               */
  S_ST( 'i',	3,      389,   689 ), /*   692 p                 */
  S_ST( 'f',	3,      694,     0 ), /*   693 pid               */
  S_ST( 'i',	3,      695,     0 ), /*   694 pidf              */
  S_ST( 'l',	3,      390,     0 ), /*   695 pidfi             */
  S_ST( 'o',	3,      698,   692 ), /*   696 p                 */
  S_ST( 'o',	3,      391,     0 ), /*   697 po                */
  S_ST( 'r',	3,      392,   697 ), /*   698 po                */
  S_ST( 'r',	3,      706,   696 ), /*   699 p                 */
  S_ST( 'e',	3,      704,     0 ), /*   700 pr                */
  S_ST( 'e',	3,      702,     0 ), /*   701 pre               */
  S_ST( 'm',	3,      703,     0 ), /*   702 pree              */
  S_ST( 'p',	3,      393,     0 ), /*   703 preem             */
  S_ST( 'f',	3,      705,   701 ), /*   704 pre               */
  S_ST( 'e',	3,      394,     0 ), /*   705 pref              */
  S_ST( 'o',	3,      719,   700 ), /*   706 pr                */
  S_ST( 'c',	3,      708,     0 ), /*   707 pro               */
  S_ST( '_',	3,      709,     0 ), /*   708 proc              */
  S_ST( 'd',	3,      710,     0 ), /*   709 proc_             */
  S_ST( 'e',	3,      711,     0 ), /*   710 proc_d            */
  S_ST( 'l',	3,      712,     0 ), /*   711 proc_de           */
  S_ST( 'a',	3,      456,     0 ), /*   712 proc_del          */
  S_ST( 'p',	3,      714,   707 ), /*   713 pro               */
  S_ST( '_',	3,      715,     0 ), /*   714 prop              */
  S_ST( 'd',	3,      716,     0 ), /*   715 prop_             */
  S_ST( 'e',	3,      717,     0 ), /*   716 prop_d            */
  S_ST( 'l',	3,      718,     0 ), /*   717 prop_de           */
  S_ST( 'a',	3,      455,     0 ), /*   718 prop_del          */
  S_ST( 't',	3,      720,   713 ), /*   719 pro               */
  S_ST( 'o',	3,      721,     0 ), /*   720 prot              */
  S_ST( 's',	3,      722,     0 ), /*   721 proto             */
  S_ST( 't',	3,      723,     0 ), /*   722 protos            */
  S_ST( 'a',	3,      724,     0 ), /*   723 protost           */
  S_ST( 't',	3,      395,     0 ), /*   724 protosta          */
  S_ST( 'r',	3,      756,   661 ), /*   725                   */
  S_ST( 'a',	3,      732,     0 ), /*   726 r                 */
  S_ST( 'n',	3,      728,     0 ), /*   727 ra                */
  S_ST( 'd',	3,      729,     0 ), /*   728 ran               */
  S_ST( 'f',	3,      730,     0 ), /*   729 rand              */
  S_ST( 'i',	3,      731,     0 ), /*   730 randf             */
  S_ST( 'l',	3,      397,     0 ), /*   731 randfi            */
  S_ST( 'w',	3,      733,   727 ), /*   732 ra                */
  S_ST( 's',	3,      734,     0 ), /*   733 raw               */
  S_ST( 't',	3,      735,     0 ), /*   734 raws              */
  S_ST( 'a',	3,      736,     0 ), /*   735 rawst             */
  S_ST( 't',	3,      398,     0 ), /*   736 rawsta            */
  S_ST( 'e',	3,      753,   726 ), /*   737 r                 */
  S_ST( 'f',	3,      739,     0 ), /*   738 re                */
  S_ST( 'i',	3,      399,     0 ), /*   739 ref               */
  S_ST( 'q',	3,      741,   738 ), /*   740 re                */
  S_ST( 'u',	3,      742,     0 ), /*   741 req               */
  S_ST( 'e',	3,      743,     0 ), /*   742 requ              */
  S_ST( 's',	3,      744,     0 ), /*   743 reque             */
  S_ST( 't',	3,      745,     0 ), /*   744 reques            */
  S_ST( 'k',	3,      746,     0 ), /*   745 request           */
  S_ST( 'e',	3,      400,     0 ), /*   746 requestk          */
  S_ST( 's',	3,      749,   740 ), /*   747 re                */
  S_ST( 'e',	3,      401,     0 ), /*   748 res               */
  S_ST( 't',	3,      750,   748 ), /*   749 res               */
  S_ST( 'r',	3,      751,     0 ), /*   750 rest              */
  S_ST( 'i',	3,      752,     0 ), /*   751 restr             */
  S_ST( 'c',	3,      402,     0 ), /*   752 restri            */
  S_ST( 'v',	3,      754,   747 ), /*   753 re                */
  S_ST( 'o',	3,      755,     0 ), /*   754 rev               */
  S_ST( 'k',	3,      403,     0 ), /*   755 revo              */
  S_ST( 'l',	3,      757,   737 ), /*   756 r                 */
  S_ST( 'i',	3,      758,     0 ), /*   757 rl                */
  S_ST( 'm',	3,      759,     0 ), /*   758 rli               */
  S_ST( 'i',	3,      404,     0 ), /*   759 rlim              */
  S_ST( 's',	3,      833,   725 ), /*   760                   */
  S_ST( 'a',	3,      762,     0 ), /*   761 s                 */
  S_ST( 'v',	3,      763,     0 ), /*   762 sa                */
  S_ST( 'e',	3,      764,     0 ), /*   763 sav               */
  S_ST( 'c',	3,      765,     0 ), /*   764 save              */
  S_ST( 'o',	3,      766,     0 ), /*   765 savec             */
  S_ST( 'n',	3,      767,     0 ), /*   766 saveco            */
  S_ST( 'f',	3,      768,     0 ), /*   767 savecon           */
  S_ST( 'i',	3,      769,     0 ), /*   768 saveconf          */
  S_ST( 'g',	3,      770,     0 ), /*   769 saveconfi         */
  S_ST( 'd',	3,      771,     0 ), /*   770 saveconfig        */
  S_ST( 'i',	3,      405,     0 ), /*   771 saveconfigd       */
  S_ST( 'e',	3,      782,   761 ), /*   772 s                 */
  S_ST( 'r',	3,      774,     0 ), /*   773 se                */
  S_ST( 'v',	3,      775,     0 ), /*   774 ser               */
  S_ST( 'e',	3,      406,     0 ), /*   775 serv              */
  S_ST( '_',	3,      777,     0 ), /*   776 server            */
  S_ST( 'o',	3,      778,     0 ), /*   777 server_           */
  S_ST( 'f',	3,      779,     0 ), /*   778 server_o          */
  S_ST( 'f',	3,      780,     0 ), /*   779 server_of         */
  S_ST( 's',	3,      781,     0 ), /*   780 server_off        */
  S_ST( 'e',	3,      450,     0 ), /*   781 server_offs       */
  S_ST( 't',	3,      783,   773 ), /*   782 se                */
  S_ST( 'v',	3,      784,     0 ), /*   783 set               */
  S_ST( 'a',	3,      407,     0 ), /*   784 setv              */
  S_ST( 'i',	3,      786,   772 ), /*   785 s                 */
  S_ST( 'm',	3,      787,     0 ), /*   786 si                */
  S_ST( 'u',	3,      788,     0 ), /*   787 sim               */
  S_ST( 'l',	3,      789,     0 ), /*   788 simu              */
  S_ST( 'a',	3,      790,     0 ), /*   789 simul             */
  S_ST( 't',	3,      791,     0 ), /*   790 simula            */
  S_ST( 'i',	3,      792,   447 ), /*   791 simulat           */
  S_ST( 'o',	3,      793,     0 ), /*   792 simulati          */
  S_ST( 'n',	3,      794,     0 ), /*   793 simulatio         */
  S_ST( '_',	3,      795,     0 ), /*   794 simulation        */
  S_ST( 'd',	3,      796,     0 ), /*   795 simulation_       */
  S_ST( 'u',	3,      797,     0 ), /*   796 simulation_d      */
  S_ST( 'r',	3,      798,     0 ), /*   797 simulation_du     */
  S_ST( 'a',	3,      799,     0 ), /*   798 simulation_dur    */
  S_ST( 't',	3,      800,     0 ), /*   799 simulation_dura   */
  S_ST( 'i',	3,      801,     0 ), /*   800 simulation_durat  */
  S_ST( 'o',	3,      449,     0 ), /*   801 simulation_durati */
  S_ST( 'o',	3,      803,   785 ), /*   802 s                 */
  S_ST( 'u',	3,      804,     0 ), /*   803 so                */
  S_ST( 'r',	3,      805,     0 ), /*   804 sou               */
  S_ST( 'c',	3,      408,     0 ), /*   805 sour              */
  S_ST( 't',	3,      829,   802 ), /*   806 s                 */
  S_ST( 'a',	3,      813,     0 ), /*   807 st                */
  S_ST( 'c',	3,      809,     0 ), /*   808 sta               */
  S_ST( 'k',	3,      810,     0 ), /*   809 stac              */
  S_ST( 's',	3,      811,     0 ), /*   810 stack             */
  S_ST( 'i',	3,      812,     0 ), /*   811 stacks            */
  S_ST( 'z',	3,      409,     0 ), /*   812 stacksi           */
  S_ST( 't',	3,      411,   808 ), /*   813 sta               */
  S_ST( 'i',	3,      815,     0 ), /*   814 stat              */
  S_ST( 's',	3,      816,     0 ), /*   815 stati             */
  S_ST( 't',	3,      817,     0 ), /*   816 statis            */
  S_ST( 'i',	3,      818,     0 ), /*   817 statist           */
  S_ST( 'c',	3,      410,     0 ), /*   818 statisti          */
  S_ST( 'd',	3,      820,     0 ), /*   819 stats             */
  S_ST( 'i',	3,      412,     0 ), /*   820 statsd            */
  S_ST( 'e',	3,      413,   807 ), /*   821 st                */
  S_ST( 'b',	3,      823,     0 ), /*   822 step              */
  S_ST( 'a',	3,      824,     0 ), /*   823 stepb             */
  S_ST( 'c',	3,      414,     0 ), /*   824 stepba            */
  S_ST( 'f',	3,      826,   822 ), /*   825 step              */
  S_ST( 'w',	3,      415,     0 ), /*   826 stepf             */
  S_ST( 'o',	3,      828,   825 ), /*   827 step              */
  S_ST( 'u',	3,      416,     0 ), /*   828 stepo             */
  S_ST( 'r',	3,      830,   821 ), /*   829 st                */
  S_ST( 'a',	3,      831,     0 ), /*   830 str               */
  S_ST( 't',	3,      832,     0 ), /*   831 stra              */
  S_ST( 'u',	3,      417,     0 ), /*   832 strat             */
  S_ST( 'y',	3,      419,   806 ), /*   833 s                 */
  S_ST( 's',	3,      835,     0 ), /*   834 sys               */
  S_ST( 't',	3,      836,     0 ), /*   835 syss              */
  S_ST( 'a',	3,      837,     0 ), /*   836 sysst             */
  S_ST( 't',	3,      420,     0 ), /*   837 syssta            */
  S_ST( 't',	3,      864,   760 ), /*   838                   */
  S_ST( 'i',	3,      850,     0 ), /*   839 t                 */
  S_ST( 'c',	3,      421,     0 ), /*   840 ti                */
  S_ST( 'm',	3,      843,   840 ), /*   841 ti                */
  S_ST( 'e',	3,      424,     0 ), /*   842 tim               */
  S_ST( 'i',	3,      844,   842 ), /*   843 tim               */
  S_ST( 'n',	3,      845,     0 ), /*   844 timi              */
  S_ST( 'g',	3,      846,     0 ), /*   845 timin             */
  S_ST( 's',	3,      847,     0 ), /*   846 timing            */
  S_ST( 't',	3,      848,     0 ), /*   847 timings           */
  S_ST( 'a',	3,      849,     0 ), /*   848 timingst          */
  S_ST( 't',	3,      425,     0 ), /*   849 timingsta         */
  S_ST( 'n',	3,      851,   841 ), /*   850 ti                */
  S_ST( 'k',	3,      852,     0 ), /*   851 tin               */
  S_ST( 'e',	3,      426,     0 ), /*   852 tink              */
  S_ST( 'o',	3,      427,   839 ), /*   853 t                 */
  S_ST( 'r',	3,      856,   853 ), /*   854 t                 */
  S_ST( 'a',	3,      428,     0 ), /*   855 tr                */
  S_ST( 'u',	3,      857,   855 ), /*   856 tr                */
  S_ST( 's',	3,      858,   429 ), /*   857 tru               */
  S_ST( 't',	3,      859,     0 ), /*   858 trus              */
  S_ST( 'e',	3,      860,     0 ), /*   859 trust             */
  S_ST( 'd',	3,      861,     0 ), /*   860 truste            */
  S_ST( 'k',	3,      862,     0 ), /*   861 trusted           */
  S_ST( 'e',	3,      430,     0 ), /*   862 trustedk          */
  S_ST( 't',	3,      431,   854 ), /*   863 t                 */
  S_ST( 'y',	3,      865,   863 ), /*   864 t                 */
  S_ST( 'p',	3,      432,     0 ), /*   865 ty                */
  S_ST( 'u',	3,      867,   838 ), /*   866                   */
  S_ST( 'n',	3,      873,     0 ), /*   867 u                 */
  S_ST( 'c',	3,      869,     0 ), /*   868 un                */
  S_ST( 'o',	3,      870,     0 ), /*   869 unc               */
  S_ST( 'n',	3,      871,     0 ), /*   870 unco              */
  S_ST( 'f',	3,      872,     0 ), /*   871 uncon             */
  S_ST( 'i',	3,      437,     0 ), /*   872 unconf            */
  S_ST( 'p',	3,      874,   868 ), /*   873 un                */
  S_ST( 'e',	3,      875,     0 ), /*   874 unp               */
  S_ST( 'e',	3,      438,     0 ), /*   875 unpe              */
  S_ST( '_',	3,      896,     0 ), /*   876 unpeer            */
  S_ST( 'c',	3,      878,     0 ), /*   877 unpeer_           */
  S_ST( 'r',	3,      879,     0 ), /*   878 unpeer_c          */
  S_ST( 'y',	3,      880,     0 ), /*   879 unpeer_cr         */
  S_ST( 'p',	3,      881,     0 ), /*   880 unpeer_cry        */
  S_ST( 't',	3,      882,     0 ), /*   881 unpeer_cryp       */
  S_ST( 'o',	3,      883,     0 ), /*   882 unpeer_crypt      */
  S_ST( '_',	3,      888,     0 ), /*   883 unpeer_crypto     */
  S_ST( 'e',	3,      885,     0 ), /*   884 unpeer_crypto_    */
  S_ST( 'a',	3,      886,     0 ), /*   885 unpeer_crypto_e   */
  S_ST( 'r',	3,      887,     0 ), /*   886 unpeer_crypto_ea  */
  S_ST( 'l',	3,      434,     0 ), /*   887 unpeer_crypto_ear */
  S_ST( 'n',	3,      889,   884 ), /*   888 unpeer_crypto_    */
  S_ST( 'a',	3,      890,     0 ), /*   889 unpeer_crypto_n   */
  S_ST( 'k',	3,      891,     0 ), /*   890 unpeer_crypto_na  */
  S_ST( '_',	3,      892,     0 ), /*   891 unpeer_crypto_nak */
  S_ST( 'e',	3,      893,     0 ), /*   892 unpeer_crypto_nak_ */
  S_ST( 'a',	3,      894,     0 ), /*   893 unpeer_crypto_nak_e */
  S_ST( 'r',	3,      895,     0 ), /*   894 unpeer_crypto_nak_ea */
  S_ST( 'l',	3,      435,     0 ), /*   895 unpeer_crypto_nak_ear */
  S_ST( 'd',	3,      897,   877 ), /*   896 unpeer_           */
  S_ST( 'i',	3,      898,     0 ), /*   897 unpeer_d          */
  S_ST( 'g',	3,      899,     0 ), /*   898 unpeer_di         */
  S_ST( 'e',	3,      900,     0 ), /*   899 unpeer_dig        */
  S_ST( 's',	3,      901,     0 ), /*   900 unpeer_dige       */
  S_ST( 't',	3,      902,     0 ), /*   901 unpeer_diges      */
  S_ST( '_',	3,      903,     0 ), /*   902 unpeer_digest     */
  S_ST( 'e',	3,      904,     0 ), /*   903 unpeer_digest_    */
  S_ST( 'a',	3,      905,     0 ), /*   904 unpeer_digest_e   */
  S_ST( 'r',	3,      906,     0 ), /*   905 unpeer_digest_ea  */
  S_ST( 'l',	3,      436,     0 ), /*   906 unpeer_digest_ear */
  S_ST( 'v',	3,      908,   866 ), /*   907                   */
  S_ST( 'e',	3,      909,     0 ), /*   908 v                 */
  S_ST( 'r',	3,      910,     0 ), /*   909 ve                */
  S_ST( 's',	3,      911,     0 ), /*   910 ver               */
  S_ST( 'i',	3,      912,     0 ), /*   911 vers              */
  S_ST( 'o',	3,      439,     0 ), /*   912 versi             */
  S_ST( 'w',	3,      920,   907 ), /*   913                   */
  S_ST( 'a',	3,      915,     0 ), /*   914 w                 */
  S_ST( 'n',	3,      916,     0 ), /*   915 wa                */
  S_ST( 'd',	3,      917,     0 ), /*   916 wan               */
  S_ST( 'e',	3,      453,     0 ), /*   917 wand              */
  S_ST( 'e',	3,      919,   914 ), /*   918 w                 */
  S_ST( 'e',	3,      441,     0 ), /*   919 we                */
  S_ST( 'i',	3,      921,   918 ), /*   920 w                 */
  S_ST( 'l',	3,      922,     0 ), /*   921 wi                */
  S_ST( 'd',	3,      923,     0 ), /*   922 wil               */
  S_ST( 'c',	3,      924,     0 ), /*   923 wild              */
  S_ST( 'a',	3,      925,     0 ), /*   924 wildc             */
  S_ST( 'r',	3,      442,     0 ), /*   925 wildca            */
  S_ST( 'x',	3,      927,   913 ), /*   926                   */
  S_ST( 'l',	3,      928,     0 ), /*   927 x                 */
  S_ST( 'e',	3,      929,     0 ), /*   928 xl                */
  S_ST( 'a',	3,      930,     0 ), /*   929 xle               */
  S_ST( 'v',	3,      443,     0 ), /*   930 xlea              */
  S_ST( 'y',	3,      932,   926 ), /*   931 [initial state]   */
  S_ST( 'e',	3,      933,     0 ), /*   932 y                 */
  S_ST( 'a',	3,      444,     0 )  /*   933 ye                */
};

