/*
 * ntp_keyword.h
 * 
 * NOTE: edit this file with caution, it is generated by keyword-gen.c
 *	 Generated 2020-01-11 06:37:02 UTC	  diff_ignore_line
 *
 */
#include "ntp_scanner.h"
#include "ntp_parser.h"

#define LOWEST_KEYWORD_ID 258

const char * const keyword_text[203] = {
	/* 0       258             T_Abbrev */	"abbrev",
	/* 1       259                T_Age */	"age",
	/* 2       260                T_All */	"all",
	/* 3       261              T_Allan */	"allan",
	/* 4       262           T_Allpeers */	"allpeers",
	/* 5       263               T_Auth */	"auth",
	/* 6       264            T_Autokey */	"autokey",
	/* 7       265            T_Automax */	"automax",
	/* 8       266            T_Average */	"average",
	/* 9       267           T_Basedate */	"basedate",
	/* 10      268            T_Bclient */	"bclient",
	/* 11      269        T_Bcpollbstep */	"bcpollbstep",
	/* 12      270             T_Beacon */	"beacon",
	/* 13      271          T_Broadcast */	"broadcast",
	/* 14      272    T_Broadcastclient */	"broadcastclient",
	/* 15      273     T_Broadcastdelay */	"broadcastdelay",
	/* 16      274              T_Burst */	"burst",
	/* 17      275          T_Calibrate */	"calibrate",
	/* 18      276            T_Ceiling */	"ceiling",
	/* 19      277          T_Checkhash */	"checkhash",
	/* 20      278         T_Clockstats */	"clockstats",
	/* 21      279             T_Cohort */	"cohort",
	/* 22      280         T_ControlKey */	"controlkey",
	/* 23      281             T_Crypto */	"crypto",
	/* 24      282        T_Cryptostats */	"cryptostats",
	/* 25      283                T_Ctl */	"ctl",
	/* 26      284                T_Day */	"day",
	/* 27      285            T_Default */	"default",
	/* 28      286             T_Digest */	"digest",
	/* 29      287            T_Disable */	"disable",
	/* 30      288            T_Discard */	"discard",
	/* 31      289         T_Dispersion */	"dispersion",
	/* 32      290             T_Double */	NULL,
	/* 33      291          T_Driftfile */	"driftfile",
	/* 34      292               T_Drop */	"drop",
	/* 35      293               T_Dscp */	"dscp",
	/* 36      294           T_Ellipsis */	"...",
	/* 37      295             T_Enable */	"enable",
	/* 38      296                T_End */	"end",
	/* 39      297              T_Epeer */	"epeer",
	/* 40      298              T_False */	NULL,
	/* 41      299               T_File */	"file",
	/* 42      300            T_Filegen */	"filegen",
	/* 43      301            T_Filenum */	"filenum",
	/* 44      302              T_Flag1 */	"flag1",
	/* 45      303              T_Flag2 */	"flag2",
	/* 46      304              T_Flag3 */	"flag3",
	/* 47      305              T_Flag4 */	"flag4",
	/* 48      306              T_Flake */	"flake",
	/* 49      307              T_Floor */	"floor",
	/* 50      308               T_Freq */	"freq",
	/* 51      309              T_Fudge */	"fudge",
	/* 52      310               T_Host */	"host",
	/* 53      311           T_Huffpuff */	"huffpuff",
	/* 54      312             T_Iburst */	"iburst",
	/* 55      313              T_Ident */	"ident",
	/* 56      314             T_Ignore */	"ignore",
	/* 57      315         T_Ignorehash */	"ignorehash",
	/* 58      316           T_Incalloc */	"incalloc",
	/* 59      317             T_Incmem */	"incmem",
	/* 60      318          T_Initalloc */	"initalloc",
	/* 61      319            T_Initmem */	"initmem",
	/* 62      320        T_Includefile */	"includefile",
	/* 63      321            T_Integer */	NULL,
	/* 64      322          T_Interface */	"interface",
	/* 65      323           T_Intrange */	NULL,
	/* 66      324                 T_Io */	"io",
	/* 67      325        T_Ippeerlimit */	"ippeerlimit",
	/* 68      326               T_Ipv4 */	"ipv4",
	/* 69      327          T_Ipv4_flag */	"-4",
	/* 70      328               T_Ipv6 */	"ipv6",
	/* 71      329          T_Ipv6_flag */	"-6",
	/* 72      330             T_Kernel */	"kernel",
	/* 73      331                T_Key */	"key",
	/* 74      332               T_Keys */	"keys",
	/* 75      333            T_Keysdir */	"keysdir",
	/* 76      334                T_Kod */	"kod",
	/* 77      335             T_Mssntp */	"mssntp",
	/* 78      336           T_Leapfile */	"leapfile",
	/* 79      337  T_Leapsmearinterval */	"leapsmearinterval",
	/* 80      338            T_Limited */	"limited",
	/* 81      339               T_Link */	"link",
	/* 82      340             T_Listen */	"listen",
	/* 83      341          T_Logconfig */	"logconfig",
	/* 84      342            T_Logfile */	"logfile",
	/* 85      343          T_Loopstats */	"loopstats",
	/* 86      344        T_Lowpriotrap */	"lowpriotrap",
	/* 87      345     T_Manycastclient */	"manycastclient",
	/* 88      346     T_Manycastserver */	"manycastserver",
	/* 89      347               T_Mask */	"mask",
	/* 90      348             T_Maxage */	"maxage",
	/* 91      349           T_Maxclock */	"maxclock",
	/* 92      350           T_Maxdepth */	"maxdepth",
	/* 93      351            T_Maxdist */	"maxdist",
	/* 94      352             T_Maxmem */	"maxmem",
	/* 95      353            T_Maxpoll */	"maxpoll",
	/* 96      354          T_Mdnstries */	"mdnstries",
	/* 97      355                T_Mem */	"mem",
	/* 98      356            T_Memlock */	"memlock",
	/* 99      357           T_Minclock */	"minclock",
	/* 100     358           T_Mindepth */	"mindepth",
	/* 101     359            T_Mindist */	"mindist",
	/* 102     360            T_Minimum */	"minimum",
	/* 103     361          T_Minjitter */	"minjitter",
	/* 104     362            T_Minpoll */	"minpoll",
	/* 105     363            T_Minsane */	"minsane",
	/* 106     364               T_Mode */	"mode",
	/* 107     365              T_Mode7 */	"mode7",
	/* 108     366            T_Monitor */	"monitor",
	/* 109     367              T_Month */	"month",
	/* 110     368                T_Mru */	"mru",
	/* 111     369    T_Multicastclient */	"multicastclient",
	/* 112     370                T_Nic */	"nic",
	/* 113     371             T_Nolink */	"nolink",
	/* 114     372           T_Nomodify */	"nomodify",
	/* 115     373          T_Nomrulist */	"nomrulist",
	/* 116     374               T_None */	"none",
	/* 117     375        T_Nonvolatile */	"nonvolatile",
	/* 118     376            T_Noepeer */	"noepeer",
	/* 119     377             T_Nopeer */	"nopeer",
	/* 120     378            T_Noquery */	"noquery",
	/* 121     379           T_Noselect */	"noselect",
	/* 122     380            T_Noserve */	"noserve",
	/* 123     381             T_Notrap */	"notrap",
	/* 124     382            T_Notrust */	"notrust",
	/* 125     383                T_Ntp */	"ntp",
	/* 126     384            T_Ntpport */	"ntpport",
	/* 127     385     T_NtpSignDsocket */	"ntpsigndsocket",
	/* 128     386             T_Orphan */	"orphan",
	/* 129     387         T_Orphanwait */	"orphanwait",
	/* 130     388          T_PCEdigest */	"peer_clear_digest_early",
	/* 131     389              T_Panic */	"panic",
	/* 132     390               T_Peer */	"peer",
	/* 133     391          T_Peerstats */	"peerstats",
	/* 134     392              T_Phone */	"phone",
	/* 135     393                T_Pid */	"pid",
	/* 136     394            T_Pidfile */	"pidfile",
	/* 137     395               T_Pool */	"pool",
	/* 138     396               T_Port */	"port",
	/* 139     397            T_Preempt */	"preempt",
	/* 140     398             T_Prefer */	"prefer",
	/* 141     399         T_Protostats */	"protostats",
	/* 142     400                 T_Pw */	"pw",
	/* 143     401           T_Randfile */	"randfile",
	/* 144     402           T_Rawstats */	"rawstats",
	/* 145     403              T_Refid */	"refid",
	/* 146     404         T_Requestkey */	"requestkey",
	/* 147     405              T_Reset */	"reset",
	/* 148     406           T_Restrict */	"restrict",
	/* 149     407             T_Revoke */	"revoke",
	/* 150     408             T_Rlimit */	"rlimit",
	/* 151     409      T_Saveconfigdir */	"saveconfigdir",
	/* 152     410             T_Server */	"server",
	/* 153     411             T_Setvar */	"setvar",
	/* 154     412             T_Source */	"source",
	/* 155     413          T_Stacksize */	"stacksize",
	/* 156     414         T_Statistics */	"statistics",
	/* 157     415              T_Stats */	"stats",
	/* 158     416           T_Statsdir */	"statsdir",
	/* 159     417               T_Step */	"step",
	/* 160     418           T_Stepback */	"stepback",
	/* 161     419            T_Stepfwd */	"stepfwd",
	/* 162     420            T_Stepout */	"stepout",
	/* 163     421            T_Stratum */	"stratum",
	/* 164     422             T_String */	NULL,
	/* 165     423                T_Sys */	"sys",
	/* 166     424           T_Sysstats */	"sysstats",
	/* 167     425               T_Tick */	"tick",
	/* 168     426              T_Time1 */	"time1",
	/* 169     427              T_Time2 */	"time2",
	/* 170     428              T_Timer */	"timer",
	/* 171     429        T_Timingstats */	"timingstats",
	/* 172     430             T_Tinker */	"tinker",
	/* 173     431                T_Tos */	"tos",
	/* 174     432               T_Trap */	"trap",
	/* 175     433               T_True */	"true",
	/* 176     434         T_Trustedkey */	"trustedkey",
	/* 177     435                T_Ttl */	"ttl",
	/* 178     436               T_Type */	"type",
	/* 179     437              T_U_int */	NULL,
	/* 180     438           T_UEcrypto */	"unpeer_crypto_early",
	/* 181     439        T_UEcryptonak */	"unpeer_crypto_nak_early",
	/* 182     440           T_UEdigest */	"unpeer_digest_early",
	/* 183     441           T_Unconfig */	"unconfig",
	/* 184     442             T_Unpeer */	"unpeer",
	/* 185     443            T_Version */	"version",
	/* 186     444    T_WanderThreshold */	NULL,
	/* 187     445               T_Week */	"week",
	/* 188     446           T_Wildcard */	"wildcard",
	/* 189     447             T_Xleave */	"xleave",
	/* 190     448               T_Year */	"year",
	/* 191     449               T_Flag */	NULL,
	/* 192     450                T_EOC */	NULL,
	/* 193     451           T_Simulate */	"simulate",
	/* 194     452         T_Beep_Delay */	"beep_delay",
	/* 195     453       T_Sim_Duration */	"simulation_duration",
	/* 196     454      T_Server_Offset */	"server_offset",
	/* 197     455           T_Duration */	"duration",
	/* 198     456        T_Freq_Offset */	"freq_offset",
	/* 199     457             T_Wander */	"wander",
	/* 200     458             T_Jitter */	"jitter",
	/* 201     459         T_Prop_Delay */	"prop_delay",
	/* 202     460         T_Proc_Delay */	"proc_delay"
};

#define SCANNER_INIT_S 958

const scan_state sst[961] = {
/*SS_T( ch,	f-by, match, other ),				 */
  0,				      /*     0                   */
  S_ST( '-',	3,      329,     0 ), /*     1                   */
  S_ST( '.',	3,        3,     1 ), /*     2                   */
  S_ST( '.',	3,      294,     0 ), /*     3 .                 */
  S_ST( 'a',	3,       23,     2 ), /*     4                   */
  S_ST( 'b',	3,        6,     0 ), /*     5 a                 */
  S_ST( 'b',	3,        7,     0 ), /*     6 ab                */
  S_ST( 'r',	3,        8,     0 ), /*     7 abb               */
  S_ST( 'e',	3,      258,     0 ), /*     8 abbr              */
  S_ST( 'g',	3,      259,     5 ), /*     9 a                 */
  S_ST( 'l',	3,      260,     9 ), /*    10 a                 */
  S_ST( 'a',	3,      261,     0 ), /*    11 all               */
  S_ST( 'p',	3,       13,    11 ), /*    12 all               */
  S_ST( 'e',	3,       14,     0 ), /*    13 allp              */
  S_ST( 'e',	3,       15,     0 ), /*    14 allpe             */
  S_ST( 'r',	3,      262,     0 ), /*    15 allpee            */
  S_ST( 'u',	3,       17,    10 ), /*    16 a                 */
  S_ST( 't',	3,       18,     0 ), /*    17 au                */
  S_ST( 'o',	3,       21,   263 ), /*    18 aut               */
  S_ST( 'k',	3,       20,     0 ), /*    19 auto              */
  S_ST( 'e',	3,      264,     0 ), /*    20 autok             */
  S_ST( 'm',	3,       22,    19 ), /*    21 auto              */
  S_ST( 'a',	3,      265,     0 ), /*    22 autom             */
  S_ST( 'v',	3,       24,    16 ), /*    23 a                 */
  S_ST( 'e',	3,       25,     0 ), /*    24 av                */
  S_ST( 'r',	3,       26,     0 ), /*    25 ave               */
  S_ST( 'a',	3,       27,     0 ), /*    26 aver              */
  S_ST( 'g',	3,      266,     0 ), /*    27 avera             */
  S_ST( 'b',	3,       75,     4 ), /*    28                   */
  S_ST( 'a',	3,       30,     0 ), /*    29 b                 */
  S_ST( 's',	3,       31,     0 ), /*    30 ba                */
  S_ST( 'e',	3,       32,     0 ), /*    31 bas               */
  S_ST( 'd',	3,       33,     0 ), /*    32 base              */
  S_ST( 'a',	3,       34,     0 ), /*    33 based             */
  S_ST( 't',	3,      267,     0 ), /*    34 baseda            */
  S_ST( 'c',	3,       40,    29 ), /*    35 b                 */
  S_ST( 'l',	3,       37,     0 ), /*    36 bc                */
  S_ST( 'i',	3,       38,     0 ), /*    37 bcl               */
  S_ST( 'e',	3,       39,     0 ), /*    38 bcli              */
  S_ST( 'n',	3,      268,     0 ), /*    39 bclie             */
  S_ST( 'p',	3,       41,    36 ), /*    40 bc                */
  S_ST( 'o',	3,       42,     0 ), /*    41 bcp               */
  S_ST( 'l',	3,       43,     0 ), /*    42 bcpo              */
  S_ST( 'l',	3,       44,     0 ), /*    43 bcpol             */
  S_ST( 'b',	3,       45,     0 ), /*    44 bcpoll            */
  S_ST( 's',	3,       46,     0 ), /*    45 bcpollb           */
  S_ST( 't',	3,       47,     0 ), /*    46 bcpollbs          */
  S_ST( 'e',	3,      269,     0 ), /*    47 bcpollbst         */
  S_ST( 'e',	3,       52,    35 ), /*    48 b                 */
  S_ST( 'a',	3,       50,     0 ), /*    49 be                */
  S_ST( 'c',	3,       51,     0 ), /*    50 bea               */
  S_ST( 'o',	3,      270,     0 ), /*    51 beac              */
  S_ST( 'e',	3,       53,    49 ), /*    52 be                */
  S_ST( 'p',	3,       54,     0 ), /*    53 bee               */
  S_ST( '_',	3,       55,     0 ), /*    54 beep              */
  S_ST( 'd',	3,       56,     0 ), /*    55 beep_             */
  S_ST( 'e',	3,       57,     0 ), /*    56 beep_d            */
  S_ST( 'l',	3,       58,     0 ), /*    57 beep_de           */
  S_ST( 'a',	3,      452,     0 ), /*    58 beep_del          */
  S_ST( 'r',	3,       60,    48 ), /*    59 b                 */
  S_ST( 'o',	3,       61,     0 ), /*    60 br                */
  S_ST( 'a',	3,       62,     0 ), /*    61 bro               */
  S_ST( 'd',	3,       63,     0 ), /*    62 broa              */
  S_ST( 'c',	3,       64,     0 ), /*    63 broad             */
  S_ST( 'a',	3,       65,     0 ), /*    64 broadc            */
  S_ST( 's',	3,      271,     0 ), /*    65 broadca           */
  S_ST( 'c',	3,       67,     0 ), /*    66 broadcast         */
  S_ST( 'l',	3,       68,     0 ), /*    67 broadcastc        */
  S_ST( 'i',	3,       69,     0 ), /*    68 broadcastcl       */
  S_ST( 'e',	3,       70,     0 ), /*    69 broadcastcli      */
  S_ST( 'n',	3,      272,     0 ), /*    70 broadcastclie     */
  S_ST( 'd',	3,       72,    66 ), /*    71 broadcast         */
  S_ST( 'e',	3,       73,     0 ), /*    72 broadcastd        */
  S_ST( 'l',	3,       74,     0 ), /*    73 broadcastde       */
  S_ST( 'a',	3,      273,     0 ), /*    74 broadcastdel      */
  S_ST( 'u',	3,       76,    59 ), /*    75 b                 */
  S_ST( 'r',	3,       77,     0 ), /*    76 bu                */
  S_ST( 's',	3,      274,     0 ), /*    77 bur               */
  S_ST( 'c',	3,      125,    28 ), /*    78                   */
  S_ST( 'a',	3,       80,     0 ), /*    79 c                 */
  S_ST( 'l',	3,       81,     0 ), /*    80 ca                */
  S_ST( 'i',	3,       82,     0 ), /*    81 cal               */
  S_ST( 'b',	3,       83,     0 ), /*    82 cali              */
  S_ST( 'r',	3,       84,     0 ), /*    83 calib             */
  S_ST( 'a',	3,       85,     0 ), /*    84 calibr            */
  S_ST( 't',	3,      275,     0 ), /*    85 calibra           */
  S_ST( 'e',	3,       87,    79 ), /*    86 c                 */
  S_ST( 'i',	3,       88,     0 ), /*    87 ce                */
  S_ST( 'l',	3,       89,     0 ), /*    88 cei               */
  S_ST( 'i',	3,       90,     0 ), /*    89 ceil              */
  S_ST( 'n',	3,      276,     0 ), /*    90 ceili             */
  S_ST( 'h',	3,       92,    86 ), /*    91 c                 */
  S_ST( 'e',	3,       93,     0 ), /*    92 ch                */
  S_ST( 'c',	3,       94,     0 ), /*    93 che               */
  S_ST( 'k',	3,       95,     0 ), /*    94 chec              */
  S_ST( 'h',	3,       96,     0 ), /*    95 check             */
  S_ST( 'a',	3,       97,     0 ), /*    96 checkh            */
  S_ST( 's',	3,      277,     0 ), /*    97 checkha           */
  S_ST( 'l',	3,       99,    91 ), /*    98 c                 */
  S_ST( 'o',	3,      100,     0 ), /*    99 cl                */
  S_ST( 'c',	3,      101,     0 ), /*   100 clo               */
  S_ST( 'k',	3,      102,     0 ), /*   101 cloc              */
  S_ST( 's',	3,      103,     0 ), /*   102 clock             */
  S_ST( 't',	3,      104,     0 ), /*   103 clocks            */
  S_ST( 'a',	3,      105,     0 ), /*   104 clockst           */
  S_ST( 't',	3,      278,     0 ), /*   105 clocksta          */
  S_ST( 'o',	3,      110,    98 ), /*   106 c                 */
  S_ST( 'h',	3,      108,     0 ), /*   107 co                */
  S_ST( 'o',	3,      109,     0 ), /*   108 coh               */
  S_ST( 'r',	3,      279,     0 ), /*   109 coho              */
  S_ST( 'n',	3,      111,   107 ), /*   110 co                */
  S_ST( 't',	3,      112,     0 ), /*   111 con               */
  S_ST( 'r',	3,      113,     0 ), /*   112 cont              */
  S_ST( 'o',	3,      114,     0 ), /*   113 contr             */
  S_ST( 'l',	3,      115,     0 ), /*   114 contro            */
  S_ST( 'k',	3,      116,     0 ), /*   115 control           */
  S_ST( 'e',	3,      280,     0 ), /*   116 controlk          */
  S_ST( 'r',	3,      118,   106 ), /*   117 c                 */
  S_ST( 'y',	3,      119,     0 ), /*   118 cr                */
  S_ST( 'p',	3,      120,     0 ), /*   119 cry               */
  S_ST( 't',	3,      281,     0 ), /*   120 cryp              */
  S_ST( 's',	3,      122,     0 ), /*   121 crypto            */
  S_ST( 't',	3,      123,     0 ), /*   122 cryptos           */
  S_ST( 'a',	3,      124,     0 ), /*   123 cryptost          */
  S_ST( 't',	3,      282,     0 ), /*   124 cryptosta         */
  S_ST( 't',	3,      283,   117 ), /*   125 c                 */
  S_ST( 'd',	3,      160,    78 ), /*   126                   */
  S_ST( 'a',	3,      284,     0 ), /*   127 d                 */
  S_ST( 'e',	3,      129,   127 ), /*   128 d                 */
  S_ST( 'f',	3,      130,     0 ), /*   129 de                */
  S_ST( 'a',	3,      131,     0 ), /*   130 def               */
  S_ST( 'u',	3,      132,     0 ), /*   131 defa              */
  S_ST( 'l',	3,      285,     0 ), /*   132 defau             */
  S_ST( 'i',	3,      137,   128 ), /*   133 d                 */
  S_ST( 'g',	3,      135,     0 ), /*   134 di                */
  S_ST( 'e',	3,      136,     0 ), /*   135 dig               */
  S_ST( 's',	3,      286,     0 ), /*   136 dige              */
  S_ST( 's',	3,      144,   134 ), /*   137 di                */
  S_ST( 'a',	3,      139,     0 ), /*   138 dis               */
  S_ST( 'b',	3,      140,     0 ), /*   139 disa              */
  S_ST( 'l',	3,      287,     0 ), /*   140 disab             */
  S_ST( 'c',	3,      142,   138 ), /*   141 dis               */
  S_ST( 'a',	3,      143,     0 ), /*   142 disc              */
  S_ST( 'r',	3,      288,     0 ), /*   143 disca             */
  S_ST( 'p',	3,      145,   141 ), /*   144 dis               */
  S_ST( 'e',	3,      146,     0 ), /*   145 disp              */
  S_ST( 'r',	3,      147,     0 ), /*   146 dispe             */
  S_ST( 's',	3,      148,     0 ), /*   147 disper            */
  S_ST( 'i',	3,      149,     0 ), /*   148 dispers           */
  S_ST( 'o',	3,      289,     0 ), /*   149 dispersi          */
  S_ST( 'r',	3,      157,   133 ), /*   150 d                 */
  S_ST( 'i',	3,      152,     0 ), /*   151 dr                */
  S_ST( 'f',	3,      153,     0 ), /*   152 dri               */
  S_ST( 't',	3,      154,     0 ), /*   153 drif              */
  S_ST( 'f',	3,      155,     0 ), /*   154 drift             */
  S_ST( 'i',	3,      156,     0 ), /*   155 driftf            */
  S_ST( 'l',	3,      291,     0 ), /*   156 driftfi           */
  S_ST( 'o',	3,      292,   151 ), /*   157 dr                */
  S_ST( 's',	3,      159,   150 ), /*   158 d                 */
  S_ST( 'c',	3,      293,     0 ), /*   159 ds                */
  S_ST( 'u',	3,      161,   158 ), /*   160 d                 */
  S_ST( 'r',	3,      162,     0 ), /*   161 du                */
  S_ST( 'a',	3,      163,     0 ), /*   162 dur               */
  S_ST( 't',	3,      164,     0 ), /*   163 dura              */
  S_ST( 'i',	3,      165,     0 ), /*   164 durat             */
  S_ST( 'o',	3,      455,     0 ), /*   165 durati            */
  S_ST( 'e',	3,      171,   126 ), /*   166                   */
  S_ST( 'n',	3,      296,     0 ), /*   167 e                 */
  S_ST( 'a',	3,      169,     0 ), /*   168 en                */
  S_ST( 'b',	3,      170,     0 ), /*   169 ena               */
  S_ST( 'l',	3,      295,     0 ), /*   170 enab              */
  S_ST( 'p',	3,      172,   167 ), /*   171 e                 */
  S_ST( 'e',	3,      173,     0 ), /*   172 ep                */
  S_ST( 'e',	3,      297,     0 ), /*   173 epe               */
  S_ST( 'f',	3,      195,   166 ), /*   174                   */
  S_ST( 'i',	3,      176,     0 ), /*   175 f                 */
  S_ST( 'l',	3,      299,     0 ), /*   176 fi                */
  S_ST( 'g',	3,      178,     0 ), /*   177 file              */
  S_ST( 'e',	3,      300,     0 ), /*   178 fileg             */
  S_ST( 'n',	3,      180,   177 ), /*   179 file              */
  S_ST( 'u',	3,      301,     0 ), /*   180 filen             */
  S_ST( 'l',	3,      185,   175 ), /*   181 f                 */
  S_ST( 'a',	3,      184,     0 ), /*   182 fl                */
  S_ST( 'g',	3,      305,     0 ), /*   183 fla               */
  S_ST( 'k',	3,      306,   183 ), /*   184 fla               */
  S_ST( 'o',	3,      186,   182 ), /*   185 fl                */
  S_ST( 'o',	3,      307,     0 ), /*   186 flo               */
  S_ST( 'r',	3,      188,   181 ), /*   187 f                 */
  S_ST( 'e',	3,      308,     0 ), /*   188 fr                */
  S_ST( '_',	3,      190,     0 ), /*   189 freq              */
  S_ST( 'o',	3,      191,     0 ), /*   190 freq_             */
  S_ST( 'f',	3,      192,     0 ), /*   191 freq_o            */
  S_ST( 'f',	3,      193,     0 ), /*   192 freq_of           */
  S_ST( 's',	3,      194,     0 ), /*   193 freq_off          */
  S_ST( 'e',	3,      456,     0 ), /*   194 freq_offs         */
  S_ST( 'u',	3,      196,   187 ), /*   195 f                 */
  S_ST( 'd',	3,      197,     0 ), /*   196 fu                */
  S_ST( 'g',	3,      309,     0 ), /*   197 fud               */
  S_ST( 'h',	3,      201,   174 ), /*   198                   */
  S_ST( 'o',	3,      200,     0 ), /*   199 h                 */
  S_ST( 's',	3,      310,     0 ), /*   200 ho                */
  S_ST( 'u',	3,      202,   199 ), /*   201 h                 */
  S_ST( 'f',	3,      203,     0 ), /*   202 hu                */
  S_ST( 'f',	3,      204,     0 ), /*   203 huf               */
  S_ST( 'p',	3,      205,     0 ), /*   204 huff              */
  S_ST( 'u',	3,      206,     0 ), /*   205 huffp             */
  S_ST( 'f',	3,      311,     0 ), /*   206 huffpu            */
  S_ST( 'i',	3,      251,   198 ), /*   207                   */
  S_ST( 'b',	3,      209,     0 ), /*   208 i                 */
  S_ST( 'u',	3,      210,     0 ), /*   209 ib                */
  S_ST( 'r',	3,      211,     0 ), /*   210 ibu               */
  S_ST( 's',	3,      312,     0 ), /*   211 ibur              */
  S_ST( 'd',	3,      213,   208 ), /*   212 i                 */
  S_ST( 'e',	3,      214,     0 ), /*   213 id                */
  S_ST( 'n',	3,      313,     0 ), /*   214 ide               */
  S_ST( 'g',	3,      216,   212 ), /*   215 i                 */
  S_ST( 'n',	3,      217,     0 ), /*   216 ig                */
  S_ST( 'o',	3,      218,     0 ), /*   217 ign               */
  S_ST( 'r',	3,      314,     0 ), /*   218 igno              */
  S_ST( 'h',	3,      220,     0 ), /*   219 ignore            */
  S_ST( 'a',	3,      221,     0 ), /*   220 ignoreh           */
  S_ST( 's',	3,      315,     0 ), /*   221 ignoreha          */
  S_ST( 'n',	3,      245,   215 ), /*   222 i                 */
  S_ST( 'c',	3,      235,     0 ), /*   223 in                */
  S_ST( 'a',	3,      225,     0 ), /*   224 inc               */
  S_ST( 'l',	3,      226,     0 ), /*   225 inca              */
  S_ST( 'l',	3,      227,     0 ), /*   226 incal             */
  S_ST( 'o',	3,      316,     0 ), /*   227 incall            */
  S_ST( 'l',	3,      229,   224 ), /*   228 inc               */
  S_ST( 'u',	3,      230,     0 ), /*   229 incl              */
  S_ST( 'd',	3,      231,     0 ), /*   230 inclu             */
  S_ST( 'e',	3,      232,     0 ), /*   231 includ            */
  S_ST( 'f',	3,      233,     0 ), /*   232 include           */
  S_ST( 'i',	3,      234,     0 ), /*   233 includef          */
  S_ST( 'l',	3,      320,     0 ), /*   234 includefi         */
  S_ST( 'm',	3,      236,   228 ), /*   235 inc               */
  S_ST( 'e',	3,      317,     0 ), /*   236 incm              */
  S_ST( 'i',	3,      238,   223 ), /*   237 in                */
  S_ST( 't',	3,      243,     0 ), /*   238 ini               */
  S_ST( 'a',	3,      240,     0 ), /*   239 init              */
  S_ST( 'l',	3,      241,     0 ), /*   240 inita             */
  S_ST( 'l',	3,      242,     0 ), /*   241 inital            */
  S_ST( 'o',	3,      318,     0 ), /*   242 initall           */
  S_ST( 'm',	3,      244,   239 ), /*   243 init              */
  S_ST( 'e',	3,      319,     0 ), /*   244 initm             */
  S_ST( 't',	3,      246,   237 ), /*   245 in                */
  S_ST( 'e',	3,      247,     0 ), /*   246 int               */
  S_ST( 'r',	3,      248,     0 ), /*   247 inte              */
  S_ST( 'f',	3,      249,     0 ), /*   248 inter             */
  S_ST( 'a',	3,      250,     0 ), /*   249 interf            */
  S_ST( 'c',	3,      322,     0 ), /*   250 interfa           */
  S_ST( 'p',	3,      321,   324 ), /*   251 i                 */
  S_ST( 'p',	3,      253,     0 ), /*   252 ip                */
  S_ST( 'e',	3,      254,     0 ), /*   253 ipp               */
  S_ST( 'e',	3,      255,     0 ), /*   254 ippe              */
  S_ST( 'r',	3,      256,     0 ), /*   255 ippee             */
  S_ST( 'l',	3,      257,     0 ), /*   256 ippeer            */
  S_ST( 'i',	3,      290,     0 ), /*   257 ippeerl           */
  S_ST( 'v',	1,        0,     0 ), /*   258 T_Abbrev          */
  S_ST( 'e',	0,        0,     0 ), /*   259 T_Age             */
  S_ST( 'l',	0,       12,     0 ), /*   260 T_All             */
  S_ST( 'n',	0,        0,     0 ), /*   261 T_Allan           */
  S_ST( 's',	0,        0,     0 ), /*   262 T_Allpeers        */
  S_ST( 'h',	0,        0,     0 ), /*   263 T_Auth            */
  S_ST( 'y',	0,        0,     0 ), /*   264 T_Autokey         */
  S_ST( 'x',	0,        0,     0 ), /*   265 T_Automax         */
  S_ST( 'e',	0,        0,     0 ), /*   266 T_Average         */
  S_ST( 'e',	1,        0,     0 ), /*   267 T_Basedate        */
  S_ST( 't',	0,        0,     0 ), /*   268 T_Bclient         */
  S_ST( 'p',	0,        0,     0 ), /*   269 T_Bcpollbstep     */
  S_ST( 'n',	0,        0,     0 ), /*   270 T_Beacon          */
  S_ST( 't',	1,       71,     0 ), /*   271 T_Broadcast       */
  S_ST( 't',	0,        0,     0 ), /*   272 T_Broadcastclient */
  S_ST( 'y',	0,        0,     0 ), /*   273 T_Broadcastdelay  */
  S_ST( 't',	0,        0,     0 ), /*   274 T_Burst           */
  S_ST( 'e',	0,        0,     0 ), /*   275 T_Calibrate       */
  S_ST( 'g',	0,        0,     0 ), /*   276 T_Ceiling         */
  S_ST( 'h',	0,        0,     0 ), /*   277 T_Checkhash       */
  S_ST( 's',	0,        0,     0 ), /*   278 T_Clockstats      */
  S_ST( 't',	0,        0,     0 ), /*   279 T_Cohort          */
  S_ST( 'y',	0,        0,     0 ), /*   280 T_ControlKey      */
  S_ST( 'o',	0,      121,     0 ), /*   281 T_Crypto          */
  S_ST( 's',	0,        0,     0 ), /*   282 T_Cryptostats     */
  S_ST( 'l',	0,        0,     0 ), /*   283 T_Ctl             */
  S_ST( 'y',	0,        0,     0 ), /*   284 T_Day             */
  S_ST( 't',	0,        0,     0 ), /*   285 T_Default         */
  S_ST( 't',	1,        0,     0 ), /*   286 T_Digest          */
  S_ST( 'e',	0,        0,     0 ), /*   287 T_Disable         */
  S_ST( 'd',	0,        0,     0 ), /*   288 T_Discard         */
  S_ST( 'n',	0,        0,     0 ), /*   289 T_Dispersion      */
  S_ST( 'm',	3,      298,     0 ), /*   290 ippeerli          */
  S_ST( 'e',	1,        0,     0 ), /*   291 T_Driftfile       */
  S_ST( 'p',	0,        0,     0 ), /*   292 T_Drop            */
  S_ST( 'p',	0,        0,     0 ), /*   293 T_Dscp            */
  S_ST( '.',	0,        0,     0 ), /*   294 T_Ellipsis        */
  S_ST( 'e',	0,        0,     0 ), /*   295 T_Enable          */
  S_ST( 'd',	0,        0,   168 ), /*   296 T_End             */
  S_ST( 'r',	0,        0,     0 ), /*   297 T_Epeer           */
  S_ST( 'i',	3,      325,     0 ), /*   298 ippeerlim         */
  S_ST( 'e',	1,      179,     0 ), /*   299 T_File            */
  S_ST( 'n',	0,        0,     0 ), /*   300 T_Filegen         */
  S_ST( 'm',	0,        0,     0 ), /*   301 T_Filenum         */
  S_ST( '1',	0,        0,     0 ), /*   302 T_Flag1           */
  S_ST( '2',	0,        0,   302 ), /*   303 T_Flag2           */
  S_ST( '3',	0,        0,   303 ), /*   304 T_Flag3           */
  S_ST( '4',	0,        0,   304 ), /*   305 T_Flag4           */
  S_ST( 'e',	0,        0,     0 ), /*   306 T_Flake           */
  S_ST( 'r',	0,        0,     0 ), /*   307 T_Floor           */
  S_ST( 'q',	0,      189,     0 ), /*   308 T_Freq            */
  S_ST( 'e',	1,        0,     0 ), /*   309 T_Fudge           */
  S_ST( 't',	1,        0,     0 ), /*   310 T_Host            */
  S_ST( 'f',	0,        0,     0 ), /*   311 T_Huffpuff        */
  S_ST( 't',	0,        0,     0 ), /*   312 T_Iburst          */
  S_ST( 't',	1,        0,     0 ), /*   313 T_Ident           */
  S_ST( 'e',	0,      219,     0 ), /*   314 T_Ignore          */
  S_ST( 'h',	0,        0,     0 ), /*   315 T_Ignorehash      */
  S_ST( 'c',	0,        0,     0 ), /*   316 T_Incalloc        */
  S_ST( 'm',	0,        0,     0 ), /*   317 T_Incmem          */
  S_ST( 'c',	0,        0,     0 ), /*   318 T_Initalloc       */
  S_ST( 'm',	0,        0,     0 ), /*   319 T_Initmem         */
  S_ST( 'e',	1,        0,     0 ), /*   320 T_Includefile     */
  S_ST( 'v',	3,      328,   252 ), /*   321 ip                */
  S_ST( 'e',	0,        0,     0 ), /*   322 T_Interface       */
  S_ST( 'j',	3,      422,   207 ), /*   323                   */
  S_ST( 'o',	0,        0,   222 ), /*   324 T_Io              */
  S_ST( 't',	0,        0,     0 ), /*   325 T_Ippeerlimit     */
  S_ST( '4',	0,        0,     0 ), /*   326 T_Ipv4            */
  S_ST( '4',	0,        0,     0 ), /*   327 T_Ipv4_flag       */
  S_ST( '6',	0,        0,   326 ), /*   328 T_Ipv6            */
  S_ST( '6',	0,        0,   327 ), /*   329 T_Ipv6_flag       */
  S_ST( 'l',	0,        0,     0 ), /*   330 T_Kernel          */
  S_ST( 'y',	0,      332,   462 ), /*   331 T_Key             */
  S_ST( 's',	1,      465,     0 ), /*   332 T_Keys            */
  S_ST( 'r',	1,        0,     0 ), /*   333 T_Keysdir         */
  S_ST( 'd',	0,        0,     0 ), /*   334 T_Kod             */
  S_ST( 'p',	0,        0,     0 ), /*   335 T_Mssntp          */
  S_ST( 'e',	1,        0,     0 ), /*   336 T_Leapfile        */
  S_ST( 'l',	0,        0,     0 ), /*   337 T_Leapsmearinterval */
  S_ST( 'd',	0,        0,     0 ), /*   338 T_Limited         */
  S_ST( 'k',	0,        0,     0 ), /*   339 T_Link            */
  S_ST( 'n',	0,        0,     0 ), /*   340 T_Listen          */
  S_ST( 'g',	2,        0,     0 ), /*   341 T_Logconfig       */
  S_ST( 'e',	1,        0,     0 ), /*   342 T_Logfile         */
  S_ST( 's',	0,        0,     0 ), /*   343 T_Loopstats       */
  S_ST( 'p',	0,        0,     0 ), /*   344 T_Lowpriotrap     */
  S_ST( 't',	1,        0,     0 ), /*   345 T_Manycastclient  */
  S_ST( 'r',	2,        0,     0 ), /*   346 T_Manycastserver  */
  S_ST( 'k',	0,        0,     0 ), /*   347 T_Mask            */
  S_ST( 'e',	0,        0,     0 ), /*   348 T_Maxage          */
  S_ST( 'k',	0,        0,     0 ), /*   349 T_Maxclock        */
  S_ST( 'h',	0,        0,     0 ), /*   350 T_Maxdepth        */
  S_ST( 't',	0,        0,     0 ), /*   351 T_Maxdist         */
  S_ST( 'm',	0,        0,     0 ), /*   352 T_Maxmem          */
  S_ST( 'l',	0,        0,     0 ), /*   353 T_Maxpoll         */
  S_ST( 's',	0,        0,     0 ), /*   354 T_Mdnstries       */
  S_ST( 'm',	0,      565,     0 ), /*   355 T_Mem             */
  S_ST( 'k',	0,        0,     0 ), /*   356 T_Memlock         */
  S_ST( 'k',	0,        0,     0 ), /*   357 T_Minclock        */
  S_ST( 'h',	0,        0,     0 ), /*   358 T_Mindepth        */
  S_ST( 't',	0,        0,     0 ), /*   359 T_Mindist         */
  S_ST( 'm',	0,        0,     0 ), /*   360 T_Minimum         */
  S_ST( 'r',	0,        0,     0 ), /*   361 T_Minjitter       */
  S_ST( 'l',	0,        0,     0 ), /*   362 T_Minpoll         */
  S_ST( 'e',	0,        0,     0 ), /*   363 T_Minsane         */
  S_ST( 'e',	0,      365,     0 ), /*   364 T_Mode            */
  S_ST( '7',	0,        0,     0 ), /*   365 T_Mode7           */
  S_ST( 'r',	0,        0,     0 ), /*   366 T_Monitor         */
  S_ST( 'h',	0,        0,     0 ), /*   367 T_Month           */
  S_ST( 'u',	0,        0,     0 ), /*   368 T_Mru             */
  S_ST( 't',	2,        0,     0 ), /*   369 T_Multicastclient */
  S_ST( 'c',	0,        0,     0 ), /*   370 T_Nic             */
  S_ST( 'k',	0,        0,     0 ), /*   371 T_Nolink          */
  S_ST( 'y',	0,        0,     0 ), /*   372 T_Nomodify        */
  S_ST( 't',	0,        0,     0 ), /*   373 T_Nomrulist       */
  S_ST( 'e',	0,        0,     0 ), /*   374 T_None            */
  S_ST( 'e',	0,        0,     0 ), /*   375 T_Nonvolatile     */
  S_ST( 'r',	0,        0,     0 ), /*   376 T_Noepeer         */
  S_ST( 'r',	0,        0,     0 ), /*   377 T_Nopeer          */
  S_ST( 'y',	0,        0,     0 ), /*   378 T_Noquery         */
  S_ST( 't',	0,        0,     0 ), /*   379 T_Noselect        */
  S_ST( 'e',	0,        0,     0 ), /*   380 T_Noserve         */
  S_ST( 'p',	0,        0,     0 ), /*   381 T_Notrap          */
  S_ST( 't',	0,        0,     0 ), /*   382 T_Notrust         */
  S_ST( 'p',	0,      670,     0 ), /*   383 T_Ntp             */
  S_ST( 't',	0,        0,     0 ), /*   384 T_Ntpport         */
  S_ST( 't',	1,        0,     0 ), /*   385 T_NtpSignDsocket  */
  S_ST( 'n',	0,      685,     0 ), /*   386 T_Orphan          */
  S_ST( 't',	0,        0,     0 ), /*   387 T_Orphanwait      */
  S_ST( 'y',	0,        0,     0 ), /*   388 T_PCEdigest       */
  S_ST( 'c',	0,        0,     0 ), /*   389 T_Panic           */
  S_ST( 'r',	1,      712,     0 ), /*   390 T_Peer            */
  S_ST( 's',	0,        0,     0 ), /*   391 T_Peerstats       */
  S_ST( 'e',	2,        0,     0 ), /*   392 T_Phone           */
  S_ST( 'd',	0,      720,     0 ), /*   393 T_Pid             */
  S_ST( 'e',	1,        0,     0 ), /*   394 T_Pidfile         */
  S_ST( 'l',	1,        0,     0 ), /*   395 T_Pool            */
  S_ST( 't',	0,        0,     0 ), /*   396 T_Port            */
  S_ST( 't',	0,        0,     0 ), /*   397 T_Preempt         */
  S_ST( 'r',	0,        0,     0 ), /*   398 T_Prefer          */
  S_ST( 's',	0,        0,     0 ), /*   399 T_Protostats      */
  S_ST( 'w',	1,        0,   726 ), /*   400 T_Pw              */
  S_ST( 'e',	1,        0,     0 ), /*   401 T_Randfile        */
  S_ST( 's',	0,        0,     0 ), /*   402 T_Rawstats        */
  S_ST( 'd',	1,        0,     0 ), /*   403 T_Refid           */
  S_ST( 'y',	0,        0,     0 ), /*   404 T_Requestkey      */
  S_ST( 't',	0,        0,     0 ), /*   405 T_Reset           */
  S_ST( 't',	0,        0,     0 ), /*   406 T_Restrict        */
  S_ST( 'e',	0,        0,     0 ), /*   407 T_Revoke          */
  S_ST( 't',	0,        0,     0 ), /*   408 T_Rlimit          */
  S_ST( 'r',	1,        0,     0 ), /*   409 T_Saveconfigdir   */
  S_ST( 'r',	1,      803,     0 ), /*   410 T_Server          */
  S_ST( 'r',	1,        0,     0 ), /*   411 T_Setvar          */
  S_ST( 'e',	0,        0,     0 ), /*   412 T_Source          */
  S_ST( 'e',	0,        0,     0 ), /*   413 T_Stacksize       */
  S_ST( 's',	0,        0,     0 ), /*   414 T_Statistics      */
  S_ST( 's',	0,      846,   841 ), /*   415 T_Stats           */
  S_ST( 'r',	1,        0,     0 ), /*   416 T_Statsdir        */
  S_ST( 'p',	0,      854,     0 ), /*   417 T_Step            */
  S_ST( 'k',	0,        0,     0 ), /*   418 T_Stepback        */
  S_ST( 'd',	0,        0,     0 ), /*   419 T_Stepfwd         */
  S_ST( 't',	0,        0,     0 ), /*   420 T_Stepout         */
  S_ST( 'm',	0,        0,     0 ), /*   421 T_Stratum         */
  S_ST( 'i',	3,      437,     0 ), /*   422 j                 */
  S_ST( 's',	0,      861,     0 ), /*   423 T_Sys             */
  S_ST( 's',	0,        0,     0 ), /*   424 T_Sysstats        */
  S_ST( 'k',	0,        0,     0 ), /*   425 T_Tick            */
  S_ST( '1',	0,        0,     0 ), /*   426 T_Time1           */
  S_ST( '2',	0,        0,   426 ), /*   427 T_Time2           */
  S_ST( 'r',	0,        0,   427 ), /*   428 T_Timer           */
  S_ST( 's',	0,        0,     0 ), /*   429 T_Timingstats     */
  S_ST( 'r',	0,        0,     0 ), /*   430 T_Tinker          */
  S_ST( 's',	0,        0,     0 ), /*   431 T_Tos             */
  S_ST( 'p',	1,        0,     0 ), /*   432 T_Trap            */
  S_ST( 'e',	0,        0,     0 ), /*   433 T_True            */
  S_ST( 'y',	0,        0,     0 ), /*   434 T_Trustedkey      */
  S_ST( 'l',	0,        0,     0 ), /*   435 T_Ttl             */
  S_ST( 'e',	0,        0,     0 ), /*   436 T_Type            */
  S_ST( 't',	3,      444,     0 ), /*   437 ji                */
  S_ST( 'y',	0,        0,     0 ), /*   438 T_UEcrypto        */
  S_ST( 'y',	0,        0,     0 ), /*   439 T_UEcryptonak     */
  S_ST( 'y',	0,        0,     0 ), /*   440 T_UEdigest        */
  S_ST( 'g',	1,        0,     0 ), /*   441 T_Unconfig        */
  S_ST( 'r',	1,      903,     0 ), /*   442 T_Unpeer          */
  S_ST( 'n',	0,        0,     0 ), /*   443 T_Version         */
  S_ST( 't',	3,      449,     0 ), /*   444 jit               */
  S_ST( 'k',	0,        0,     0 ), /*   445 T_Week            */
  S_ST( 'd',	0,        0,     0 ), /*   446 T_Wildcard        */
  S_ST( 'e',	0,        0,     0 ), /*   447 T_Xleave          */
  S_ST( 'r',	0,        0,     0 ), /*   448 T_Year            */
  S_ST( 'e',	3,      458,     0 ), /*   449 jitt              */
  S_ST( 'k',	3,      467,   323 ), /*   450                   */
  S_ST( 'e',	0,        0,     0 ), /*   451 T_Simulate        */
  S_ST( 'y',	0,        0,     0 ), /*   452 T_Beep_Delay      */
  S_ST( 'n',	0,        0,     0 ), /*   453 T_Sim_Duration    */
  S_ST( 't',	0,        0,     0 ), /*   454 T_Server_Offset   */
  S_ST( 'n',	0,        0,     0 ), /*   455 T_Duration        */
  S_ST( 't',	0,        0,     0 ), /*   456 T_Freq_Offset     */
  S_ST( 'r',	0,        0,     0 ), /*   457 T_Wander          */
  S_ST( 'r',	0,        0,     0 ), /*   458 T_Jitter          */
  S_ST( 'y',	0,        0,     0 ), /*   459 T_Prop_Delay      */
  S_ST( 'y',	0,        0,     0 ), /*   460 T_Proc_Delay      */
  S_ST( 'e',	3,      331,     0 ), /*   461 k                 */
  S_ST( 'r',	3,      463,     0 ), /*   462 ke                */
  S_ST( 'n',	3,      464,     0 ), /*   463 ker               */
  S_ST( 'e',	3,      330,     0 ), /*   464 kern              */
  S_ST( 'd',	3,      466,     0 ), /*   465 keys              */
  S_ST( 'i',	3,      333,     0 ), /*   466 keysd             */
  S_ST( 'o',	3,      334,   461 ), /*   467 k                 */
  S_ST( 'l',	3,      496,   450 ), /*   468                   */
  S_ST( 'e',	3,      470,     0 ), /*   469 l                 */
  S_ST( 'a',	3,      471,     0 ), /*   470 le                */
  S_ST( 'p',	3,      475,     0 ), /*   471 lea               */
  S_ST( 'f',	3,      473,     0 ), /*   472 leap              */
  S_ST( 'i',	3,      474,     0 ), /*   473 leapf             */
  S_ST( 'l',	3,      336,     0 ), /*   474 leapfi            */
  S_ST( 's',	3,      476,   472 ), /*   475 leap              */
  S_ST( 'm',	3,      477,     0 ), /*   476 leaps             */
  S_ST( 'e',	3,      478,     0 ), /*   477 leapsm            */
  S_ST( 'a',	3,      479,     0 ), /*   478 leapsme           */
  S_ST( 'r',	3,      480,     0 ), /*   479 leapsmea          */
  S_ST( 'i',	3,      481,     0 ), /*   480 leapsmear         */
  S_ST( 'n',	3,      482,     0 ), /*   481 leapsmeari        */
  S_ST( 't',	3,      483,     0 ), /*   482 leapsmearin       */
  S_ST( 'e',	3,      484,     0 ), /*   483 leapsmearint      */
  S_ST( 'r',	3,      485,     0 ), /*   484 leapsmearinte     */
  S_ST( 'v',	3,      486,     0 ), /*   485 leapsmearinter    */
  S_ST( 'a',	3,      337,     0 ), /*   486 leapsmearinterv   */
  S_ST( 'i',	3,      493,   469 ), /*   487 l                 */
  S_ST( 'm',	3,      489,     0 ), /*   488 li                */
  S_ST( 'i',	3,      490,     0 ), /*   489 lim               */
  S_ST( 't',	3,      491,     0 ), /*   490 limi              */
  S_ST( 'e',	3,      338,     0 ), /*   491 limit             */
  S_ST( 'n',	3,      339,   488 ), /*   492 li                */
  S_ST( 's',	3,      494,   492 ), /*   493 li                */
  S_ST( 't',	3,      495,     0 ), /*   494 lis               */
  S_ST( 'e',	3,      340,     0 ), /*   495 list              */
  S_ST( 'o',	3,      512,   487 ), /*   496 l                 */
  S_ST( 'g',	3,      503,     0 ), /*   497 lo                */
  S_ST( 'c',	3,      499,     0 ), /*   498 log               */
  S_ST( 'o',	3,      500,     0 ), /*   499 logc              */
  S_ST( 'n',	3,      501,     0 ), /*   500 logco             */
  S_ST( 'f',	3,      502,     0 ), /*   501 logcon            */
  S_ST( 'i',	3,      341,     0 ), /*   502 logconf           */
  S_ST( 'f',	3,      504,   498 ), /*   503 log               */
  S_ST( 'i',	3,      505,     0 ), /*   504 logf              */
  S_ST( 'l',	3,      342,     0 ), /*   505 logfi             */
  S_ST( 'o',	3,      507,   497 ), /*   506 lo                */
  S_ST( 'p',	3,      508,     0 ), /*   507 loo               */
  S_ST( 's',	3,      509,     0 ), /*   508 loop              */
  S_ST( 't',	3,      510,     0 ), /*   509 loops             */
  S_ST( 'a',	3,      511,     0 ), /*   510 loopst            */
  S_ST( 't',	3,      343,     0 ), /*   511 loopsta           */
  S_ST( 'w',	3,      513,   506 ), /*   512 lo                */
  S_ST( 'p',	3,      514,     0 ), /*   513 low               */
  S_ST( 'r',	3,      515,     0 ), /*   514 lowp              */
  S_ST( 'i',	3,      516,     0 ), /*   515 lowpr             */
  S_ST( 'o',	3,      517,     0 ), /*   516 lowpri            */
  S_ST( 't',	3,      518,     0 ), /*   517 lowprio           */
  S_ST( 'r',	3,      519,     0 ), /*   518 lowpriot          */
  S_ST( 'a',	3,      344,     0 ), /*   519 lowpriotr         */
  S_ST( 'm',	3,      606,   468 ), /*   520                   */
  S_ST( 'a',	3,      539,     0 ), /*   521 m                 */
  S_ST( 'n',	3,      523,     0 ), /*   522 ma                */
  S_ST( 'y',	3,      524,     0 ), /*   523 man               */
  S_ST( 'c',	3,      525,     0 ), /*   524 many              */
  S_ST( 'a',	3,      526,     0 ), /*   525 manyc             */
  S_ST( 's',	3,      527,     0 ), /*   526 manyca            */
  S_ST( 't',	3,      533,     0 ), /*   527 manycas           */
  S_ST( 'c',	3,      529,     0 ), /*   528 manycast          */
  S_ST( 'l',	3,      530,     0 ), /*   529 manycastc         */
  S_ST( 'i',	3,      531,     0 ), /*   530 manycastcl        */
  S_ST( 'e',	3,      532,     0 ), /*   531 manycastcli       */
  S_ST( 'n',	3,      345,     0 ), /*   532 manycastclie      */
  S_ST( 's',	3,      534,   528 ), /*   533 manycast          */
  S_ST( 'e',	3,      535,     0 ), /*   534 manycasts         */
  S_ST( 'r',	3,      536,     0 ), /*   535 manycastse        */
  S_ST( 'v',	3,      537,     0 ), /*   536 manycastser       */
  S_ST( 'e',	3,      346,     0 ), /*   537 manycastserv      */
  S_ST( 's',	3,      347,   522 ), /*   538 ma                */
  S_ST( 'x',	3,      554,   538 ), /*   539 ma                */
  S_ST( 'a',	3,      541,     0 ), /*   540 max               */
  S_ST( 'g',	3,      348,     0 ), /*   541 maxa              */
  S_ST( 'c',	3,      543,   540 ), /*   542 max               */
  S_ST( 'l',	3,      544,     0 ), /*   543 maxc              */
  S_ST( 'o',	3,      545,     0 ), /*   544 maxcl             */
  S_ST( 'c',	3,      349,     0 ), /*   545 maxclo            */
  S_ST( 'd',	3,      550,   542 ), /*   546 max               */
  S_ST( 'e',	3,      548,     0 ), /*   547 maxd              */
  S_ST( 'p',	3,      549,     0 ), /*   548 maxde             */
  S_ST( 't',	3,      350,     0 ), /*   549 maxdep            */
  S_ST( 'i',	3,      551,   547 ), /*   550 maxd              */
  S_ST( 's',	3,      351,     0 ), /*   551 maxdi             */
  S_ST( 'm',	3,      553,   546 ), /*   552 max               */
  S_ST( 'e',	3,      352,     0 ), /*   553 maxm              */
  S_ST( 'p',	3,      555,   552 ), /*   554 max               */
  S_ST( 'o',	3,      556,     0 ), /*   555 maxp              */
  S_ST( 'l',	3,      353,     0 ), /*   556 maxpo             */
  S_ST( 'd',	3,      558,   521 ), /*   557 m                 */
  S_ST( 'n',	3,      559,     0 ), /*   558 md                */
  S_ST( 's',	3,      560,     0 ), /*   559 mdn               */
  S_ST( 't',	3,      561,     0 ), /*   560 mdns              */
  S_ST( 'r',	3,      562,     0 ), /*   561 mdnst             */
  S_ST( 'i',	3,      563,     0 ), /*   562 mdnstr            */
  S_ST( 'e',	3,      354,     0 ), /*   563 mdnstri           */
  S_ST( 'e',	3,      355,   557 ), /*   564 m                 */
  S_ST( 'l',	3,      566,     0 ), /*   565 mem               */
  S_ST( 'o',	3,      567,     0 ), /*   566 meml              */
  S_ST( 'c',	3,      356,     0 ), /*   567 memlo             */
  S_ST( 'i',	3,      569,   564 ), /*   568 m                 */
  S_ST( 'n',	3,      591,     0 ), /*   569 mi                */
  S_ST( 'c',	3,      571,     0 ), /*   570 min               */
  S_ST( 'l',	3,      572,     0 ), /*   571 minc              */
  S_ST( 'o',	3,      573,     0 ), /*   572 mincl             */
  S_ST( 'c',	3,      357,     0 ), /*   573 minclo            */
  S_ST( 'd',	3,      578,   570 ), /*   574 min               */
  S_ST( 'e',	3,      576,     0 ), /*   575 mind              */
  S_ST( 'p',	3,      577,     0 ), /*   576 minde             */
  S_ST( 't',	3,      358,     0 ), /*   577 mindep            */
  S_ST( 'i',	3,      579,   575 ), /*   578 mind              */
  S_ST( 's',	3,      359,     0 ), /*   579 mindi             */
  S_ST( 'i',	3,      581,   574 ), /*   580 min               */
  S_ST( 'm',	3,      582,     0 ), /*   581 mini              */
  S_ST( 'u',	3,      360,     0 ), /*   582 minim             */
  S_ST( 'j',	3,      584,   580 ), /*   583 min               */
  S_ST( 'i',	3,      585,     0 ), /*   584 minj              */
  S_ST( 't',	3,      586,     0 ), /*   585 minji             */
  S_ST( 't',	3,      587,     0 ), /*   586 minjit            */
  S_ST( 'e',	3,      361,     0 ), /*   587 minjitt           */
  S_ST( 'p',	3,      589,   583 ), /*   588 min               */
  S_ST( 'o',	3,      590,     0 ), /*   589 minp              */
  S_ST( 'l',	3,      362,     0 ), /*   590 minpo             */
  S_ST( 's',	3,      592,   588 ), /*   591 min               */
  S_ST( 'a',	3,      593,     0 ), /*   592 mins              */
  S_ST( 'n',	3,      363,     0 ), /*   593 minsa             */
  S_ST( 'o',	3,      596,   568 ), /*   594 m                 */
  S_ST( 'd',	3,      364,     0 ), /*   595 mo                */
  S_ST( 'n',	3,      600,   595 ), /*   596 mo                */
  S_ST( 'i',	3,      598,     0 ), /*   597 mon               */
  S_ST( 't',	3,      599,     0 ), /*   598 moni              */
  S_ST( 'o',	3,      366,     0 ), /*   599 monit             */
  S_ST( 't',	3,      367,   597 ), /*   600 mon               */
  S_ST( 'r',	3,      368,   594 ), /*   601 m                 */
  S_ST( 's',	3,      603,   601 ), /*   602 m                 */
  S_ST( 's',	3,      604,     0 ), /*   603 ms                */
  S_ST( 'n',	3,      605,     0 ), /*   604 mss               */
  S_ST( 't',	3,      335,     0 ), /*   605 mssn              */
  S_ST( 'u',	3,      607,   602 ), /*   606 m                 */
  S_ST( 'l',	3,      608,     0 ), /*   607 mu                */
  S_ST( 't',	3,      609,     0 ), /*   608 mul               */
  S_ST( 'i',	3,      610,     0 ), /*   609 mult              */
  S_ST( 'c',	3,      611,     0 ), /*   610 multi             */
  S_ST( 'a',	3,      612,     0 ), /*   611 multic            */
  S_ST( 's',	3,      613,     0 ), /*   612 multica           */
  S_ST( 't',	3,      614,     0 ), /*   613 multicas          */
  S_ST( 'c',	3,      615,     0 ), /*   614 multicast         */
  S_ST( 'l',	3,      616,     0 ), /*   615 multicastc        */
  S_ST( 'i',	3,      617,     0 ), /*   616 multicastcl       */
  S_ST( 'e',	3,      618,     0 ), /*   617 multicastcli      */
  S_ST( 'n',	3,      369,     0 ), /*   618 multicastclie     */
  S_ST( 'n',	3,      666,   520 ), /*   619                   */
  S_ST( 'i',	3,      370,     0 ), /*   620 n                 */
  S_ST( 'o',	3,      661,   620 ), /*   621 n                 */
  S_ST( 'e',	3,      623,     0 ), /*   622 no                */
  S_ST( 'p',	3,      624,     0 ), /*   623 noe               */
  S_ST( 'e',	3,      625,     0 ), /*   624 noep              */
  S_ST( 'e',	3,      376,     0 ), /*   625 noepe             */
  S_ST( 'l',	3,      627,   622 ), /*   626 no                */
  S_ST( 'i',	3,      628,     0 ), /*   627 nol               */
  S_ST( 'n',	3,      371,     0 ), /*   628 noli              */
  S_ST( 'm',	3,      634,   626 ), /*   629 no                */
  S_ST( 'o',	3,      631,     0 ), /*   630 nom               */
  S_ST( 'd',	3,      632,     0 ), /*   631 nomo              */
  S_ST( 'i',	3,      633,     0 ), /*   632 nomod             */
  S_ST( 'f',	3,      372,     0 ), /*   633 nomodi            */
  S_ST( 'r',	3,      635,   630 ), /*   634 nom               */
  S_ST( 'u',	3,      636,     0 ), /*   635 nomr              */
  S_ST( 'l',	3,      637,     0 ), /*   636 nomru             */
  S_ST( 'i',	3,      638,     0 ), /*   637 nomrul            */
  S_ST( 's',	3,      373,     0 ), /*   638 nomruli           */
  S_ST( 'n',	3,      640,   629 ), /*   639 no                */
  S_ST( 'v',	3,      641,   374 ), /*   640 non               */
  S_ST( 'o',	3,      642,     0 ), /*   641 nonv              */
  S_ST( 'l',	3,      643,     0 ), /*   642 nonvo             */
  S_ST( 'a',	3,      644,     0 ), /*   643 nonvol            */
  S_ST( 't',	3,      645,     0 ), /*   644 nonvola           */
  S_ST( 'i',	3,      646,     0 ), /*   645 nonvolat          */
  S_ST( 'l',	3,      375,     0 ), /*   646 nonvolati         */
  S_ST( 'p',	3,      648,   639 ), /*   647 no                */
  S_ST( 'e',	3,      649,     0 ), /*   648 nop               */
  S_ST( 'e',	3,      377,     0 ), /*   649 nope              */
  S_ST( 'q',	3,      651,   647 ), /*   650 no                */
  S_ST( 'u',	3,      652,     0 ), /*   651 noq               */
  S_ST( 'e',	3,      653,     0 ), /*   652 noqu              */
  S_ST( 'r',	3,      378,     0 ), /*   653 noque             */
  S_ST( 's',	3,      655,   650 ), /*   654 no                */
  S_ST( 'e',	3,      659,     0 ), /*   655 nos               */
  S_ST( 'l',	3,      657,     0 ), /*   656 nose              */
  S_ST( 'e',	3,      658,     0 ), /*   657 nosel             */
  S_ST( 'c',	3,      379,     0 ), /*   658 nosele            */
  S_ST( 'r',	3,      660,   656 ), /*   659 nose              */
  S_ST( 'v',	3,      380,     0 ), /*   660 noser             */
  S_ST( 't',	3,      662,   654 ), /*   661 no                */
  S_ST( 'r',	3,      664,     0 ), /*   662 not               */
  S_ST( 'a',	3,      381,     0 ), /*   663 notr              */
  S_ST( 'u',	3,      665,   663 ), /*   664 notr              */
  S_ST( 's',	3,      382,     0 ), /*   665 notru             */
  S_ST( 't',	3,      383,   621 ), /*   666 n                 */
  S_ST( 'p',	3,      668,     0 ), /*   667 ntp               */
  S_ST( 'o',	3,      669,     0 ), /*   668 ntpp              */
  S_ST( 'r',	3,      384,     0 ), /*   669 ntppo             */
  S_ST( 's',	3,      671,   667 ), /*   670 ntp               */
  S_ST( 'i',	3,      672,     0 ), /*   671 ntps              */
  S_ST( 'g',	3,      673,     0 ), /*   672 ntpsi             */
  S_ST( 'n',	3,      674,     0 ), /*   673 ntpsig            */
  S_ST( 'd',	3,      675,     0 ), /*   674 ntpsign           */
  S_ST( 's',	3,      676,     0 ), /*   675 ntpsignd          */
  S_ST( 'o',	3,      677,     0 ), /*   676 ntpsignds         */
  S_ST( 'c',	3,      678,     0 ), /*   677 ntpsigndso        */
  S_ST( 'k',	3,      679,     0 ), /*   678 ntpsigndsoc       */
  S_ST( 'e',	3,      385,     0 ), /*   679 ntpsigndsock      */
  S_ST( 'o',	3,      681,   619 ), /*   680                   */
  S_ST( 'r',	3,      682,     0 ), /*   681 o                 */
  S_ST( 'p',	3,      683,     0 ), /*   682 or                */
  S_ST( 'h',	3,      684,     0 ), /*   683 orp               */
  S_ST( 'a',	3,      386,     0 ), /*   684 orph              */
  S_ST( 'w',	3,      686,     0 ), /*   685 orphan            */
  S_ST( 'a',	3,      687,     0 ), /*   686 orphanw           */
  S_ST( 'i',	3,      387,     0 ), /*   687 orphanwa          */
  S_ST( 'p',	3,      400,   680 ), /*   688                   */
  S_ST( 'a',	3,      690,     0 ), /*   689 p                 */
  S_ST( 'n',	3,      691,     0 ), /*   690 pa                */
  S_ST( 'i',	3,      389,     0 ), /*   691 pan               */
  S_ST( 'e',	3,      693,   689 ), /*   692 p                 */
  S_ST( 'e',	3,      390,     0 ), /*   693 pe                */
  S_ST( '_',	3,      695,     0 ), /*   694 peer              */
  S_ST( 'c',	3,      696,     0 ), /*   695 peer_             */
  S_ST( 'l',	3,      697,     0 ), /*   696 peer_c            */
  S_ST( 'e',	3,      698,     0 ), /*   697 peer_cl           */
  S_ST( 'a',	3,      699,     0 ), /*   698 peer_cle          */
  S_ST( 'r',	3,      700,     0 ), /*   699 peer_clea         */
  S_ST( '_',	3,      701,     0 ), /*   700 peer_clear        */
  S_ST( 'd',	3,      702,     0 ), /*   701 peer_clear_       */
  S_ST( 'i',	3,      703,     0 ), /*   702 peer_clear_d      */
  S_ST( 'g',	3,      704,     0 ), /*   703 peer_clear_di     */
  S_ST( 'e',	3,      705,     0 ), /*   704 peer_clear_dig    */
  S_ST( 's',	3,      706,     0 ), /*   705 peer_clear_dige   */
  S_ST( 't',	3,      707,     0 ), /*   706 peer_clear_diges  */
  S_ST( '_',	3,      708,     0 ), /*   707 peer_clear_digest */
  S_ST( 'e',	3,      709,     0 ), /*   708 peer_clear_digest_ */
  S_ST( 'a',	3,      710,     0 ), /*   709 peer_clear_digest_e */
  S_ST( 'r',	3,      711,     0 ), /*   710 peer_clear_digest_ea */
  S_ST( 'l',	3,      388,     0 ), /*   711 peer_clear_digest_ear */
  S_ST( 's',	3,      713,   694 ), /*   712 peer              */
  S_ST( 't',	3,      714,     0 ), /*   713 peers             */
  S_ST( 'a',	3,      715,     0 ), /*   714 peerst            */
  S_ST( 't',	3,      391,     0 ), /*   715 peersta           */
  S_ST( 'h',	3,      717,   692 ), /*   716 p                 */
  S_ST( 'o',	3,      718,     0 ), /*   717 ph                */
  S_ST( 'n',	3,      392,     0 ), /*   718 pho               */
  S_ST( 'i',	3,      393,   716 ), /*   719 p                 */
  S_ST( 'f',	3,      721,     0 ), /*   720 pid               */
  S_ST( 'i',	3,      722,     0 ), /*   721 pidf              */
  S_ST( 'l',	3,      394,     0 ), /*   722 pidfi             */
  S_ST( 'o',	3,      725,   719 ), /*   723 p                 */
  S_ST( 'o',	3,      395,     0 ), /*   724 po                */
  S_ST( 'r',	3,      396,   724 ), /*   725 po                */
  S_ST( 'r',	3,      733,   723 ), /*   726 p                 */
  S_ST( 'e',	3,      731,     0 ), /*   727 pr                */
  S_ST( 'e',	3,      729,     0 ), /*   728 pre               */
  S_ST( 'm',	3,      730,     0 ), /*   729 pree              */
  S_ST( 'p',	3,      397,     0 ), /*   730 preem             */
  S_ST( 'f',	3,      732,   728 ), /*   731 pre               */
  S_ST( 'e',	3,      398,     0 ), /*   732 pref              */
  S_ST( 'o',	3,      746,   727 ), /*   733 pr                */
  S_ST( 'c',	3,      735,     0 ), /*   734 pro               */
  S_ST( '_',	3,      736,     0 ), /*   735 proc              */
  S_ST( 'd',	3,      737,     0 ), /*   736 proc_             */
  S_ST( 'e',	3,      738,     0 ), /*   737 proc_d            */
  S_ST( 'l',	3,      739,     0 ), /*   738 proc_de           */
  S_ST( 'a',	3,      460,     0 ), /*   739 proc_del          */
  S_ST( 'p',	3,      741,   734 ), /*   740 pro               */
  S_ST( '_',	3,      742,     0 ), /*   741 prop              */
  S_ST( 'd',	3,      743,     0 ), /*   742 prop_             */
  S_ST( 'e',	3,      744,     0 ), /*   743 prop_d            */
  S_ST( 'l',	3,      745,     0 ), /*   744 prop_de           */
  S_ST( 'a',	3,      459,     0 ), /*   745 prop_del          */
  S_ST( 't',	3,      747,   740 ), /*   746 pro               */
  S_ST( 'o',	3,      748,     0 ), /*   747 prot              */
  S_ST( 's',	3,      749,     0 ), /*   748 proto             */
  S_ST( 't',	3,      750,     0 ), /*   749 protos            */
  S_ST( 'a',	3,      751,     0 ), /*   750 protost           */
  S_ST( 't',	3,      399,     0 ), /*   751 protosta          */
  S_ST( 'r',	3,      783,   688 ), /*   752                   */
  S_ST( 'a',	3,      759,     0 ), /*   753 r                 */
  S_ST( 'n',	3,      755,     0 ), /*   754 ra                */
  S_ST( 'd',	3,      756,     0 ), /*   755 ran               */
  S_ST( 'f',	3,      757,     0 ), /*   756 rand              */
  S_ST( 'i',	3,      758,     0 ), /*   757 randf             */
  S_ST( 'l',	3,      401,     0 ), /*   758 randfi            */
  S_ST( 'w',	3,      760,   754 ), /*   759 ra                */
  S_ST( 's',	3,      761,     0 ), /*   760 raw               */
  S_ST( 't',	3,      762,     0 ), /*   761 raws              */
  S_ST( 'a',	3,      763,     0 ), /*   762 rawst             */
  S_ST( 't',	3,      402,     0 ), /*   763 rawsta            */
  S_ST( 'e',	3,      780,   753 ), /*   764 r                 */
  S_ST( 'f',	3,      766,     0 ), /*   765 re                */
  S_ST( 'i',	3,      403,     0 ), /*   766 ref               */
  S_ST( 'q',	3,      768,   765 ), /*   767 re                */
  S_ST( 'u',	3,      769,     0 ), /*   768 req               */
  S_ST( 'e',	3,      770,     0 ), /*   769 requ              */
  S_ST( 's',	3,      771,     0 ), /*   770 reque             */
  S_ST( 't',	3,      772,     0 ), /*   771 reques            */
  S_ST( 'k',	3,      773,     0 ), /*   772 request           */
  S_ST( 'e',	3,      404,     0 ), /*   773 requestk          */
  S_ST( 's',	3,      776,   767 ), /*   774 re                */
  S_ST( 'e',	3,      405,     0 ), /*   775 res               */
  S_ST( 't',	3,      777,   775 ), /*   776 res               */
  S_ST( 'r',	3,      778,     0 ), /*   777 rest              */
  S_ST( 'i',	3,      779,     0 ), /*   778 restr             */
  S_ST( 'c',	3,      406,     0 ), /*   779 restri            */
  S_ST( 'v',	3,      781,   774 ), /*   780 re                */
  S_ST( 'o',	3,      782,     0 ), /*   781 rev               */
  S_ST( 'k',	3,      407,     0 ), /*   782 revo              */
  S_ST( 'l',	3,      784,   764 ), /*   783 r                 */
  S_ST( 'i',	3,      785,     0 ), /*   784 rl                */
  S_ST( 'm',	3,      786,     0 ), /*   785 rli               */
  S_ST( 'i',	3,      408,     0 ), /*   786 rlim              */
  S_ST( 's',	3,      860,   752 ), /*   787                   */
  S_ST( 'a',	3,      789,     0 ), /*   788 s                 */
  S_ST( 'v',	3,      790,     0 ), /*   789 sa                */
  S_ST( 'e',	3,      791,     0 ), /*   790 sav               */
  S_ST( 'c',	3,      792,     0 ), /*   791 save              */
  S_ST( 'o',	3,      793,     0 ), /*   792 savec             */
  S_ST( 'n',	3,      794,     0 ), /*   793 saveco            */
  S_ST( 'f',	3,      795,     0 ), /*   794 savecon           */
  S_ST( 'i',	3,      796,     0 ), /*   795 saveconf          */
  S_ST( 'g',	3,      797,     0 ), /*   796 saveconfi         */
  S_ST( 'd',	3,      798,     0 ), /*   797 saveconfig        */
  S_ST( 'i',	3,      409,     0 ), /*   798 saveconfigd       */
  S_ST( 'e',	3,      809,   788 ), /*   799 s                 */
  S_ST( 'r',	3,      801,     0 ), /*   800 se                */
  S_ST( 'v',	3,      802,     0 ), /*   801 ser               */
  S_ST( 'e',	3,      410,     0 ), /*   802 serv              */
  S_ST( '_',	3,      804,     0 ), /*   803 server            */
  S_ST( 'o',	3,      805,     0 ), /*   804 server_           */
  S_ST( 'f',	3,      806,     0 ), /*   805 server_o          */
  S_ST( 'f',	3,      807,     0 ), /*   806 server_of         */
  S_ST( 's',	3,      808,     0 ), /*   807 server_off        */
  S_ST( 'e',	3,      454,     0 ), /*   808 server_offs       */
  S_ST( 't',	3,      810,   800 ), /*   809 se                */
  S_ST( 'v',	3,      811,     0 ), /*   810 set               */
  S_ST( 'a',	3,      411,     0 ), /*   811 setv              */
  S_ST( 'i',	3,      813,   799 ), /*   812 s                 */
  S_ST( 'm',	3,      814,     0 ), /*   813 si                */
  S_ST( 'u',	3,      815,     0 ), /*   814 sim               */
  S_ST( 'l',	3,      816,     0 ), /*   815 simu              */
  S_ST( 'a',	3,      817,     0 ), /*   816 simul             */
  S_ST( 't',	3,      818,     0 ), /*   817 simula            */
  S_ST( 'i',	3,      819,   451 ), /*   818 simulat           */
  S_ST( 'o',	3,      820,     0 ), /*   819 simulati          */
  S_ST( 'n',	3,      821,     0 ), /*   820 simulatio         */
  S_ST( '_',	3,      822,     0 ), /*   821 simulation        */
  S_ST( 'd',	3,      823,     0 ), /*   822 simulation_       */
  S_ST( 'u',	3,      824,     0 ), /*   823 simulation_d      */
  S_ST( 'r',	3,      825,     0 ), /*   824 simulation_du     */
  S_ST( 'a',	3,      826,     0 ), /*   825 simulation_dur    */
  S_ST( 't',	3,      827,     0 ), /*   826 simulation_dura   */
  S_ST( 'i',	3,      828,     0 ), /*   827 simulation_durat  */
  S_ST( 'o',	3,      453,     0 ), /*   828 simulation_durati */
  S_ST( 'o',	3,      830,   812 ), /*   829 s                 */
  S_ST( 'u',	3,      831,     0 ), /*   830 so                */
  S_ST( 'r',	3,      832,     0 ), /*   831 sou               */
  S_ST( 'c',	3,      412,     0 ), /*   832 sour              */
  S_ST( 't',	3,      856,   829 ), /*   833 s                 */
  S_ST( 'a',	3,      840,     0 ), /*   834 st                */
  S_ST( 'c',	3,      836,     0 ), /*   835 sta               */
  S_ST( 'k',	3,      837,     0 ), /*   836 stac              */
  S_ST( 's',	3,      838,     0 ), /*   837 stack             */
  S_ST( 'i',	3,      839,     0 ), /*   838 stacks            */
  S_ST( 'z',	3,      413,     0 ), /*   839 stacksi           */
  S_ST( 't',	3,      415,   835 ), /*   840 sta               */
  S_ST( 'i',	3,      842,     0 ), /*   841 stat              */
  S_ST( 's',	3,      843,     0 ), /*   842 stati             */
  S_ST( 't',	3,      844,     0 ), /*   843 statis            */
  S_ST( 'i',	3,      845,     0 ), /*   844 statist           */
  S_ST( 'c',	3,      414,     0 ), /*   845 statisti          */
  S_ST( 'd',	3,      847,     0 ), /*   846 stats             */
  S_ST( 'i',	3,      416,     0 ), /*   847 statsd            */
  S_ST( 'e',	3,      417,   834 ), /*   848 st                */
  S_ST( 'b',	3,      850,     0 ), /*   849 step              */
  S_ST( 'a',	3,      851,     0 ), /*   850 stepb             */
  S_ST( 'c',	3,      418,     0 ), /*   851 stepba            */
  S_ST( 'f',	3,      853,   849 ), /*   852 step              */
  S_ST( 'w',	3,      419,     0 ), /*   853 stepf             */
  S_ST( 'o',	3,      855,   852 ), /*   854 step              */
  S_ST( 'u',	3,      420,     0 ), /*   855 stepo             */
  S_ST( 'r',	3,      857,   848 ), /*   856 st                */
  S_ST( 'a',	3,      858,     0 ), /*   857 str               */
  S_ST( 't',	3,      859,     0 ), /*   858 stra              */
  S_ST( 'u',	3,      421,     0 ), /*   859 strat             */
  S_ST( 'y',	3,      423,   833 ), /*   860 s                 */
  S_ST( 's',	3,      862,     0 ), /*   861 sys               */
  S_ST( 't',	3,      863,     0 ), /*   862 syss              */
  S_ST( 'a',	3,      864,     0 ), /*   863 sysst             */
  S_ST( 't',	3,      424,     0 ), /*   864 syssta            */
  S_ST( 't',	3,      891,   787 ), /*   865                   */
  S_ST( 'i',	3,      877,     0 ), /*   866 t                 */
  S_ST( 'c',	3,      425,     0 ), /*   867 ti                */
  S_ST( 'm',	3,      870,   867 ), /*   868 ti                */
  S_ST( 'e',	3,      428,     0 ), /*   869 tim               */
  S_ST( 'i',	3,      871,   869 ), /*   870 tim               */
  S_ST( 'n',	3,      872,     0 ), /*   871 timi              */
  S_ST( 'g',	3,      873,     0 ), /*   872 timin             */
  S_ST( 's',	3,      874,     0 ), /*   873 timing            */
  S_ST( 't',	3,      875,     0 ), /*   874 timings           */
  S_ST( 'a',	3,      876,     0 ), /*   875 timingst          */
  S_ST( 't',	3,      429,     0 ), /*   876 timingsta         */
  S_ST( 'n',	3,      878,   868 ), /*   877 ti                */
  S_ST( 'k',	3,      879,     0 ), /*   878 tin               */
  S_ST( 'e',	3,      430,     0 ), /*   879 tink              */
  S_ST( 'o',	3,      431,   866 ), /*   880 t                 */
  S_ST( 'r',	3,      883,   880 ), /*   881 t                 */
  S_ST( 'a',	3,      432,     0 ), /*   882 tr                */
  S_ST( 'u',	3,      884,   882 ), /*   883 tr                */
  S_ST( 's',	3,      885,   433 ), /*   884 tru               */
  S_ST( 't',	3,      886,     0 ), /*   885 trus              */
  S_ST( 'e',	3,      887,     0 ), /*   886 trust             */
  S_ST( 'd',	3,      888,     0 ), /*   887 truste            */
  S_ST( 'k',	3,      889,     0 ), /*   888 trusted           */
  S_ST( 'e',	3,      434,     0 ), /*   889 trustedk          */
  S_ST( 't',	3,      435,   881 ), /*   890 t                 */
  S_ST( 'y',	3,      892,   890 ), /*   891 t                 */
  S_ST( 'p',	3,      436,     0 ), /*   892 ty                */
  S_ST( 'u',	3,      894,   865 ), /*   893                   */
  S_ST( 'n',	3,      900,     0 ), /*   894 u                 */
  S_ST( 'c',	3,      896,     0 ), /*   895 un                */
  S_ST( 'o',	3,      897,     0 ), /*   896 unc               */
  S_ST( 'n',	3,      898,     0 ), /*   897 unco              */
  S_ST( 'f',	3,      899,     0 ), /*   898 uncon             */
  S_ST( 'i',	3,      441,     0 ), /*   899 unconf            */
  S_ST( 'p',	3,      901,   895 ), /*   900 un                */
  S_ST( 'e',	3,      902,     0 ), /*   901 unp               */
  S_ST( 'e',	3,      442,     0 ), /*   902 unpe              */
  S_ST( '_',	3,      923,     0 ), /*   903 unpeer            */
  S_ST( 'c',	3,      905,     0 ), /*   904 unpeer_           */
  S_ST( 'r',	3,      906,     0 ), /*   905 unpeer_c          */
  S_ST( 'y',	3,      907,     0 ), /*   906 unpeer_cr         */
  S_ST( 'p',	3,      908,     0 ), /*   907 unpeer_cry        */
  S_ST( 't',	3,      909,     0 ), /*   908 unpeer_cryp       */
  S_ST( 'o',	3,      910,     0 ), /*   909 unpeer_crypt      */
  S_ST( '_',	3,      915,     0 ), /*   910 unpeer_crypto     */
  S_ST( 'e',	3,      912,     0 ), /*   911 unpeer_crypto_    */
  S_ST( 'a',	3,      913,     0 ), /*   912 unpeer_crypto_e   */
  S_ST( 'r',	3,      914,     0 ), /*   913 unpeer_crypto_ea  */
  S_ST( 'l',	3,      438,     0 ), /*   914 unpeer_crypto_ear */
  S_ST( 'n',	3,      916,   911 ), /*   915 unpeer_crypto_    */
  S_ST( 'a',	3,      917,     0 ), /*   916 unpeer_crypto_n   */
  S_ST( 'k',	3,      918,     0 ), /*   917 unpeer_crypto_na  */
  S_ST( '_',	3,      919,     0 ), /*   918 unpeer_crypto_nak */
  S_ST( 'e',	3,      920,     0 ), /*   919 unpeer_crypto_nak_ */
  S_ST( 'a',	3,      921,     0 ), /*   920 unpeer_crypto_nak_e */
  S_ST( 'r',	3,      922,     0 ), /*   921 unpeer_crypto_nak_ea */
  S_ST( 'l',	3,      439,     0 ), /*   922 unpeer_crypto_nak_ear */
  S_ST( 'd',	3,      924,   904 ), /*   923 unpeer_           */
  S_ST( 'i',	3,      925,     0 ), /*   924 unpeer_d          */
  S_ST( 'g',	3,      926,     0 ), /*   925 unpeer_di         */
  S_ST( 'e',	3,      927,     0 ), /*   926 unpeer_dig        */
  S_ST( 's',	3,      928,     0 ), /*   927 unpeer_dige       */
  S_ST( 't',	3,      929,     0 ), /*   928 unpeer_diges      */
  S_ST( '_',	3,      930,     0 ), /*   929 unpeer_digest     */
  S_ST( 'e',	3,      931,     0 ), /*   930 unpeer_digest_    */
  S_ST( 'a',	3,      932,     0 ), /*   931 unpeer_digest_e   */
  S_ST( 'r',	3,      933,     0 ), /*   932 unpeer_digest_ea  */
  S_ST( 'l',	3,      440,     0 ), /*   933 unpeer_digest_ear */
  S_ST( 'v',	3,      935,   893 ), /*   934                   */
  S_ST( 'e',	3,      936,     0 ), /*   935 v                 */
  S_ST( 'r',	3,      937,     0 ), /*   936 ve                */
  S_ST( 's',	3,      938,     0 ), /*   937 ver               */
  S_ST( 'i',	3,      939,     0 ), /*   938 vers              */
  S_ST( 'o',	3,      443,     0 ), /*   939 versi             */
  S_ST( 'w',	3,      947,   934 ), /*   940                   */
  S_ST( 'a',	3,      942,     0 ), /*   941 w                 */
  S_ST( 'n',	3,      943,     0 ), /*   942 wa                */
  S_ST( 'd',	3,      944,     0 ), /*   943 wan               */
  S_ST( 'e',	3,      457,     0 ), /*   944 wand              */
  S_ST( 'e',	3,      946,   941 ), /*   945 w                 */
  S_ST( 'e',	3,      445,     0 ), /*   946 we                */
  S_ST( 'i',	3,      948,   945 ), /*   947 w                 */
  S_ST( 'l',	3,      949,     0 ), /*   948 wi                */
  S_ST( 'd',	3,      950,     0 ), /*   949 wil               */
  S_ST( 'c',	3,      951,     0 ), /*   950 wild              */
  S_ST( 'a',	3,      952,     0 ), /*   951 wildc             */
  S_ST( 'r',	3,      446,     0 ), /*   952 wildca            */
  S_ST( 'x',	3,      954,   940 ), /*   953                   */
  S_ST( 'l',	3,      955,     0 ), /*   954 x                 */
  S_ST( 'e',	3,      956,     0 ), /*   955 xl                */
  S_ST( 'a',	3,      957,     0 ), /*   956 xle               */
  S_ST( 'v',	3,      447,     0 ), /*   957 xlea              */
  S_ST( 'y',	3,      959,   953 ), /*   958 [initial state]   */
  S_ST( 'e',	3,      960,     0 ), /*   959 y                 */
  S_ST( 'a',	3,      448,     0 )  /*   960 ye                */
};

